import {ref as storageRef,getMetadata,uploadBytes} from 'firebase/storage';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,updateDoc} from 'firebase/firestore';
import * as firestoreSdk from 'firebase/firestore';
import {createFirebaseRepository} from '../../src/backend/firebaseRepository.js';
import {spawn} from 'node:child_process';
import {chromium} from '../../node_modules/@playwright/test/index.mjs';

test('production tenant rules and deployed function handler: valid school, verified auth, cross-tenant denial',{skip:process.env.PERFECTEDU_TENANT_TEST!=='true',timeout:180000},async()=>{
 assert.ok(process.env.FIRESTORE_EMULATOR_HOST);
 const env=await initializeTestEnvironment({projectId:'demo-gbs-school',storage:{host:'127.0.0.1',port:9199,rules:await readFile(new URL('../storage.rules',import.meta.url),'utf8')},firestore:{host:'127.0.0.1',port:8080,rules:await readFile(new URL('../firestore.production.rules',import.meta.url),'utf8')}});
 try{
  await env.clearFirestore();
  const password=crypto.randomUUID()+'!Aa8';
  const auth=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=emulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:`test-${crypto.randomUUID()}@example.invalid`,password,returnSecureToken:true})}).then(r=>r.json());
  assert.ok(auth.idToken);
  const resources=['students','teachers','attendance','fees','results','settings','notifications','library','sports','trips','certificates','communication_logs','parents','academic_years','homework','exams','scholarships'];
  await env.withSecurityRulesDisabled(async ctx=>{
   for(const [id,udise]of [['gbs-school','27190113523'],['other-school','11111111111']])await setDoc(doc(ctx.firestore(),'schools',id),{tenantId:id,status:'ACTIVE',udise,schoolName:'TEST '+id});
   for(const [school,uid,role]of [['gbs-school',auth.localId,'SUPER_ADMIN'],['other-school','other-admin','SCHOOL_SUPER_ADMIN'],['gbs-school','teacher','Teacher']])await setDoc(doc(ctx.firestore(),`schools/${school}/members/${uid}`),{active:true,passwordSetupComplete:true,role,modules:['Dashboard','Students','Settings','Automation','Certificates','Staff','Backup','Homework','Classwork','Meetings','Visits','Checkout','AccessSetup','Attendance'],resources,classIds:['8:A'],studentIds:[]});
   await setDoc(doc(ctx.firestore(),'students/legacy-test'),{name:'TEST LEGACY'});
  });
  const admin=env.authenticatedContext(auth.localId).firestore(),other=env.authenticatedContext('other-admin').firestore(),teacher=env.authenticatedContext('teacher').firestore(),anonymous=env.unauthenticatedContext().firestore();
  await assertSucceeds(getDoc(doc(admin,'students/legacy-test')));
  for(const client of [other,teacher,anonymous])await assertFails(getDoc(doc(client,'students/legacy-test')));
  await assertFails(updateDoc(doc(teacher,`schools/gbs-school/members/${auth.localId}`),{role:'Teacher'}));
  await assertFails(updateDoc(doc(teacher,'schools/gbs-school/members/teacher'),{role:'SUPER_ADMIN'}));
  for(const name of resources){await assertFails(getDoc(doc(other,`schools/gbs-school/${name}/test`)));await assertFails(setDoc(doc(other,`schools/gbs-school/${name}/test`),{value:'attack'}));}
  const repo=createFirebaseRepository({db:admin,auth:{currentUser:{uid:auth.localId}},schoolId:'gbs-school',firestoreSdk});await repo.membership();
  const data={id:'TEST-STUDENT',name:'TEST Student',grNo:'TEST-GR',className:'8',division:'A',academicYear:'2026-27'};
  await repo.mutate({collection:'students',id:data.id,classId:'8:A',expectedVersion:0,mutationId:crypto.randomUUID(),data});
  assert.equal((await repo.read('students',data.id)).data.name,'TEST Student');
  await repo.mutate({collection:'students',id:data.id,classId:'8:A',expectedVersion:1,mutationId:crypto.randomUUID(),data:{...data,name:'TEST Edited'}});
  await env.withSecurityRulesDisabled(ctx=>setDoc(doc(ctx.firestore(),'schools/gbs-school/members/headmaster'),{active:true,passwordSetupComplete:true,role:'HEADMASTER',resources:['teachers'],modules:['Staff'],classIds:[],studentIds:[]}));
  const headmaster=env.authenticatedContext('headmaster').firestore();
  const staffRepo=createFirebaseRepository({db:headmaster,auth:{currentUser:{uid:'headmaster'}},schoolId:'gbs-school',firestoreSdk});await staffRepo.membership();
  await repo.mutate({collection:'teachers',id:'TEST-EMPLOYEE',classId:'',expectedVersion:0,mutationId:crypto.randomUUID(),data:{kind:'teacher',name:'TEST Employee'}});
  const staffRow={kind:'staff_attendance',employeeId:'TEST-EMPLOYEE',date:'2026-09-24',status:'Present'};
  const staffMutation={collection:'teachers',id:'staff_2026-09-24_TEST-EMPLOYEE',classId:'',expectedVersion:0,mutationId:crypto.randomUUID(),data:staffRow};
  await staffRepo.mutate(staffMutation);
  await assert.rejects(staffRepo.mutate({...staffMutation,expectedVersion:1,mutationId:crypto.randomUUID(),data:{...staffRow,status:'Late'}}));
  await staffRepo.mutate({...staffMutation,expectedVersion:1,mutationId:crypto.randomUUID(),data:{...staffRow,status:'Late',correctionReason:'TEST corrected arrival'}});
  await assert.rejects(staffRepo.mutate({...staffMutation,expectedVersion:2,deleted:true,mutationId:crypto.randomUUID(),data:{...staffRow,correctionReason:'TEST deletion denied'}}));
  await assert.rejects(staffRepo.mutate({...staffMutation,id:'staff_2026-09-24_FOREIGN',data:{...staffRow,employeeId:'FOREIGN'}}));
  await assertFails(updateDoc(doc(headmaster,'schools/gbs-school/audit_logs/teachers_staff_2026-09-24_TEST-EMPLOYEE_2'),{actor:'tampered'}));
  await assertFails(getDoc(doc(other,'schools/gbs-school/teachers/staff_2026-09-24_TEST-EMPLOYEE')));
  for(const role of ['TEACHER','HEADMASTER','CLERK','STAFF','ACCOUNTANT','LIBRARIAN','SPORTS_TEACHER','READ_ONLY','SCHOOL_ADMIN']){
   const uid='role-'+role;await env.withSecurityRulesDisabled(ctx=>setDoc(doc(ctx.firestore(),'schools/gbs-school/members/'+uid),{role,active:true,passwordSetupComplete:true,resources,modules:['Students','Fees','Library'],classIds:['8:A'],studentIds:[]}));const client=env.authenticatedContext(uid).firestore();await assertSucceeds(getDoc(doc(client,'schools/gbs-school/students/TEST-STUDENT')));await assertFails(getDoc(doc(client,'schools/other-school/students/TEST-STUDENT')));await assertFails(updateDoc(doc(client,'schools/gbs-school/members/'+uid),{role:'SUPER_ADMIN'}));
   const scoped=createFirebaseRepository({db:client,auth:{currentUser:{uid}},schoolId:'gbs-school',firestoreSdk});await scoped.membership();
   const mutation={collection:role==='LIBRARIAN'?'library':'fees',id:'TEST-'+role,classId:role==='LIBRARIAN'?'':'8:A',expectedVersion:0,mutationId:crypto.randomUUID(),data:role==='LIBRARIAN'?{kind:'book',name:'TEST role book'}:{studentId:'TEST-STUDENT',total:100,paid:0}};
   if(['ACCOUNTANT','SCHOOL_ADMIN','LIBRARIAN'].includes(role))await scoped.mutate(mutation);else if(['TEACHER','READ_ONLY','SPORTS_TEACHER'].includes(role))await assert.rejects(scoped.mutate(mutation));
  }
  const call=async(body,token)=>{const r=await fetch('http://127.0.0.1:5001/demo-gbs-school/asia-south1/perfectEduAuth',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
  const school=await call({action:'school',udise:'27190113523'});assert.equal(school.status,200);assert.equal(school.data.school.id,'gbs-school');
  assert.equal((await call({action:'session',udise:'27190113523'},auth.idToken)).status,200);
  assert.equal((await call({action:'session',udise:'11111111111'},auth.idToken)).status,403);
  assert.equal((await call({action:'session',udise:'27190113523'})).status,401);
  assert.equal((await call({action:'platform-list'},auth.idToken)).status,403);
  await env.withSecurityRulesDisabled(ctx=>setDoc(doc(ctx.firestore(),`platform_members/${auth.localId}`),{active:true,role:'PLATFORM_SUPER_ADMIN'}));
  const support=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=emulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'test-support@example.invalid',password,returnSecureToken:true})}).then(r=>r.json());assert.equal((await call({action:'platform-save-authority',user:{email:support.email,role:'PLATFORM_SUPPORT',active:true}},auth.idToken)).status,200);assert.equal((await call({action:'platform-session'},support.idToken)).data.role,'PLATFORM_SUPPORT');assert.equal((await call({action:'platform-list'},support.idToken)).status,200);
  for(const action of ['platform-save-school','platform-save-authority','platform-users','platform-school','platform-settings','platform-authorities'])assert.equal((await call({action,schoolId:'gbs-school'},support.idToken)).status,403);
  assert.equal((await call({action:'platform-save-authority',user:{email:auth.email,role:'PLATFORM_SUPPORT',active:true}},auth.idToken)).status,409);
  const platformSchool=(id,udise)=>({tenantId:id,udise,schoolCode:id,schoolNameEn:'TEST '+id,schoolNameMr:'चाचणी शाळा',status:'ACTIVE',academicYear:'2026-27'});
  for(const [id,code]of [['test-school-a','11111111112'],['test-school-b','11111111113']])assert.equal((await call({action:'platform-save-school',school:platformSchool(id,code)},auth.idToken)).status,200);
  assert.equal((await call({action:'platform-save-school',school:platformSchool('duplicate-school','11111111112')},auth.idToken)).status,409);
  assert.equal((await call({action:'platform-save-school',school:{...platformSchool('test-school-a','11111111112'),id:'test-school-a',district:'TEST UPDATED'}},auth.idToken)).status,200);
  const schoolUsers=[];
  for(const schoolId of ['test-school-a','test-school-b']){
   const schoolUser=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=emulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:`${schoolId}@example.invalid`,password,returnSecureToken:true})}).then(r=>r.json());schoolUsers.push(schoolUser);
   assert.equal((await call({action:'platform-save-admin',schoolId,user:{email:schoolUser.email,name:'TEST Admin',modules:['Dashboard','Students'],active:true}},auth.idToken)).status,200);
   assert.equal((await call({action:'platform-list'},schoolUser.idToken)).status,403);
   const client=env.authenticatedContext(schoolUser.localId).firestore();await assertFails(setDoc(doc(client,`platform_members/${schoolUser.localId}`),{active:true,role:'PLATFORM_SUPER_ADMIN'}));
   const schoolRepo=createFirebaseRepository({db:client,auth:{currentUser:{uid:schoolUser.localId}},schoolId,firestoreSdk});await schoolRepo.membership();await schoolRepo.mutate({collection:'students',id:'TEST-STUDENT',classId:'8:A',expectedVersion:0,mutationId:crypto.randomUUID(),data:{...data,name:'TEST '+schoolId}});
   const otherSchool=schoolId==='test-school-a'?'test-school-b':'test-school-a';await assertFails(getDoc(doc(client,`schools/${otherSchool}/students/TEST-STUDENT`)));
   assert.equal((await call({action:'platform-school',schoolId,collection:'students'},auth.idToken)).data.records[0].data.name,'TEST '+schoolId);
  }
  const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5298','--strictPort'],{cwd:new URL('../../',import.meta.url),stdio:'ignore',windowsHide:true,env:{...process.env,DEV_ADMIN_LOGIN:'false',VITE_SCHOOL_DATA_MODE:'firebase',VITE_SCHOOL_ID:'gbs-school',VITE_FIREBASE_PROJECT_ID:'demo-gbs-school',VITE_FIREBASE_API_KEY:'emulator-only',VITE_FIREBASE_APP_ID:'emulator-web',VITE_FIREBASE_STORAGE_BUCKET:'demo-gbs-school.appspot.com',VITE_FIREBASE_AUTH_DOMAIN:'demo-gbs-school.firebaseapp.com',VITE_FIREBASE_EMULATORS:'true',VITE_TENANT_AUTH_URL:'http://127.0.0.1:5001/demo-gbs-school/asia-south1/perfectEduAuth'}});
  let browser;
  try{
   for(let i=0;i<50;i++){try{if((await fetch('http://127.0.0.1:5298/login')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
   browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.on('pageerror',error=>console.log('Browser error:',error.message));await page.goto('http://127.0.0.1:5298/login');await page.getByRole('button',{name:'EN',exact:true}).click();
   await page.getByLabel('School UDISE Code',{exact:true}).fill('27190113523');await page.getByLabel('Email',{exact:true}).fill(auth.email);
   await page.locator('.perfectedu-school-preview').waitFor();assert.match(await page.locator('.perfectedu-school-preview').innerText(),/TEST gbs-school/);
   await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Login',exact:true}).click();await page.locator('.portal-shell').waitFor({timeout:30000});
   assert.match(await page.locator('.perfectedu-tenant-banner').innerText(),/27190113523/);
   assert.ok(!(await page.locator('body').innerText()).includes('School sign-in configuration is required'));
   await page.locator('.portal-nav-group').filter({has:page.locator('[data-nav="Settings"]')}).first().locator('.portal-group-trigger').click();await page.locator('[data-nav="Settings"]').first().click();await page.locator('input[name="schoolName"]').fill('TEST School Settings Shared');await page.getByRole('button',{name:'Save Settings',exact:true}).click();
   for(let i=0;i<40;i++){const row=await getDoc(doc(admin,'schools/gbs-school/settings/general'));if(row.data()?.data?.schoolName==='TEST School Settings Shared')break;await new Promise(r=>setTimeout(r,100));}
   assert.equal((await getDoc(doc(admin,'schools/gbs-school/settings/general'))).data().data.schoolName,'TEST School Settings Shared');await assertFails(getDoc(doc(other,'schools/gbs-school/settings/general')));
   assert.equal(await page.evaluate(()=>localStorage.getItem('schoolSettings')),null);
   await page.locator('.portal-nav-group').filter({has:page.locator('[data-nav="Certificates"]')}).first().locator('.portal-group-trigger').click();await page.locator('[data-nav="Certificates"]').first().click();
   await page.getByLabel('Document student',{exact:true}).selectOption('TEST-STUDENT');await page.locator('.import-actions button').first().click();await page.getByRole('button',{name:'Generate Bonafide',exact:true}).click();await page.getByRole('heading',{name:/Issue history.*1/,exact:true}).waitFor();
   const issued=await repo.list('certificates');assert.equal(issued.length,1);assert.equal(issued[0].data.studentId,'TEST-STUDENT');await assertFails(getDoc(doc(other,'schools/gbs-school/certificates/'+issued[0].id)));assert.equal(await page.evaluate(()=>localStorage.getItem('erp_pro_certificates')),null);
   await page.getByLabel('Format',{exact:true}).selectOption('Leaving Certificate');const fields=page.locator('.workflow-panel .form-grid input');for(const [i,value]of [[2,'TEST transfer'],[3,'8'],[4,'Good'],[5,'Good']])await fields.nth(i).fill(value);await page.getByLabel('Confirm actual LC issue',{exact:false}).check();await page.locator('.import-actions button').first().click();await page.getByRole('button',{name:'Generate document',exact:true}).click();await page.getByRole('heading',{name:/Issue history.*2/,exact:true}).waitFor();assert.equal((await repo.read('students','TEST-STUDENT')).data.status,'TC/LC Issued');assert.equal((await repo.read('students','TEST-STUDENT')).data.movements.at(-1).actor,auth.localId);
   const queueResults=await page.evaluate(async()=>{const {saveSharedMessageJobs}=await import('/src/services/sharedMessageQueue.js');const job={key:'TEST-ABSENT-ONCE',studentId:'TEST-STUDENT',type:'Absent',status:'Queued',message:'TEST notice',date:'2026-09-24'};return (await Promise.allSettled([saveSharedMessageJobs([job]),saveSharedMessageJobs([job])])).map(r=>r.status);});assert.equal(queueResults.filter(s=>s==='fulfilled').length,1);
   const queue=(await repo.list('communication_logs')).filter(r=>r.data.kind==='notification_job');assert.equal(queue.length,1);assert.equal(queue[0].data.dryRun,true);await assertFails(getDoc(doc(other,'schools/gbs-school/communication_logs/'+queue[0].id)));
   await page.locator('.portal-nav-group').filter({has:page.locator('[data-nav="Staff"]')}).first().locator('.portal-group-trigger').click();await page.locator('[data-nav="Staff"]').first().click();await page.getByLabel('Staff status TEST Employee',{exact:true}).selectOption('Absent');await page.getByLabel('Correction reason',{exact:true}).fill('TEST browser correction');await page.getByRole('button',{name:'Save staff attendance',exact:true}).click();await page.getByText('Staff attendance saved to Firestore',{exact:false}).waitFor();assert.equal((await repo.read('teachers','staff_2026-09-24_TEST-EMPLOYEE')).data.status,'Absent');
   const navigateModule=async name=>{await page.locator('.portal-nav-group').filter({has:page.locator('[data-nav="'+name+'"]')}).first().locator('.portal-group-trigger').click();await page.locator('[data-nav="'+name+'"]').first().click();};
   await navigateModule('Classwork');const classInputs=page.locator('.form-grid input');await classInputs.nth(0).fill('2026-09-24');await classInputs.nth(1).fill('8');await classInputs.nth(2).fill('TEST Science');await page.getByLabel('Division',{exact:true}).fill('A');await page.locator('textarea').fill('TEST class lesson');await page.getByRole('button',{name:'Save Classwork',exact:true}).click();await page.getByRole('button',{name:'Edit Classwork',exact:true}).click();await page.locator('textarea').fill('TEST updated lesson');await page.getByRole('button',{name:'Save Classwork',exact:true}).click();await page.getByRole('cell',{name:'TEST updated lesson',exact:true}).waitFor();const classRecord=(await repo.list('homework')).find(r=>r.data.kind==='classwork');assert.ok(classRecord);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Archive Classwork',exact:true}).click();await page.getByRole('button',{name:'Edit Classwork',exact:true}).waitFor({state:'hidden'});assert.equal((await getDoc(doc(admin,'schools/gbs-school/homework/'+classRecord.id))).data().deleted,true);
   await navigateModule('Meetings');await page.getByLabel('Student',{exact:true}).selectOption('TEST-STUDENT');for(const [label,value]of [['parent','TEST Parent'],['teacher','TEST Teacher'],['time','09:00'],['purpose','TEST review']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole('button',{name:'Save Interaction',exact:true}).click();await page.getByRole('button',{name:'Edit interaction',exact:true}).click();await page.getByLabel('purpose',{exact:true}).fill('TEST updated review');await page.getByRole('button',{name:'Update Interaction',exact:true}).click();await page.getByRole('button',{name:'Save Interaction',exact:true}).waitFor();assert.equal((await repo.list('parents'))[0].data.purpose,'TEST updated review');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Archive interaction',exact:true}).click();await page.getByRole('button',{name:'Edit interaction',exact:true}).waitFor({state:'hidden'});
   await navigateModule('Homework');for(const [label,value]of [['Standard','8'],['Division','A'],['Subject','TEST Shared Homework']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel('Homework',{exact:true}).fill('TEST shared assignment');await page.getByLabel('Attachment',{exact:true}).setInputFiles({name:'TEST-homework.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 TEST attachment')});await page.getByText('TEST-homework.pdf',{exact:true}).waitFor();await page.getByRole('button',{name:'Save Homework',exact:true}).click();await page.getByRole('link',{name:'TEST-homework.pdf',exact:true}).waitFor();const homework=(await repo.list('homework')).find(r=>r.data.kind==='homework');assert.ok(homework.data.attachment.id.startsWith('schools/gbs-school/class_files/8:A/'));
   await assertFails(getMetadata(storageRef(env.authenticatedContext('other-admin').storage('gs://demo-gbs-school.appspot.com'),homework.data.attachment.id)));await assertSucceeds(getMetadata(storageRef(env.authenticatedContext('role-READ_ONLY').storage('gs://demo-gbs-school.appspot.com'),homework.data.attachment.id)));await assertFails(uploadBytes(storageRef(env.authenticatedContext('role-READ_ONLY').storage('gs://demo-gbs-school.appspot.com'),'schools/gbs-school/class_files/8:A/forbidden'),new Uint8Array([1]),{contentType:'application/pdf'}));
   await page.locator('.portal-nav-group').filter({has:page.locator('[data-nav="Backup"]')}).first().locator('.portal-group-trigger').click();await page.locator('[data-nav="Backup"]').first().click();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download school database export',exact:true}).click();const exported=await downloadEvent;const backup=JSON.parse(await readFile(await exported.path(),'utf8'));assert.equal(backup.schoolId,'gbs-school');assert.ok(backup.data.audit_logs.length>0);
   backup.data.students.push({id:'TEST-RESTORED',class_id:'8:A',data:{...data,id:'TEST-RESTORED',grNo:'TEST-RESTORED'}});backup.data.attendance.push({id:'TEST-RESTORED-ATTENDANCE',class_id:'8:A',data:{studentId:'TEST-RESTORED',date:'2026-09-24',academicYear:'2026-27',status:'Present'}});
   await page.getByLabel('Preview school database restore',{exact:true}).setInputFiles({name:'test-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.getByRole('heading',{name:'Restore preview',exact:true}).waitFor();await page.getByLabel('Restore missing records only; keep all existing values.',{exact:true}).check();await page.getByRole('button',{name:'Confirm school database restore',exact:true}).click();await page.getByText('Missing operational records restored atomically.',{exact:false}).waitFor();assert.equal((await repo.read('attendance','TEST-RESTORED-ATTENDANCE')).data.studentId,'TEST-RESTORED');assert.equal((await repo.read('students','TEST-STUDENT')).data.status,'TC/LC Issued');
   await navigateModule('Checkout');await page.getByLabel('Permission student',{exact:true}).selectOption('TEST-RESTORED');await page.getByLabel('outTime',{exact:true}).fill('08:00');await page.getByLabel('reason',{exact:true}).fill('TEST early leave');await page.getByLabel('permissionBy',{exact:true}).fill('TEST Headmaster');await page.getByRole('button',{name:'Review permission',exact:true}).click();await page.getByRole('button',{name:'Confirm permission',exact:true}).click();try{await page.getByText('Permission recorded; configured messages',{exact:false}).waitFor();}catch(error){console.log('Permission form status:',await page.locator('main').innerText());throw error;}assert.equal((await repo.list('parents')).filter(r=>r.data.kind==='permission').length,1);
   await page.getByLabel('Student',{exact:true}).selectOption('TEST-RESTORED');await page.getByLabel('time',{exact:true}).fill('08:10');await page.getByLabel("I confirm this individual student's checkout was observed.",{exact:true}).check();await page.getByRole('button',{name:'Save Confirmed Checkout',exact:true}).click();await page.getByRole('button',{name:'Prepare checkout message',exact:true}).waitFor();assert.equal((await repo.list('parents')).filter(r=>r.data.kind==='student_checkout').length,1);
   const staffAccount=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=emulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'test-school-user@example.invalid',password,returnSecureToken:true})}).then(r=>r.json());await navigateModule('AccessSetup');await page.getByLabel('User name',{exact:true}).fill('TEST Staff User');await page.getByLabel('User email',{exact:true}).fill(staffAccount.email);await page.getByLabel('Assigned classes (Class:Division, comma separated)',{exact:true}).pressSequentially('8:A, 9:B');await page.getByRole('button',{name:'Save school user',exact:true}).click();await page.getByText('School access saved.',{exact:false}).waitFor();assert.equal((await getDoc(doc(admin,'schools/gbs-school/members/'+staffAccount.localId))).data().role,'TEACHER');assert.deepEqual((await getDoc(doc(admin,'schools/gbs-school/members/'+staffAccount.localId))).data().classIds,['8:A','9:B']);assert.equal((await call({action:'school-users',udise:'27190113523'},staffAccount.idToken)).status,403);assert.equal((await call({action:'school-save-user',udise:'11111111111',user:{}},auth.idToken)).status,403);await page.getByRole('button',{name:'Send password setup email',exact:true}).click();await page.getByText('Password setup/reset email requested.',{exact:false}).waitFor();
   await env.withSecurityRulesDisabled(ctx=>setDoc(doc(ctx.firestore(),'schools/other-school/members/'+staffAccount.localId),{role:'TEACHER',active:true,passwordSetupComplete:true,modules:['Students'],resources:['students'],classIds:['8:A'],studentIds:[]}));await page.getByLabel('School access active',{exact:true}).uncheck();await page.getByRole('button',{name:'Save school user',exact:true}).click();await page.getByText('School access saved.',{exact:false}).waitFor();assert.equal((await call({action:'session',udise:'27190113523'},staffAccount.idToken)).status,403);assert.equal((await call({action:'session',udise:'11111111111'},staffAccount.idToken)).status,200);
   await page.reload();try{await page.locator('.portal-shell').waitFor({timeout:10000});}catch(error){console.log('Reload state:',await page.locator('body').innerText());console.log('Selected school:',await page.evaluate(()=>sessionStorage.getItem('perfectedu_selected_udise')));throw error;}
   await page.goto('http://127.0.0.1:5298/platform-admin/login');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();assert.equal(new URL(page.url()).pathname,'/platform-admin');
   await page.getByRole('button',{name:'Users',exact:true}).click();await page.getByLabel('Existing account email',{exact:true}).fill(support.email);await page.getByLabel('Platform role',{exact:true}).selectOption('PLATFORM_SUPPORT');await page.getByRole('button',{name:'Save platform access',exact:true}).click();await page.getByText('Platform role saved.',{exact:false}).waitFor();
   await page.getByRole('button',{name:'Add New School',exact:true}).click();
   for(const [label,value] of [['School Name','TEST Browser School'],['UDISE Code','11111111114'],['Unique School Code','browser-school'],['Permanent Tenant ID','browser-school'],['Academic Year','2026-27']])await page.getByLabel(label,{exact:true}).fill(value);
   await page.getByRole('button',{name:'Save School',exact:true}).click();await page.getByRole('cell',{name:'TEST Browser School',exact:true}).waitFor();
   await page.reload();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();await page.getByRole('button',{name:'Schools',exact:true}).click();await page.getByRole('cell',{name:'TEST Browser School',exact:true}).waitFor();
   const schoolRow=page.getByRole('row').filter({has:page.getByRole('cell',{name:'TEST Browser School',exact:true})});await schoolRow.getByRole('button',{name:'Open School',exact:true}).click();await page.getByRole('heading',{name:'School inspection',exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:'School inspection',exact:true}).waitFor();assert.match(await page.locator('.platform-context').innerText(),/browser-school/);
   await page.getByRole('button',{name:'Back to Platform Admin',exact:true}).click();
   await page.getByRole('button',{name:'Logout',exact:true}).click();await page.getByRole('heading',{name:'Super Admin Login'}).waitFor();
   await page.getByLabel('Email',{exact:true}).fill(schoolUsers[0].email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Platform Login',exact:true}).click();await page.getByText('Platform administrator permission required.',{exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);assert.equal(new URL(page.url()).pathname,'/platform-admin/login');assert.equal(await page.getByLabel('School UDISE Code',{exact:true}).count(),0);
   await page.getByLabel('Email',{exact:true}).fill(auth.email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Platform Login',exact:true}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();assert.equal(new URL(page.url()).pathname,'/platform-admin');
   await page.getByRole('button',{name:'Logout',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(support.email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Platform Login',exact:true}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Add New School',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Users',exact:true}).count(),0);await page.getByRole('button',{name:'Schools',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Manage Admins',exact:true}).count(),0);
  }finally{if(browser)await browser.close();server.kill();}
  await env.withSecurityRulesDisabled(ctx=>updateDoc(doc(ctx.firestore(),'schools/gbs-school'),{status:'SUSPENDED'}));
  await assertFails(getDoc(doc(admin,'schools/gbs-school/students/TEST-STUDENT')));
  assert.equal((await call({action:'school',udise:'27190113523'})).status,403);
 }finally{await env.cleanup();}
});
