const escapeHtml=value=>String(value??" ").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[c]));
let D={students:[],attendance:[],homework:[],results:[],fees:[],health:[],distribution:[],library:[],committees:[],transport:[],mdm:[],users:[],teachers:[],photos:[],audit:[]};
const $=id=>document.getElementById(id), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7), today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const unreadableStorage=new Set();
function readLegacy(k,fallback){try{const raw=localStorage.getItem('v32_'+k);if(raw===null)return fallback;const value=JSON.parse(raw);if(Array.isArray(fallback)?!Array.isArray(value):!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid data');return value}catch{if(!unreadableStorage.has(k)){unreadableStorage.add(k);queueMicrotask(()=>alert('जुना '+k+' डेटा वाचता येत नाही. डेटा बदललेला नाही. Backup तपासा.'))}return fallback}}
function writeLegacy(k,value){if(unreadableStorage.has(k))throw Error('Saved data cannot be read');localStorage.setItem('v32_'+k,JSON.stringify(value))}
const get=k=>readLegacy(k,[]),set=writeLegacy,getO=k=>readLegacy(k,{}),setO=writeLegacy;
function show(id,b){document.querySelectorAll('.page').forEach(p=>p.classList.remove('show'));$(id).classList.add('show');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAll()}
window.onload=()=>{if(location.hash.startsWith('#verify-student='))return;['attDate','mdmDate'].forEach(i=>{$(i)&&($(i).value=today())});loadAll();loadSettings();seedTemplates(false)}
function loadAll(){Object.keys(D).forEach(k=>D[k]=get(k));renderAll()}
function renderAll(){studentCount&&(studentCount.innerText=D.students.length);attToday&&(attToday.innerText=D.attendance.filter(a=>a.date==today()).length);feeDue&&(feeDue.innerText=D.fees.reduce((s,f)=>s+(+f.balance||0),0));refreshSelects();renderStudents();renderAttendanceTable();['users','teachers','photos','homework','results','fees','health','distribution','library','committees','transport','mdm','audit'].forEach(renderTable)}
function refreshSelects(){let opts=D.students.map(s=>`<option value="${escapeHtml(s.id)}">${escapeHtml(s.roll)}. ${escapeHtml(s.name)} - ${escapeHtml(s.className)}</option>`).join('');['certStudent','resStudent','feeStudent','healthStudent','distStudent','bookStudent','photoStudent'].forEach(i=>{if($(i)){const old=$(i).value;$(i).innerHTML=opts;if([...$(i).options].some(o=>o.value===old))$(i).value=old}}); if(window.templateKey){let t=getO('templates'); const selected=templateKey.value; templateKey.innerHTML=Object.keys(t).map(k=>`<option value="${escapeHtml(k)}">${escapeHtml(k)}</option>`).join('');if(Object.hasOwn(t,selected))templateKey.value=selected}}
function studentBy(id){return D.students.find(x=>x.id==id)||{}}
function loadSampleStudents(){const existing=new Set(D.students.map(s=>s.admissionNo||[s.name,s.className,s.roll].join('|')));const additions=(window.SEED_STUDENTS||[]).filter(s=>!existing.has(s.admissionNo||[s.name,s.className,s.roll].join('|'))).map(s=>({...s,id:s.id||uid()}));D.students=[...D.students,...additions];set('students',D.students);renderAll();alert('मागची 34 विद्यार्थ्यांची यादी Import झाली')}
function seedTemplates(showAlert=true){if(!Object.keys(getO('templates')).length)setO('templates',window.DEFAULT_TEMPLATES||{});refreshSelects();if(showAlert)alert('Templates Import झाले')}
function fill(t,o){return (t||'').replace(/\{(\w+)\}/g,(m,k)=>o[k]??m)}
function saveStudent(){if(!sName.value.trim()||!sAdmission.value.trim()){alert('नाव आणि प्रवेश क्रमांक भरा');return}if(D.students.some(s=>s.admissionNo===sAdmission.value.trim())){alert('प्रवेश क्रमांक आधीच नोंदवलेला आहे');return}if(sParent.value&&!/^(?:\+?91)?\d{10}$/.test(sParent.value)){alert('मोबाईल नंबर चुकीचा आहे');return}D.students.push({id:uid(),admissionNo:sAdmission.value,name:sName.value,mother:sMother.value,className:sClass.value,roll:sRoll.value,religion:sReligion.value,caste:sCaste.value,dob:sDob.value,admissionDate:sAdmissionDate.value,parent:sParent.value});set('students',D.students);renderAll()}
function renderStudents(){if(!window.studentTable)return;studentTable.innerHTML='<tr><th>रोल</th><th>प्रवेश</th><th>नाव</th><th>आई</th><th>धर्म</th><th>जात</th><th>DOB</th><th>Mobile</th></tr>'+D.students.map(s=>`<tr><td>${escapeHtml(s.roll||'')}</td><td>${escapeHtml(s.admissionNo||'')}</td><td>${escapeHtml(s.name||'')}</td><td>${escapeHtml(s.mother||'')}</td><td>${escapeHtml(s.religion||'')}</td><td>${escapeHtml(s.caste||'')}</td><td>${escapeHtml(s.dob||'')}</td><td>${escapeHtml(s.parent||'')}</td></tr>`).join('')}
function loadAttendance(){attList.dataset.className=attClass.value;attList.dataset.date=attDate.value;attList.innerHTML=D.students.filter(s=>s.className==attClass.value).map(s=>`<div class='row' data-id='${escapeHtml(s.id)}' data-status='${escapeHtml((D.attendance.find(a=>a.date===attDate.value&&a.className===s.className&&(a.studentId?a.studentId===s.id:a.name===s.name&&a.roll===s.roll))||{}).status||'P')}'><b>${escapeHtml(s.roll)}</b><b>${escapeHtml(s.name)}<br><small>${escapeHtml(s.mother||'')}</small></b><button class='ok' onclick="mark(this,'P')">P</button><button class='bad' onclick="mark(this,'A')">A</button><button class='half' onclick="mark(this,'H')">H</button><button class='late' onclick="mark(this,'L')">L</button><span class='st'>${escapeHtml((D.attendance.find(a=>a.date===attDate.value&&a.className===s.className&&(a.studentId?a.studentId===s.id:a.name===s.name&&a.roll===s.roll))||{}).status||'P')}</span></div>`).join('')}
function mark(btn,st){let r=btn.closest('.row');r.dataset.status=st;r.querySelector('.st').innerText=st;let s=studentBy(r.dataset.id), t=getO('templates')['attendance_'+st]||'{STUDENT} {STATUS}';let msg=fill(t,{STUDENT:s.name,DATE:attDate.value,CLASS:s.className,STATUS:st});msgUrls.value=(msgUrls.value?msgUrls.value+'\n':'')+buildWhatsUrl(s.parent,msg)+'\n'+buildApiUrl(s.parent,msg)}
function saveAttendance(){let date=attDate.value;if(!date||attList.dataset.className!==attClass.value||attList.dataset.date!==date||!attList.querySelector('.row')){alert('निवडलेल्या दिनांक व वर्गाची यादी आधी दाखवा');return}D.attendance=D.attendance.filter(a=>!(a.date==date&&a.className==attClass.value));document.querySelectorAll('#attList .row').forEach(r=>{let s=studentBy(r.dataset.id);D.attendance.push({studentId:s.id,date,className:attClass.value,roll:s.roll,name:s.name,mother:s.mother,mobile:s.parent,status:r.dataset.status})});set('attendance',D.attendance);renderAll();alert('Attendance Save झाली')}
function buildWhatsUrl(mobile,msg){return `https://wa.me/${mobile||'917507514475'}?text=${encodeURIComponent(msg)}`}
function buildApiUrl(mobile,msg){let w=getO('wa');return `${(w.url||'https://whatsbot.tech/api').replace(/\/$/,'')}/send_sms?api_token=${encodeURIComponent(w.token||'')}&mobile=${encodeURIComponent(mobile||w.mobile||'917507514475')}&message=${encodeURIComponent(msg)}&device_id=${encodeURIComponent(w.device||'')}`}
function generateAttendanceUrls(){let t=getO('templates');msgUrls.value=D.attendance.filter(a=>a.date==attDate.value&&a.className==attClass.value).map(a=>{let msg=fill(t['attendance_'+a.status]||'{STUDENT} attendance {STATUS}',{STUDENT:a.name,DATE:a.date,STATUS:a.status,CLASS:a.className});return buildWhatsUrl(a.mobile,msg)+'\n'+buildApiUrl(a.mobile,msg)}).join('\n')}
function renderAttendanceTable(){if(!window.attendanceTable)return;attendanceTable.innerHTML='<tr><th>Date</th><th>Class</th><th>Roll</th><th>Name</th><th>Status</th><th>Mobile</th></tr>'+D.attendance.slice(-150).map(a=>`<tr><td>${escapeHtml(a.date)}</td><td>${escapeHtml(a.className)}</td><td>${escapeHtml(a.roll)}</td><td>${escapeHtml(a.name)}</td><td>${escapeHtml(a.status)}</td><td>${escapeHtml(a.mobile)}</td></tr>`).join('')}
function saveHomework(){if(!hwSubject.value.trim()||(!hwHomework.value.trim()&&!hwClasswork.value.trim())){alert('विषय आणि गृहपाठ / वर्गपाठ भरा');return}D.homework.push({className:hwClass.value,subject:hwSubject.value,classwork:hwClasswork.value,homework:hwHomework.value,date:today()});set('homework',D.homework);renderAll()}
function homeworkUrls(){let t=getO('templates').homework;hwOut.value=D.students.filter(s=>s.className==hwClass.value).map(s=>buildWhatsUrl(s.parent,fill(t,{CLASS:hwClass.value,SUBJECT:hwSubject.value,CLASSWORK:hwClasswork.value,HOMEWORK:hwHomework.value}))).join('\n')}
function makeCertificate(){if(!studentBy(certStudent.value).id){alert('विद्यार्थी निवडा');return}let s=studentBy(certStudent.value),g=window.resolveLegacySchoolIdentity(getO('settings'));certBox.innerHTML=`<div class='printbox'><img src='assets/school-logo.jpg' alt='School logo' style='width:72px;height:78px;object-fit:contain'><p style='white-space:pre-line'>${escapeHtml(g.sansthaName)}</p><h2>${escapeHtml(g.school||schoolTitle.innerText)}</h2><h3>${certType.value}</h3><table><tr><th>विद्यार्थी</th><td>${escapeHtml(s.name||'')}</td></tr><tr><th>आईचे नाव</th><td>${escapeHtml(s.mother||'')}</td></tr><tr><th>वर्ग</th><td>${escapeHtml(s.className||'')}</td></tr><tr><th>जन्म दिनांक</th><td>${escapeHtml(s.dob||'')}</td></tr><tr><th>कारण</th><td>${certReason.value}</td></tr></table><p style='text-align:right;margin-top:45px'>${escapeHtml(g.principal||'मुख्याध्यापक')} सही</p></div>`}
function parseMarks(txt){return txt.split(',').map(x=>{let [sub,m]=x.split(':'),[ob,max]=(m||'0/100').split('/');return{sub:(sub||'').trim(),ob:+ob||0,max:+max||100}}).filter(x=>x.sub)}
function saveResult(){if(!resExam.value.trim()||!resMarks.value.trim()||!resMarks.value.split(',').every(x=>{const m=x.trim().match(/^([^:]+):\s*(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)$/);return m&&+m[3]>0&&+m[2]<=+m[3]})){alert('परीक्षा आणि योग्य गुण भरा: गणित:75/100');return}if(!studentBy(resStudent.value).id){alert('विद्यार्थी निवडा');return}let s=studentBy(resStudent.value),ms=parseMarks(resMarks.value),total=ms.reduce((a,b)=>a+b.ob,0),max=ms.reduce((a,b)=>a+b.max,0),pct=max?Math.round(total*100/max):0;D.results.push({student:s.name,mobile:s.parent,exam:resExam.value,marks:resMarks.value,total,max,percentage:pct,grade:pct>=75?'A':pct>=60?'B':pct>=45?'C':'D',attendance:resAttendance.value});set('results',D.results);renderAll()}
function makeResultCard(){if(!D.results.length){alert('आधी निकाल Save करा');return}let r=D.results[D.results.length-1]||{};resultCard.innerHTML=`<div class='printbox'><h2>निकालपत्र</h2><p>${escapeHtml(r.student)} - ${escapeHtml(r.exam)}</p><p>${escapeHtml(r.marks)}</p><p>${escapeHtml(r.total)}/${escapeHtml(r.max)} | ${escapeHtml(r.percentage)}% | Grade ${escapeHtml(r.grade)}</p></div>`}
function saveFee(){const amounts=['feeAdmission','feeTuition','feeExam','feeComputer','feeLibrary','feeTransport','feeOther'].map(id=>Number($(id).value||0));const payment=Number(feePaid.value||0);if(amounts.some(n=>!Number.isFinite(n)||n<0)||!Number.isFinite(payment)||payment<0||payment>amounts.reduce((a,b)=>a+b,0)){alert('फी आणि भरलेली रक्कम तपासा');return}if(!studentBy(feeStudent.value).id){alert('विद्यार्थी निवडा');return}let s=studentBy(feeStudent.value),total=['feeAdmission','feeTuition','feeExam','feeComputer','feeLibrary','feeTransport','feeOther'].reduce((a,i)=>a+(+$(i).value||0),0),paid=+feePaid.value||0;D.fees.push({student:s.name,mobile:s.parent,total,paid,balance:total-paid,remark:feeRemark.value});set('fees',D.fees);renderAll()}
function makeReceipt(){if(!D.fees.length){alert('आधी फी Save करा');return}let f=D.fees[D.fees.length-1]||{};receiptBox.innerHTML=`<div class='printbox'><h2>Fee Receipt</h2><p>${escapeHtml(f.student)}</p><p>Total ${escapeHtml(f.total)}, Paid ${escapeHtml(f.paid)}, Balance ${escapeHtml(f.balance)}</p></div>`}
function feeReminder(){let t=getO('templates').fees;feeOut.value=D.fees.filter(f=>f.balance>0).map(f=>buildWhatsUrl(f.mobile,fill(t,{STUDENT:f.student,BALANCE:f.balance}))).join('\n')}
function saveHealth(){if(!studentBy(healthStudent.value).id){alert('विद्यार्थी निवडा');return}let s=studentBy(healthStudent.value);D.health.push({student:s.name,height:heightVal.value,weight:weightVal.value,blood:bloodVal.value,hb:hbVal.value,vision:visionVal.value,remark:healthRemark.value});set('health',D.health);renderAll()}
function saveDist(){if(!/^\d+$/.test(distQty.value)||+distQty.value<1){alert('वाटप संख्या तपासा');return}if(!studentBy(distStudent.value).id){alert('विद्यार्थी निवडा');return}let s=studentBy(distStudent.value);D.distribution.push({student:s.name,item:distItem.value,qty:distQty.value,details:distDetails.value});set('distribution',D.distribution);renderAll()}
function saveGeneric(k,ids){const required={users:['uName','uMobile','uPass'],teachers:['tName','tMobile','tSubject'],committees:['memberName'],transport:['busNo','routeName','driverName'],mdm:['mdmDate','mdmCount','mdmMenu']}[k]||[];if(required.some(id=>!$(id).value.trim())){alert('आवश्यक माहिती भरा');return}const mobile=ids.find(id=>/Mobile$/.test(id));if(mobile&&$(mobile).value&&!/^(?:\+?91)?\d{10}$/.test($(mobile).value)){alert('मोबाईल नंबर चुकीचा आहे');return}if(k==='mdm'&&(!/^\d+$/.test(mdmCount.value)||+mdmCount.value<0)){alert('लाभार्थी संख्या तपासा');return}D[k].push(Object.fromEntries(ids.map(i=>[i,$(i).value])));set(k,D[k]);renderAll()}
function saveGenericStudent(k,sel,ids){if(!$(ids[0]).value.trim()){alert('आवश्यक माहिती भरा');return}if(!studentBy($(sel).value).id){alert('विद्यार्थी निवडा');return}let s=studentBy($(sel).value);D[k].push({student:s.name,...Object.fromEntries(ids.map(i=>[i,$(i).value]))});set(k,D[k]);renderAll()}
function renderTable(k){let el=$(k+'Table');if(!el)return;let rows=D[k]||[];el.innerHTML='<tr>'+(rows[0]?Object.keys(rows[0]).map(h=>`<th>${escapeHtml(h)}</th>`).join(''):'')+'</tr>'+rows.map(r=>'<tr>'+Object.entries(r).map(([key,value])=>{const v=key==='uPass'?'••••••':value;return `<td>${escapeHtml(v??'')}</td>`}).join('')+'</tr>').join('')}
function loadTemplateToBox(){templateText.value=(getO('templates')[templateKey.value]||'')}
function saveTemplate(){let t=getO('templates');t[templateKey.value]=templateText.value;setO('templates',t);alert('Template Save झाले')}
function saveWA(){setO('wa',{url:waUrl.value,token:waToken.value,device:waDevice.value,mobile:waMobile.value,smsTemplate:smsTemplate.value});alert('API Save झाला')}
function testWA(){let w=getO('wa'),msg=waMessage.value||'ERP Test';waOut.value=buildWhatsUrl(waMobile.value||w.mobile,msg)+'\n'+buildApiUrl(waMobile.value||w.mobile,msg)}
function openTestWA(){testWA();window.open(waOut.value.split('\n')[0],'_blank')}
function saveFirebase(){setO('firebase',{config:firebaseConfig.value});alert('Firebase Config Save झाले')}
function saveSettings(){let g={school:setSchool.value,address:setAddress.value,year:setYear.value,principal:setPrincipal.value,chairman:setChairman.value,secretary:setSecretary.value,mobile:setMobile.value,logo:setLogo.value};setO('settings',g);loadSettings();alert('Settings Save झाले')}
function loadSettings(){let g=window.resolveLegacySchoolIdentity(getO('settings'));for(const [key,id] of Object.entries({school:'setSchool',address:'setAddress',year:'setYear',principal:'setPrincipal',chairman:'setChairman',secretary:'setSecretary',mobile:'setMobile',logo:'setLogo'})){if($(id))$(id).value=g[key]||''}if(g.school)schoolTitle.innerText=g.school;if(g.address)schoolAddressTitle.innerText=g.address;if(g.year)academicYear.innerText=g.year;if(g.logo)document.querySelector('.logoText').style.background=`#fff url('${g.logo}') center/contain no-repeat`;let w=getO('wa');if(window.waUrl){waUrl.value=w.url||'https://whatsbot.tech/api';waToken.value=w.token||'';waDevice.value=w.device||'';waMobile.value=w.mobile||'917507514475';smsTemplate.value=w.smsTemplate||''}}
function showReport(){let rows=D[reportType.value]||[];reportBox.innerHTML='<table><tr>'+(rows[0]?Object.keys(rows[0]).map(h=>`<th>${escapeHtml(h)}</th>`).join(''):'')+'</tr>'+rows.map(r=>'<tr>'+Object.values(r).map(v=>`<td>${escapeHtml(v??'')}</td>`).join('')+'</tr>').join('')+'</table>'}
function downloadReport(){if(!window.XLSX){alert('Excel library load झाली नाही. Internet तपासून पुन्हा प्रयत्न करा.');return}let rows=D[reportType.value]||[];let ws=XLSX.utils.json_to_sheet(rows);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');XLSX.writeFile(wb,reportType.value+'.xlsx')}
function backupData(){let b=new Blob([JSON.stringify({D,settings:getO('settings'),wa:getO('wa'),templates:getO('templates'),firebase:getO('firebase')},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='school_erp_v32_backup.json';a.click()}
async function restoreData(){const f=restoreFile.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data.D||typeof data.D!=='object'||Array.isArray(data.D))throw Error('Invalid backup');for(const [k,v] of Object.entries(data.D)){if(!Object.hasOwn(D,k)||!Array.isArray(v))throw Error('Invalid records')}for(const k of ['settings','wa','templates','firebase']){if(data[k]&&(typeof data[k]!=='object'||Array.isArray(data[k])))throw Error('Invalid settings')}if(!confirm('Backup मधील माहितीने सध्याची माहिती बदलणार आहे. पुढे जायचे का?'))return;const entries=[...Object.entries(data.D),...['settings','wa','templates','firebase'].filter(k=>data[k]).map(k=>[k,data[k]])];const previous=entries.map(([k])=>[k,localStorage.getItem('v32_'+k)]);try{entries.forEach(([k,v])=>localStorage.setItem('v32_'+k,JSON.stringify(v)))}catch(error){previous.forEach(([k,v])=>v===null?localStorage.removeItem('v32_'+k):localStorage.setItem('v32_'+k,v));throw error}loadAll();loadSettings();alert('Restore झाले')}catch{alert('Restore झाले नाही. Backup file किंवा browser storage तपासा.')}}

// Keep the in-memory lists unchanged if the browser refuses a save.
for(const name of ['saveStudent','loadSampleStudents','seedTemplates','saveAttendance','saveHomework','saveResult','saveFee','saveHealth','saveDist','saveGeneric','saveGenericStudent','saveTemplate','saveWA','saveFirebase','saveSettings']){const action=window[name];window[name]=function(...args){const previous=structuredClone(D);try{return action(...args)}catch{D=previous;renderAll();alert('Save झाले नाही. Browser storage किंवा जुना डेटा तपासा.')}}}
