import fs from 'node:fs';
const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('src/pages/StudentLifecycle.jsx',s=>s.replace("'Class Transfer','School Left'","'Class Transfer','Set Initial Academic Year','School Left'"));
edit('src/pages/LongAbsence.jsx',s=>"import {prepareLongAbsenceAlerts} from '../services/longAbsenceStore';\n"+s.replace('[alerts,saveAlerts]','[alerts,,reloadAlerts]').replace(/ const prepare=\(\)=>\{.*?\};\n/," const prepare=()=>{try{prepareLongAbsenceAlerts(date);reloadAlerts();notify('Local alerts prepared. No provider sending performed.')}catch(e){notify(e.message)}};\n"));
edit('src/pages/StudentImport.jsx',s=>"import {enrollment,academicSnapshot} from '../services/studentLifecycle';\n"+s.replace('erp_pro_students: change.students,',`erp_pro_students: change.students,
        erp_pro_student_movements:[...readStored('erp_pro_student_movements',[]),...change.students.flatMap(s=>{const old=review.existing.find(p=>p.id===s.id);if(old&&JSON.stringify(enrollment(old))===JSON.stringify(enrollment(s)))return [];return [{id:crypto.randomUUID(),studentId:s.id,studentName:s.name,grNo:s.grNo,action:old?'Class Changed (reviewed Excel update)':'Added',type:old?'Class Changed':'Added',oldValue:old?enrollment(old):null,newValue:enrollment(s),reason:'Reviewed Excel import '+file.name,actor:'local-review',createdAt:timestamp}]})],
        erp_pro_academic_history:[...readStored('erp_pro_academic_history',[]),...review.existing.flatMap(old=>{const s=change.students.find(p=>p.id===old.id);return s&&JSON.stringify(enrollment(old))!==JSON.stringify(enrollment(s))?[{id:crypto.randomUUID(),...academicSnapshot(old,readStored('erp_pro_results',[]),readStored('erp_pro_attendance',{}),'Reviewed Excel update',timestamp.slice(0,10))}]:[]})],`));
edit('src/components/AbsenceCommunication.jsx',s=>"import {lifecycleActive} from '../services/studentLifecycle';\n"+s.replace('!allowed || !master ||','!allowed || !master || !lifecycleActive(master) ||'));
edit('src/pages/Attendance.jsx',s=>s.replace('const updateStatus = (id, status) => {','const updateStatus = (id, status) => {\n    if(!readStored("erp_pro_students",[]).some(s=>s.id===id&&isActiveStudent(s)))return notify("Student is no longer enrolled. Reopen Attendance.");'));
edit('src/services/absenceCommunication.js',s=>s.replace('status: channel === "call" ? "Dialer requested" : "Composer requested", remark: "",','status: extra.status || (channel === "call" ? "Dialer requested" : "Composer requested"), remark: extra.remark || "",'));
// History tables retain departed students as names, not orphan-looking IDs.
for(const file of ['src/pages/Fees.jsx','src/pages/Results.jsx'])edit(file,s=>s.replace('readStored("erp_pro_students", []).filter(s => !s.archivedAt)','readStored("erp_pro_students", [])').replace("readStored('erp_pro_students',[]).filter(s=>!s.archivedAt)","readStored('erp_pro_students',[])"));
