import {saveSharedMessageJobs} from '../services/sharedMessageQueue';
import {sharedOperationalEnabled} from '../backend/sharedReadCache';
import {schoolFirebase} from '../backend/firebaseClient';
import {createFirebaseRepository} from '../backend/firebaseRepository';
import {useSharedRecords} from '../backend/useSharedRecords';
import {schoolStorage} from '../backend/demoClient';
import {useContext,useState} from 'react';
import {CommunicationSession} from '../backend/CommunicationSession';
import {readStored,useStoredState,localDate,commitStoredBatch} from '../storage';
import {automationKey,automationTemplates,mergedAutomation,validateAutomation,classKey,messageFor,planMessages,retryDryRun} from '../services/attendanceAutomation';
import {prepareAutomationDue} from '../services/attendanceAutomationStore';
import {parentContacts} from '../services/absenceCommunication';
import './AutomationControls.css';

export default function AutomationControls(){
 const session=useContext(CommunicationSession),admin=['Super Admin','Admin'].includes(session?.role);
 const [stored,save]=useStoredState(automationKey,{}),[form,setForm]=useState(()=>mergedAutomation(stored)),[notice,setNotice]=useState(''),[type,setType]=useState('Absent'),[selected,setSelected]=useState(''),[fields,setFields]=useState({date:localDate()}),[preview,setPreview]=useState(''),[copyName,setCopyName]=useState(''),[jobs,setJobs]=useState(()=>readStored('erp_pro_message_jobs',[])),[overrideDate,setOverrideDate]=useState(''),[holidayDate,setHolidayDate]=useState('');
 const [students,setStudents,,reloadStudents]=useSharedRecords('students','erp_pro_students');
 const groups=[...new Set(students.map(s=>classKey(s.academicYear,s.className,s.division)))];
 const types=[...new Set([...Object.keys(automationTemplates),...Object.keys(form.templates)])],template=form.templates[type]||{},pair=automationTemplates[type]||['',''];
 const setTemplate=next=>setForm({...form,templates:{...form.templates,[type]:{...template,...next,updatedAt:new Date().toISOString()}}});
 const act=async fn=>{try{await fn()}catch(e){setNotice(e.message)}};
 const saveSettings=()=>act(async()=>{if(!admin)throw Error('Admin required.');validateAutomation(form);if(sharedOperationalEnabled){const repo=createFirebaseRepository(schoolFirebase());await repo.membership();const {__version,id:_id,...data}=form;const saved=await repo.mutate({collection:'settings',id:'attendance-automation',classId:'',expectedVersion:__version||0,data:{...data,dryRun:true},mutationId:crypto.randomUUID()});setForm({...form,__version:saved.version});setNotice('School timings and templates saved to Firestore. Live delivery is not enabled.');}else if(save({...form,dryRun:true}))setNotice('Settings saved. Dry Run ON. No messages sent.');});
 const student=students.find(s=>String(s.id)===selected);
 const renderFields={school_name:readStored('schoolSettings',{}).schoolName,student_name:student?.name,class:student?.className,division:student?.division||'-',...fields};
 const requiredFields=[...new Set(((template.en??pair[0])+' '+(template.mr??pair[1])).match(/\{[a-z_]+\}/g)||[])].map(s=>s.slice(1,-1)).filter(k=>!['school_name','student_name','class','division'].includes(k));
 const timing=(name,value,update)=><fieldset><legend>{name}</legend><div className="form-grid">{['start','end','attendanceCutoff','lateCutoff'].map(key=><label key={key}>{key}<input aria-label={`${name} ${key}`} type="time" value={value[key]||''} onChange={e=>update({...value,[key]:e.target.value})}/></label>)}</div></fieldset>;
 const updateStudent=async(id,key,value)=>{if(!admin)return; if(await setStudents(students.map(s=>s.id===id?{...s,[key]:value}:s)))setNotice('Student notification preference saved.');};
 return <div className="automation-controls"><section className="school-panel workflow-panel"><h2>Attendance Automation / उपस्थिती सूचना</h2><strong>DRY RUN ON — LIVE MESSAGING OFF</strong><p>Messages below are previews only. {sharedOperationalEnabled?"Attendance, settings and queue records are shared through your school database. Background delivery requires an approved provider.":"This development preview uses local records. Background delivery is not enabled."}</p><button disabled>Enable live messaging — backend setup required</button><p role="status">{notice}</p></section>
 <fieldset disabled={!admin}><section className="school-panel workflow-panel"><h3>School Timing / शाळेची वेळ</h3>{timing('Monday–Friday',form.weekdays,value=>setForm({...form,weekdays:value}))}{timing('Saturday',form.saturday,value=>setForm({...form,saturday:value}))}<h4>Weekly holidays</h4><div className="check-grid">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((name,index)=><label key={name}><input type="checkbox" checked={form.weeklyHolidays.includes(index)} onChange={e=>setForm({...form,weeklyHolidays:e.target.checked?[...form.weeklyHolidays,index]:form.weeklyHolidays.filter(v=>v!==index)})}/>{name}</label>)}</div>
 <h4>Special / exam timing overrides</h4><label>Override date<input type="date" value={overrideDate} onChange={e=>setOverrideDate(e.target.value)}/></label><button onClick={()=>overrideDate&&setForm({...form,overrides:{...form.overrides,[overrideDate]:{...form.weekdays,reason:'',kind:'Special'}}})}>Add timing override</button>{Object.entries(form.overrides).map(([date,value])=><div key={date}>{timing(date,value,next=>setForm({...form,overrides:{...form.overrides,[date]:next}}))}<label>Type<select value={value.kind||'Special'} onChange={e=>setForm({...form,overrides:{...form.overrides,[date]:{...value,kind:e.target.value}}})}><option>Special</option><option>Exam</option><option>Emergency</option></select></label><label>Reason<input value={value.reason||''} onChange={e=>setForm({...form,overrides:{...form.overrides,[date]:{...value,reason:e.target.value}}})}/></label><button onClick={()=>setForm({...form,overrides:Object.fromEntries(Object.entries(form.overrides).filter(([key])=>key!==date))})}>Remove override {date}</button></div>)}
 <h4>Dated holidays</h4><label>Holiday date<input type="date" value={holidayDate} onChange={e=>setHolidayDate(e.target.value)}/></label><button onClick={()=>holidayDate&&setForm({...form,holidays:{...form.holidays,[holidayDate]:{reason:'',reopenDate:''}}})}>Add holiday</button>{Object.entries(form.holidays).map(([date,value])=><div className="form-grid" key={date}><strong>{date}</strong>{['reason','reopenDate'].map(key=><label key={key}>{key}<input type={key==='reopenDate'?'date':'text'} value={value[key]} onChange={e=>setForm({...form,holidays:{...form.holidays,[date]:{...value,[key]:e.target.value}}})}/></label>)}<button onClick={()=>setForm({...form,holidays:Object.fromEntries(Object.entries(form.holidays).filter(([key])=>key!==date))})}>Remove holiday {date}</button></div>)}</section>
 <section className="school-panel workflow-panel"><h3>Enabled Classes — trial scope</h3><p>All classes start disabled. Select one class/division for the initial trial. Additional classes can be enabled here later.</p>{groups.map(key=><label key={key}><input type="checkbox" checked={form.enabledClasses.includes(key)} onChange={e=>setForm({...form,enabledClasses:e.target.checked?[...form.enabledClasses,key]:form.enabledClasses.filter(v=>v!==key)})}/>{JSON.parse(key).join(' / ')}</label>)}{!groups.length&&<p>No classes in Student Master.</p>}<label>Custom statuses (comma separated)<input value={form.customStatuses.join(',')} onChange={e=>setForm({...form,customStatuses:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><div className="form-grid">{['consecutiveDays','lowAttendancePercent','minimumMarkedDays','maxRetries'].map(key=><label key={key}>{key}<input type="number" value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/></label>)}<label>Staff daily summary time<input type="time" value={form.staffSummaryTime} onChange={e=>setForm({...form,staffSummaryTime:e.target.value})}/></label><label>Default language<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option value="mr">मराठी</option><option value="en">English</option><option value="both">Both</option></select></label></div></section>
 <section className="school-panel workflow-panel"><h3>Management notification recipients</h3><button onClick={()=>setForm({...form,managementRecipients:[...form.managementRecipients,{id:crypto.randomUUID(),name:'',designation:'Headmaster',mobile:'',whatsapp:'',email:'',enabled:false,absence:false,late:false,summary:false,channel:'sms',language:'mr'}]})}>Add authorized recipient</button>{form.managementRecipients.map(row=><fieldset key={row.id}><legend>{row.name||'New recipient'}</legend><div className="form-grid">{['name','designation','mobile','whatsapp','email'].map(key=><label key={key}>{key}<input value={row[key]} onChange={e=>setForm({...form,managementRecipients:form.managementRecipients.map(r=>r.id===row.id?{...r,[key]:e.target.value}:r)})}/></label>)}{['channel','language'].map(key=><label key={key}>{key}<select value={row[key]} onChange={e=>setForm({...form,managementRecipients:form.managementRecipients.map(r=>r.id===row.id?{...r,[key]:e.target.value}:r)})}>{(key==='channel'?['sms','whatsapp','both']:['mr','en','both']).map(v=><option key={v}>{v}</option>)}</select></label>)}</div>{['enabled','absence','late','summary'].map(key=><label key={key}><input type="checkbox" checked={!!row[key]} onChange={e=>setForm({...form,managementRecipients:form.managementRecipients.map(r=>r.id===row.id?{...r,[key]:e.target.checked}:r)})}/>{key}</label>)}</fieldset>)}</section>
 <section className="school-panel workflow-panel"><h3>Message Templates / संदेश नमुने</h3><label>Template name<select aria-label="Template name" value={type} onChange={e=>{setType(e.target.value);setPreview('')}}>{types.map(v=><option key={v}>{v}</option>)}</select></label><p>Trigger: {automationTemplates[type]?'Saved event / due schedule':'Manual custom notice'} · Recipients: {type.startsWith('Staff')?'Opted-in management':'Selected student’s configured parents'} · Last updated: {template.updatedAt||'Default'}</p><label><input type="checkbox" checked={form.enabledEvents.includes(type)} onChange={e=>setForm({...form,enabledEvents:e.target.checked?[...form.enabledEvents,type]:form.enabledEvents.filter(v=>v!==type)})}/>Enabled</label><label>Default channel<select value={template.channel||'sms'} onChange={e=>setTemplate({channel:e.target.value})}><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="both">Both</option></select></label><label>English template<textarea rows={5} value={template.en??pair[0]} onChange={e=>setTemplate({en:e.target.value})}/></label><label>Marathi template<textarea rows={5} value={template.mr??pair[1]} onChange={e=>setTemplate({mr:e.target.value})}/></label><label>Duplicate name<input value={copyName} onChange={e=>setCopyName(e.target.value)}/></label><button onClick={()=>act(()=>{const name=copyName.trim();if(!name||types.includes(name))throw Error('Choose a new unique template name.');setForm({...form,templates:{...form.templates,[name]:{en:template.en??pair[0],mr:template.mr??pair[1],channel:template.channel||'sms',updatedAt:new Date().toISOString()}}});setType(name);setCopyName('')})}>Duplicate template</button><button onClick={saveSettings}>Save Automation Settings</button></section></fieldset>
 <section className="school-panel workflow-panel"><h3>Preview / Test Send (dry run only)</h3><label>Student for preview<select aria-label="Student for preview" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.grNo} · {s.className}/{s.division}</option>)}</select></label><div className="form-grid">{requiredFields.map(key=><label key={key}>{key}<input value={fields[key]||''} onChange={e=>setFields({...fields,[key]:e.target.value})}/></label>)}</div><button onClick={()=>act(()=>setPreview(messageFor(type,renderFields,form,'both')))}>Preview Marathi + English</button><button disabled={!admin} onClick={()=>act(async()=>{const source=schoolStorage.getItem('erp_pro_message_jobs'),previous=readStored('erp_pro_message_jobs',[]),config=mergedAutomation(readStored(automationKey,{}));const next=planMessages([{type,studentId:student?.id,staff:type.startsWith('Staff'),key:`manual:${crypto.randomUUID()}`,fields}],students,readStored('schoolSettings',{}),config,previous,session.uid);if(next.length===previous.length)throw Error('No recipients: save and enable this template and the trial class, or opt in management recipients.');if(sharedOperationalEnabled)await saveSharedMessageJobs(next,readStored('erp_pro_message_jobs',[]));else commitStoredBatch({erp_pro_message_jobs:next},{erp_pro_message_jobs:source});setJobs(next);setNotice('Dry-run test logged. Nothing sent.');})}>Test Send — dry run</button><pre className="message-preview">{preview}</pre></section>
 <section className="school-panel workflow-panel"><h3>Student notification preferences</h3><button onClick={reloadStudents}>Refresh students</button>{student?<fieldset disabled={!admin}><strong>{student.name} · {student.grNo}</strong>{['primaryNotificationContact','secondaryNotificationContact'].map(key=><label key={key}>{key}<select value={student[key]||''} onChange={e=>updateStudent(student.id,key,e.target.value)}><option value="">{key.startsWith('primary')?'First available':'None'}</option>{parentContacts(student).map(c=><option key={c.id} value={c.id}>{c.label} — {c.mobile||'Invalid number'}</option>)}</select></label>)}{['notificationChannel','notificationLanguage'].map(key=><label key={key}>{key}<select value={student[key]||(key==='notificationChannel'?'sms':form.language)} onChange={e=>updateStudent(student.id,key,e.target.value)}>{(key==='notificationChannel'?['sms','whatsapp','both']:['mr','en','both']).map(v=><option key={v}>{v}</option>)}</select></label>)}</fieldset>:<p>Select a student above to edit preferences.</p>}</section>
 <section className="school-panel workflow-panel"><h3>Communication Queue / Log</h3><button onClick={()=>act(async()=>{const count=await prepareAutomationDue();setJobs(readStored('erp_pro_message_jobs',[]));setNotice(`${count} due dry-run jobs prepared.`)})}>Prepare due previews now</button><button onClick={()=>setJobs(readStored('erp_pro_message_jobs',[]))}>Refresh queue</button><p>Queued previews are never labelled Sent or Delivered. Scheduling runs only while this app is open.</p>{jobs.slice().reverse().map(job=><article className="record-card" key={job.id}><div><strong>{job.type} · {job.studentName}</strong><p>{job.recipient||job.parentName} · {job.parentMobile} · {job.channel}</p><p>{job.date} · {job.initiatedAt} · {job.status} {job.dryRun?'(DRY RUN)':''} · Attempts {job.attempts||0}</p><pre className="message-preview">{job.message}</pre><p>{job.failureReason}</p>{job.dryRun&&job.status==='Failed'&&<button disabled={!admin||(job.attempts||0)>=form.maxRetries} onClick={()=>act(async()=>{const source=schoolStorage.getItem('erp_pro_message_jobs'),all=readStored('erp_pro_message_jobs',[]),current=all.find(j=>j.id===job.id);if(!current||current.attempts>=mergedAutomation(readStored(automationKey,{})).maxRetries)throw Error('Retry limit reached.');const next=all.map(j=>j.id===job.id?retryDryRun(j,readStored('erp_pro_students',[]),readStored('schoolSettings',{}),mergedAutomation(readStored(automationKey,{}))):j);if(sharedOperationalEnabled)await saveSharedMessageJobs(next,readStored('erp_pro_message_jobs',[]));else commitStoredBatch({erp_pro_message_jobs:next},{erp_pro_message_jobs:source});setJobs(next)})}>Retry Failed validation</button>}</div></article>)}</section></div>;
}
