import {markedAbsent} from "../services/attendanceAutomationStore";
import {useState,useContext} from 'react';
import {CommunicationSession} from '../backend/CommunicationSession';
import CallFollowup from './CallFollowup';
import './FamilyContactCard.css';
import {parentContacts,communicationLink,communicationKeys,communicationRecord,normalizeParentMobile} from '../services/absenceCommunication';
import {readStored,commitStoredBatch,localDate} from '../storage';
import {defaultWorkflow} from '../services/messageWorkflow';
import {notify} from './Feedback';
import {useLanguage} from '../design/language';
import Icon from './Icon';
export default function FamilyContactCard({student,message='',date=localDate(),compact=false,onNavigate,requireAbsent=false}){
 const actor=useContext(CommunicationSession);
 const {t}=useLanguage(),[reveal,setReveal]=useState(requireAbsent),[callId,setCallId]=useState(null);
 const primary=student.primaryNotificationContact||readStored(communicationKeys.settings,{}).primaryContact||'father';
 const contacts=parentContacts(student,primary),relations=[['father','Father','वडील'],['mother','Mother','आई'],['emergency','Emergency Contact','आपत्कालीन संपर्क']];
 relations.sort((a,b)=>Number(b[0]===(contacts.find(c=>c.mobile)?.id))-Number(a[0]===(contacts.find(c=>c.mobile)?.id)));
 const body=message||`${student.name}, Class ${student.className}/${student.division||''}: Please contact the school.`;
 const number=(s,id,channel)=>channel==='whatsapp'&&['father','mother'].includes(id)&&s[id==='father'?'fatherWhatsapp':'motherWhatsapp']?normalizeParentMobile(s[id==='father'?'fatherWhatsapp':'motherWhatsapp']):parentContacts(s).find(c=>c.id===id)?.mobile;
 const launch=(e,id,channel)=>{const fresh=readStored('erp_pro_students',[]).find(s=>s.id===student.id),contact=fresh&&parentContacts(fresh).find(c=>c.id===id),mobile=fresh&&number(fresh,id,channel),enabled=channel==='call'||readStored('erp_pro_message_settings',defaultWorkflow).channels.some(c=>c.id===channel&&c.enabled);if(!actor?.uid||!contact||!mobile||!enabled||(requireAbsent&&!markedAbsent(fresh,date))){e.preventDefault();return notify('This contact or channel is unavailable. Choose another saved contact.');}if(mobile!==number(student,id,channel)){e.preventDefault();return notify('Parent contact changed. Reopen the student before contacting.');}e.currentTarget.href=communicationLink(channel,mobile,body,navigator.userAgent);const record=communicationRecord(fresh,{...contact,mobile},date,channel,actor.uid,{initiatedByName:actor.email,message:channel==='call'?'':body,source:'Parent & Emergency Contact Card',status:channel==='call'?'Dialer requested':'Composer requested',failureReason:'Device action; connection and delivery unverified'});try{const entries={[communicationKeys.history]:[...readStored(communicationKeys.history,[]),record]};if(channel==='call'){const followups=readStored(communicationKeys.followups,{}),key=JSON.stringify([date,String(student.id)]);entries[communicationKeys.followups]={...followups,[key]:{...followups[key],status:'Contact Attempted',response:followups[key]?.response||'',updatedBy:actor.uid,updatedAt:record.initiatedAt}};}commitStoredBatch(entries);if(channel==='call')setCallId(record.id);window.dispatchEvent(new Event('communication-history-changed'));}catch{notify('History could not be saved. The device action is still available.')};};
 return <section className={`family-contact-card ${compact?'compact':''}`} aria-label={`Parent and emergency contacts for ${student.name}`}><div className="family-card-heading"><span><Icon name="phone" size={19}/><strong>{t('Parent & Emergency Contacts','पालक व आपत्कालीन संपर्क')}</strong></span><button onClick={()=>setReveal(!reveal)}>{reveal?t('Hide numbers','क्रमांक लपवा'):t('Show numbers','क्रमांक दाखवा')}</button></div><div className="family-contact-grid">{relations.map(([id,label,mr])=>{const contact=contacts.find(c=>c.id===id);return <article className={`family-person ${id}`} key={id}><span className="family-relation">{t(label,mr)}</span><strong>{contact?.name||t('Not provided','नोंद नाही')}</strong>{id==='emergency'&&student.emergencyRelation&&<small>{student.emergencyRelation}</small>}<span className="family-number">{contact?.mobile?(reveal?contact.mobile:`•••••• ${contact.mobile.slice(-4)}`):t('Number not saved','क्रमांक उपलब्ध नाही')}</span><div className="family-actions">{[['call',`Call ${id==='emergency'?'Emergency':label}`,'phone'],['sms',`SMS ${id==='emergency'?'Emergency':label}`,'message'],...(id==='emergency'?[]:[['whatsapp',`WhatsApp ${label}`,'message']])].map(([channel,title,icon])=>contact?.mobile?<a key={channel} aria-label={title} href={communicationLink(channel,number(student,id,channel),body,navigator.userAgent)||undefined} target={channel==='whatsapp'?'_blank':undefined} rel="noopener noreferrer" onClick={e=>launch(e,id,channel)}><Icon name={icon} size={14}/>{t(title,channel==='call'?'कॉल':channel==='sms'?'SMS':'WhatsApp')}</a>:<button key={channel} disabled aria-label={title}>{title}</button>)}</div></article>})}</div>{onNavigate&&<div className="family-card-footer"><span>{t('Missing a number? Use another saved contact.','क्रमांक नाही? दुसरा जतन केलेला संपर्क वापरा.')}</span><button onClick={()=>onNavigate('Communications',{initialStudentIds:[student.id],initialMessage:body})}>{t('Audio & history','ध्वनी संदेश व इतिहास')} →</button></div>}<CallFollowup key={`${student.id}:${date}:${callId || "history"}`} student={student} date={date} callId={callId} onSaved={()=>setCallId(null)}/></section>;
}
