import {schoolStorage} from '../backend/demoClient';
import {useContext,useState} from 'react';
import {CommunicationSession} from '../backend/CommunicationSession';
import {readStored,useStoredState,localDate,commitStoredBatch} from '../storage';
import {staffStatuses,planMessages,daySchedule} from '../services/attendanceAutomation';
import {configForAttendance} from '../services/attendanceAutomationStore';
const staffRoster=()=>[...readStored('erp_pro_teachers',[]).map(s=>({...s,id:`teacher:${s.id}`,designation:s.designation||'Teacher'})),...readStored('erp_pro_staff',[]).map(s=>({...s,id:`staff:${s.id}`,name:s.name||s['पूर्ण नाव'],designation:s.designation||s['पद']||'Staff'}))].filter(s=>s.status!=='Archived');
export default function StaffAttendance(){
 const session=useContext(CommunicationSession),[date,setDate]=useState(localDate()),[drafts,saveDrafts]=useStoredState('erp_pro_staff_attendance_drafts',{}),[review,setReview]=useState(null),[notice,setNotice]=useState('');
 const staff=staffRoster(),records=readStored('erp_pro_staff_attendance',{}),locked=!!records[date];
 const rows=staff.map(s=>({...s,...(records[date]?.rows||[]).find(r=>r.id===s.id),...drafts[date]?.[s.id]}));
 const change=(id,key,value)=>{setReview(null);saveDrafts({...drafts,[date]:{...drafts[date],[id]:{...drafts[date]?.[id],[key]:value}}})};
 const snapshots=()=>Object.fromEntries(['erp_pro_staff','erp_pro_teachers','erp_pro_staff_attendance','erp_pro_staff_attendance_drafts','erp_pro_message_jobs','erp_pro_attendance_automation','schoolSettings'].map(k=>[k,schoolStorage.getItem(k)]));
 const act=fn=>{try{fn()}catch(e){setNotice(e.message)}};
 if(!session?.modules.includes('Staff'))return null;
 return <section className="school-panel workflow-panel"><h2>Staff Attendance / कर्मचारी उपस्थिती</h2><label>Staff attendance date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setReview(null)}}/></label><p>{locked?'Finalized — saved attendance shown.':'Draft marks only. Review before submitting.'}</p><fieldset disabled={locked}>{rows.map(row=><article key={row.id}><h4>{row.name} · {row.designation}</h4><div className="form-grid"><label>Status<select aria-label={`Staff status ${row.name}`} value={row.status||''} onChange={e=>change(row.id,'status',e.target.value)}><option value="">Not Marked</option>{staffStatuses.map(s=><option key={s}>{s}</option>)}</select></label>{['inTime','outTime','lateTime','leaveType','reason','remark'].map(key=><label key={key}>{key}<input type={key.endsWith('Time')?'time':'text'} value={row[key]||''} onChange={e=>change(row.id,key,e.target.value)}/></label>)}</div></article>)}</fieldset>{!staff.length&&<p>Add teachers or staff in their existing master registers first.</p>}<button disabled={locked||!staff.length} onClick={()=>act(()=>{if(!date||date>localDate()||daySchedule(date,configForAttendance()).closed)throw Error('Choose a working school day, no later than today.');if(rows.some(r=>!staffStatuses.includes(r.status)||r.status==='Late'&&!r.inTime))throw Error('Mark all staff and record late arrival times.');setReview({date,rows,expected:snapshots()});setNotice('Review the staff attendance below before Final Submit.');})}>Review staff attendance</button>{review&&<><ul>{review.rows.map(r=><li key={r.id}>{r.name} · {r.status} · {r.inTime} · {r.reason}</li>)}</ul><button onClick={()=>act(()=>{if(!session?.uid||review.date!==date)throw Error('Review current date with verified user.');const old=readStored('erp_pro_staff_attendance',{});if(old[date])throw Error('Already finalized.');const events=review.rows.filter(r=>['Absent','Late'].includes(r.status)).map(r=>({type:`Staff ${r.status}`,staff:true,staffId:r.id,key:`staff:${date}:${r.id}`,fields:{date,staff_name:r.name,designation:r.designation,time:r.inTime}}));const jobs=planMessages(events,[],readStored('schoolSettings',{}),configForAttendance(),readStored('erp_pro_message_jobs',[]),session.uid);commitStoredBatch({erp_pro_staff_attendance:{...old,[date]:{rows:review.rows,submittedBy:session.uid,submittedAt:new Date().toISOString()}},erp_pro_message_jobs:jobs},review.expected);setReview(null);setNotice('Staff attendance finalized. Configured management alerts queued as dry-run previews.');})}>Final Submit staff attendance</button></>}<p role="status">{notice}</p></section>;
}
