import {test,expect} from '@playwright/test';
import {nav} from './portal-navigation.mjs';

const students=[{id:'life-1',name:'Lifecycle One',grNo:'L001',className:'8',division:'A',rollNo:'1',academicYear:'2026-27',status:'Active',mobile:'9876543210',fatherName:'Father One',fatherMobile:'9876543210'},{id:'life-2',name:'Lifecycle Two',grNo:'L002',className:'8',division:'A',rollNo:'2',academicYear:'2026-27',status:'Active',mobile:'9876543211'}];
const read=(page,key)=>page.evaluate(k=>JSON.parse(window.TEST_STORAGE.getItem(k)||'null'),key);
async function setup(page){
 await page.goto('/login');if(!page.url().startsWith('http://127.0.0.1:5398/'))throw Error('Isolated QA server required');
 await page.getByRole('button',{name:'EN',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('admin1234');await page.getByRole('button',{name:'Login',exact:true}).click();await page.locator('.portal-shell').waitFor();
 await page.evaluate(async students=>{const client=await import(performance.getEntriesByType('resource').filter(r=>r.name.includes('/src/backend/demoClient.js')).at(-1).name);window.TEST_STORAGE=client.schoolStorage;const entries=Object.fromEntries(client.schoolStorage.keys().filter(k=>client.demoKey(k)).map(k=>[k,null]));client.demoCommit({...entries,erp_pro_students:students,erp_pro_results:[{id:'mark1',studentId:'life-1',academicYear:'2026-27',exam:'Annual',subject:'Math',obtainedMarks:75,maxMarks:100}],erp_pro_attendance:{'2026-09-14':{'life-1':'Absent'},'2026-09-15':{'life-1':'Absent'},'2026-09-16':{'life-1':'Absent'}}});},students);
}
async function confirm(page){await page.getByRole('button',{name:'Preview lifecycle changes',exact:true}).click();await page.getByLabel('I reviewed results, selected students and every proposed change.').check();await page.getByRole('button',{name:'Confirm lifecycle changes',exact:true}).click();}
test('bulk year end keeps IDs, freezes history, repeats selected student and rejects stale preview',async({page})=>{await setup(page);await nav(page,'Lifecycle');await page.getByRole('button',{name:'Select visible enrolled students',exact:true}).click();await page.getByLabel('Next academic year',{exact:true}).fill('2027-28');await page.getByLabel('Reason (required)',{exact:true}).fill('Year-end review');await page.getByLabel('Decision Lifecycle Two',{exact:true}).selectOption('Repeat');await page.getByRole('button',{name:'Preview lifecycle changes',exact:true}).click();await page.getByLabel('I reviewed results, selected students and every proposed change.').check();await page.getByRole('button',{name:'Confirm lifecycle changes',exact:true}).click();const next=await read(page,'erp_pro_students');expect(next.map(s=>s.id)).toEqual(['life-1','life-2']);expect(next[0].className).toBe('9');expect(next[1].className).toBe('8');expect(next[1].status).toBe('Repeated');expect((await read(page,'erp_pro_academic_history'))[0].results[0].id).toBe('mark1');expect((await read(page,'erp_pro_results'))).toHaveLength(1);
 await page.getByLabel('Select Lifecycle One',{exact:true}).check();await page.getByLabel('Lifecycle action',{exact:true}).selectOption('Archive');await page.getByRole('button',{name:'Preview lifecycle changes',exact:true}).click();await page.evaluate(()=>{const students=JSON.parse(window.TEST_STORAGE.getItem('erp_pro_students'));students[0].mobile='9876543299';window.TEST_STORAGE.setItem('erp_pro_students',JSON.stringify(students))});await page.getByLabel('I reviewed results, selected students and every proposed change.').check();await page.getByRole('button',{name:'Confirm lifecycle changes',exact:true}).click();expect((await read(page,'erp_pro_students'))[0].archivedAt).toBeUndefined();await expect(page.getByText('Data changed since preview. Reload and validate again.',{exact:true})).toBeVisible();});
test('school leaving excludes attendance; archive/restore preserve withdrawal and LC can be issued from history',async({page})=>{await setup(page);await nav(page,'Lifecycle');await page.getByLabel('Select Lifecycle One',{exact:true}).check();await page.getByLabel('Lifecycle action',{exact:true}).selectOption('School Left');await page.getByLabel('Reason (required)',{exact:true}).fill('Family moved');await confirm(page);expect((await read(page,'erp_pro_students'))[0].status).toBe('School Left');await nav(page,'Attendance');await expect(page.locator('tr[data-student-id="life-1"]')).toHaveCount(0);await nav(page,'Lifecycle');await page.getByLabel('Select Lifecycle One',{exact:true}).check();await page.getByLabel('Lifecycle action',{exact:true}).selectOption('Delete Student');await page.getByLabel('Reason (required)',{exact:true}).fill('Archive retained history');await confirm(page);expect((await read(page,'erp_pro_students'))).toHaveLength(2);await page.getByLabel('Select Lifecycle One',{exact:true}).check();await page.getByLabel('Lifecycle action',{exact:true}).selectOption('Restore');await confirm(page);expect((await read(page,'erp_pro_students'))[0].status).toBe('School Left');await nav(page,'Formats');await page.getByLabel('Format',{exact:true}).selectOption('Leaving Certificate');await page.getByLabel('Document student',{exact:true}).selectOption('life-1');for(const [label,value]of Object.entries({reason:'Relocation','last class':'8',progress:'Good',conduct:'Good'}))await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel('Confirm actual LC issue and remove selected students from active rolls. Draft generation alone does not change enrollment.').check();await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Generate document',exact:true}).click();expect((await read(page,'erp_pro_students'))[0].status).toBe('TC/LC Issued');expect((await read(page,'erp_pro_certificates'))[0].studentId).toBe('life-1');});
test('long absence has correct contacts, editable bilingual audio text, alert rules and mobile layout',async({page})=>{await setup(page);await nav(page,'LongAbsence');await page.getByLabel('As of date',{exact:true}).fill('2026-09-16');await expect(page.getByText(/Consecutive: 3/)).toBeVisible();expect(await page.getByRole('link',{name:'Call Parent',exact:true}).getAttribute('href')).toBe('tel:+919876543210');expect(await page.getByRole('link',{name:'SMS',exact:true}).getAttribute('href')).toContain('sms:+919876543210');await page.evaluate(()=>document.addEventListener('click',e=>{if(e.target.closest('a'))e.preventDefault()}));await page.getByRole('link',{name:'Call Parent',exact:true}).click();expect((await read(page,'erp_pro_absence_communications'))[0].studentId).toBe('life-1');await page.getByLabel('Message language',{exact:true}).selectOption('mr');await expect(page.getByLabel('Absence message Lifecycle One',{exact:true})).toHaveValue(/सलग 3/);await page.getByLabel('Enable local absence alerts',{exact:true}).check();await page.getByRole('button',{name:'Save absence alert rules',exact:true}).click();await page.getByRole('button',{name:'Prepare absence alerts',exact:true}).click();expect((await read(page,'erp_pro_long_absence_alerts'))).toHaveLength(2);await page.getByRole('button',{name:'Prepare absence alerts',exact:true}).click();expect((await read(page,'erp_pro_long_absence_alerts'))).toHaveLength(2);await page.getByLabel('Follow-up status',{exact:true}).selectOption('Medical Reason');expect((await read(page,'erp_pro_long_absence_followups'))['life-1'].status).toBe('Medical Reason');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await nav(page,'Lifecycle');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
