import {test,expect} from '@playwright/test';
import * as XLSX from 'xlsx';
import fs from 'node:fs/promises';
import {coreDesignFixture} from './fixtures/core-design.mjs';
import {nav} from './portal-navigation.mjs';
const out='artifacts/implementation-proof';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8l8AAAAASUVORK5CYII=','base64');
const read=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('erp_pro_students')||'[]'));
async function setup(page){await page.goto('/');await page.evaluate(data=>{localStorage.clear();for(const[k,v]of Object.entries(data))localStorage.setItem(k,JSON.stringify(v))},coreDesignFixture());await page.reload();await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('admin1234');await page.getByRole('button',{name:'Login',exact:true}).click();await fs.mkdir(out,{recursive:true});}
const rows=[{'Photo Number':'1001','Student Name':'Shantanu Sunil Pawar','Class':'8','Division':'A','Roll Number':'71','GR Number':'PROOF-1001','Admission Number':'PROOF-A1','DOB':'2012-05-01','Academic Year':'2026-27','Father Name':'Sunil Pawar','Father Mobile':'9876543210','Mother Name':'Asha Pawar','Mother Mobile':'9876543211','Emergency Contact Name':'Rahul Pawar','Emergency Mobile':'9876543212','Address':'Sample school road'}, {'Photo Number':'1002','Student Name':'Aditi Patil','Class':'8','Division':'B','Roll Number':'72','GR Number':'PROOF-1002','Father Mobile':'9876543213','Academic Year':'2026-27'}];
function workbook(type){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Students');return type==='csv'?Buffer.from(XLSX.utils.sheet_to_csv(wb.Sheets.Students)):Buffer.from(XLSX.write(wb,{type:'buffer',bookType:type==='xls'?'biff8':'xlsx'}));}
async function upload(page,type='xlsx'){await nav(page,'Students');await page.getByRole('button',{name:'Import Excel',exact:true}).click();await page.getByLabel('Upload Excel',{exact:true}).setInputFiles({name:'sample-students.'+type,mimeType:'application/octet-stream',buffer:workbook(type)});await page.getByRole('button',{name:'Validate',exact:true}).click();}
async function shot(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test('real Excel and photo import, edit and persistent directory evidence',async({page})=>{
 test.setTimeout(120000);await setup(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1000});await shot(page,'home-desktop');
 await nav(page,'Students');for(const name of ['Add student','Import Excel','Download Excel Template','Export Excel'])await expect(page.getByRole('button',{name,exact:true})).toBeVisible();await expect(page.getByRole('columnheader',{name:'Emergency Mobile',exact:true})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download Excel Template',exact:true}).click();const template=XLSX.read(await fs.readFile(await(await download).path()),{type:'buffer'});const headers=XLSX.utils.sheet_to_json(template.Sheets[template.SheetNames[0]],{header:1})[0];for(const name of ['Photo Number','Student Full Name','Standard','Emergency Contact Name','Emergency Mobile','Father Mobile','Mother Mobile','Academic Year'])expect(headers).toContain(name);
 await upload(page);expect((await read(page)).some(s=>s.grNo==='PROOF-1001')).toBe(false);await expect(page.getByLabel('Marathi name row 2')).toHaveValue('शांतनु सुनील पवार');await fs.writeFile(`${out}/sample-students.xlsx`,workbook('xlsx'));
 const photoBuffers=await page.evaluate(()=>['#173755','#c7a469'].map(color=>{const c=document.createElement('canvas');c.width=30;c.height=40;c.getContext('2d').fillStyle=color;c.getContext('2d').fillRect(0,0,30,40);return c.toDataURL('image/png').split(',')[1]}));
 await page.getByLabel('Photos with Excel',{exact:true}).setInputFiles([{name:'1002.png',mimeType:'image/png',buffer:Buffer.from(photoBuffers[1],'base64')},{name:'1001.png',mimeType:'image/png',buffer:Buffer.from(photoBuffers[0],'base64')},{name:'unmatched.png',mimeType:'image/png',buffer:png}]);await page.getByRole('button',{name:'Preview Excel photo matches'}).click();await expect(page.getByLabel('Photo action unmatched.png')).toBeVisible();await expect(page.getByRole('button',{name:'Confirm Import',exact:true})).toBeDisabled();await page.getByLabel('Photo action unmatched.png').selectOption('skip');await expect(page.getByLabel('Photo action 1001.png')).toHaveValue('attach');await expect(page.getByLabel('Photo action 1002.png')).toHaveValue('attach');const expectedPhotos={};for(const gr of ['PROOF-1001','PROOF-1002'])expectedPhotos[gr]=await page.locator('.combined-photo-import tbody tr').filter({hasText:gr}).locator('img').getAttribute('src');await shot(page,'excel-photo-preview');
 await page.getByLabel('I reviewed all rows and before/after changes. Save only the selected actions.').check();await page.getByRole('button',{name:'Confirm Import',exact:true}).click();await page.getByLabel('Search students').fill('PROOF-');await expect(page.locator('tr[data-student-id]')).toHaveCount(2);let imported=(await read(page)).filter(s=>s.grNo.startsWith('PROOF-'));expect(imported).toHaveLength(2);for(const s of imported)expect(s.photo).toBe(expectedPhotos[s.grNo]);expect(imported[0].photo).not.toBe(imported[1].photo);await shot(page,'student-master-imported');
 const student=imported.find(s=>s.grNo==='PROOF-1001'),row=page.locator(`tr[data-student-id="${student.id}"]`);await expect(row).toContainText('9876543212');for(const name of ['View','Edit','Change Class','Change Division','Change Academic Year','Promote','School Left','Archive','Delete'])await expect(row.getByRole('button',{name:name==='View'?'View profile PROOF-1001':name==='Archive'?'Archive student':name,exact:true})).toBeVisible();
 await row.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('input[name="emergencyContact"]').fill('9876543219');await page.locator('input[name="fatherName"]').fill('Sunil Pawar Updated');await shot(page,'student-edit');await page.getByRole('button',{name:'Save Student',exact:true}).click();const edited=(await read(page)).find(s=>s.id===student.id);expect(edited.emergencyContact).toBe('9876543219');expect(edited.fatherName).toBe('Sunil Pawar Updated');expect(edited.photo).toBe(student.photo);expect((await read(page)).find(s=>s.grNo==='PROOF-1002')).toEqual(imported.find(s=>s.grNo==='PROOF-1002'));
 await page.reload();await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('admin1234');await page.getByRole('button',{name:'Login',exact:true}).click();await nav(page,'Students');await page.getByLabel('Search students').fill('PROOF-1001');await expect(page.locator(`tr[data-student-id="${student.id}"]`)).toContainText('9876543219');
 for(const width of [390,360]){await page.setViewportSize({width,height:844});await nav(page,'Dashboard');await shot(page,`home-${width}`);await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.locator('.portal-group-trigger').filter({hasText:'Students'}).click();await shot(page,`menu-${width}`);await page.keyboard.press('Escape');await nav(page,'Students');await shot(page,`students-${width}`);await page.getByRole('button',{name:'Import Excel',exact:true}).click();await shot(page,`import-${width}`)}expect(errors).toEqual([]);
});
for(const format of ['xls','csv'])test(`real ${format} import appears in Student Master`,async({page})=>{await setup(page);await upload(page,format);await page.getByLabel('I reviewed all rows and before/after changes. Save only the selected actions.').check();await page.getByRole('button',{name:'Confirm Import',exact:true}).click();await page.getByLabel('Search students').fill('PROOF-');await expect(page.locator('tr[data-student-id]')).toHaveCount(2);expect((await read(page)).find(s=>s.grNo==='PROOF-1001').emergencyContact).toBe('9876543212')});
test('combined import rejects duplicate photos and stale student snapshot',async({page})=>{await setup(page);await upload(page);await page.getByLabel('Photos with Excel',{exact:true}).setInputFiles([{name:'1001.png',mimeType:'image/png',buffer:png},{name:'1001.PNG',mimeType:'image/png',buffer:png}]);await page.getByRole('button',{name:'Preview Excel photo matches'}).click();await expect(page.getByRole('cell',{name:'Duplicate photos: same identifier',exact:true})).toHaveCount(2);await expect(page.getByRole('button',{name:'Confirm Import',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Remove selected photos'}).click();await page.getByLabel('I reviewed all rows and before/after changes. Save only the selected actions.').check();await page.evaluate(()=>{const students=JSON.parse(localStorage.getItem('erp_pro_students'));students[0].address='Concurrent edit';localStorage.setItem('erp_pro_students',JSON.stringify(students))});await page.getByRole('button',{name:'Confirm Import',exact:true}).click();await expect(page.getByText('Data changed since preview. Reload and validate again.',{exact:true})).toBeVisible();expect((await read(page)).some(s=>s.grNo==='PROOF-1001')).toBe(false)});
