import { test, expect } from '@playwright/test';
import { coreDesignFixture } from './fixtures/core-design.mjs';
import { nav } from './portal-navigation.mjs';
import fs from 'node:fs/promises';

const folder='artifacts/institutional-review';
const read=(page,key)=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
async function setup(page){await page.goto('/');await page.evaluate(data=>{localStorage.clear();for(const [key,value]of Object.entries(data))localStorage.setItem(key,JSON.stringify(value));const students=JSON.parse(localStorage.getItem('erp_pro_students'));localStorage.setItem('erp_pro_students',JSON.stringify(students.map(s=>({...s,academicYear:'2026-27'}))));localStorage.setItem('erp_pro_portal_notices',JSON.stringify([{id:'review-notice',title:'Parent–teacher meeting · Saturday, 10:00 AM',titleMr:'पालक सभा · शनिवार, सकाळी १० वाजता',published:true,date:'2026-09-17'}]));},coreDesignFixture());await page.reload();await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('admin1234');await page.getByRole('button',{name:'Login',exact:true}).click();await fs.mkdir(folder,{recursive:true});}
async function shot(page,name){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name+' page overflow').toBe(true);}

test('institutional desktop/mobile review and complete student change flow',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1000});await setup(page);
 await shot(page,'01-Desktop-Home');await page.locator('.portal-group-trigger').filter({hasText:'Students'}).click();await shot(page,'02-Desktop-Dropdown');await page.keyboard.press('Escape');
 await nav(page,'Students');await shot(page,'03-Student-Master');await page.getByLabel('Rows per page').selectOption('10');await expect(page.locator('tr[data-student-id]')).toHaveCount(10);await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText('Page 2 / 4',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add student',exact:true}).click();for(const [key,value]of Object.entries({firstName:'Shantanu',middleName:'Sunil',lastName:'Pawar',grNo:'REVIEW-NEW',className:'8',division:'B',rollNo:'50',fatherName:'Sunil Pawar',fatherMobile:'9876543210',motherName:'Asha Pawar',motherMobile:'9876543211',emergencyName:'Rahul Pawar',emergencyRelation:'Uncle',emergencyContact:'9876543212'}))await page.locator(`input[name="${key}"]`).fill(value);
 await expect(page.locator('input[name="name"]')).toHaveValue('Shantanu Sunil Pawar');await expect(page.locator('input[name="student_name_mr"]')).toHaveValue('शांतनु सुनील पवार');await shot(page,'04-Add-Student');await page.getByRole('button',{name:'Save Student',exact:true}).click();
 const student=(await read(page,'erp_pro_students')).find(s=>s.grNo==='REVIEW-NEW');expect(student.academicYear).toBe('2026-27');expect(student.student_name_en).toBe('Shantanu Sunil Pawar');const before=await read(page,'erp_pro_attendance');
 for(const [action,fields,name]of [['Change Class',{'New standard':'9'},'06-Class-Change'],['Change Division',{'New division':'C'},'07-Division-Change'],['Change Academic Year',{'Destination academic year':'2027-28'},'08-Academic-Year-Change']]){
   await page.locator('tr[data-student-id="'+student.id+'"]').getByRole('button',{name:action,exact:true}).click();const dialog=page.getByRole('dialog');for(const [label,value]of Object.entries(fields))await dialog.getByLabel(label,{exact:true}).fill(value);await dialog.getByLabel('Reason for change').fill('Reviewed school enrollment correction');await dialog.getByRole('button',{name:'Preview change',exact:true}).click();await shot(page,name);await dialog.getByLabel('I reviewed this student and the proposed change.').check();await dialog.getByRole('button',{name:'Confirm student change',exact:true}).click();
 }
 const updated=(await read(page,'erp_pro_students')).find(s=>s.id===student.id);expect(updated.className).toBe('9');expect(updated.division).toBe('C');expect(updated.academicYear).toBe('2027-28');expect(await read(page,'erp_pro_attendance')).toEqual(before);expect((await read(page,'erp_pro_academic_history')).filter(s=>s.studentId===student.id)).toHaveLength(3);
 await page.getByRole('button',{name:'View profile REVIEW-NEW'}).click();await shot(page,'09-Student-Profile');await page.getByRole('button',{name:'Back to student directory',exact:true}).click();
 await page.locator('tr[data-student-id="'+student.id+'"]').getByRole('button',{name:'Delete',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Reason for change').fill('Archive review, preserve all history');await dialog.getByRole('button',{name:'Preview change',exact:true}).click();await shot(page,'10-Delete-Archive');await dialog.getByLabel('I reviewed this student and the proposed change.').check();await dialog.getByRole('button',{name:'Confirm archive'}).click();expect((await read(page,'erp_pro_students')).find(s=>s.id===student.id).status).toBe('Archived');expect(await read(page,'erp_pro_attendance')).toEqual(before);
 await nav(page,'Students');await page.getByRole('button',{name:'Import Excel',exact:true}).click();await page.getByLabel('Upload Excel',{exact:true}).setInputFiles({name:'review.csv',mimeType:'text/csv',buffer:Buffer.from('Full Name,GR Number,Standard,Photo Number,Father Mobile\nShantanu Sunil Pawar,EXCEL-REVIEW,8,1001,9876543210')});await expect(page.getByLabel('Marathi name row 2')).toHaveValue('शांतनु सुनील पवार');await page.getByRole('button',{name:'Validate',exact:true}).click();await shot(page,'11-Excel-Import');
 await nav(page,'AcademicYears');await shot(page,'12-Academic-Years');
 for(const width of [1024,768,390,360]){await page.setViewportSize({width,height:900});await nav(page,'Dashboard');expect(await page.getByRole('button',{name:'Open navigation'}).isVisible()).toBe(true);await shot(page,`13-Home-${width}`);await page.getByRole('button',{name:'Open navigation'}).click();await page.locator('.portal-group-trigger').filter({hasText:'Students'}).click();await shot(page,`14-Menu-${width}`);await page.keyboard.press('Escape');await nav(page,'Students');await shot(page,`15-Students-${width}`);}
 expect(errors).toEqual([]);
});

test('student preview rejects stale records and cancellation preserves data',async({page})=>{
 await setup(page);await nav(page,'Students');const original=await read(page,'erp_pro_students');const first=original[0];await page.locator(`tr[data-student-id="${first.id}"]`).getByRole('button',{name:'Change Division',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('New division').fill('Z');await dialog.getByLabel('Reason for change').fill('Stale preview test');await dialog.getByRole('button',{name:'Preview change',exact:true}).click();await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('erp_pro_students'));s[0].address='Changed in another tab';localStorage.setItem('erp_pro_students',JSON.stringify(s));});await dialog.getByLabel('I reviewed this student and the proposed change.').check();await dialog.getByRole('button',{name:'Confirm student change'}).click();await expect(dialog.getByRole('alert')).toBeVisible();expect((await read(page,'erp_pro_students'))[0].division).toBe(first.division);await dialog.getByRole('button',{name:'Close student action'}).click();expect(await read(page,'erp_pro_academic_history')).toBeNull();
});
