import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import {nav} from './portal-navigation.mjs';
import {coreDesignFixture} from './fixtures/core-design.mjs';
const identity=JSON.parse(await fs.readFile('../assets/school-identity.json','utf8'));
const folder='artifacts/official-identity';
async function login(page){await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('admin1234');await page.getByRole('button',{name:'Login',exact:true}).click()}
async function screenshot(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test('official identity migrates settings, appears in real pages and all print formats',async({page})=>{
 test.setTimeout(120000);await fs.mkdir(folder,{recursive:true});await page.goto('/');
 await page.evaluate(data=>{localStorage.clear();for(const[k,v]of Object.entries(data))localStorage.setItem(k,JSON.stringify(v));localStorage.setItem('schoolSettings',JSON.stringify({schoolName:'Previous school label',sansthaName:'Previous institution label',address:'Previous address',schoolCode:'KEEP-CODE',udise:'KEEP-UDISE',contactNumber:'9876543210',customField:'preserve'}))},coreDesignFixture());await page.reload();await page.setViewportSize({width:1440,height:1000});
 await expect(page.locator('.login-school-brand')).toContainText(identity.institutionNameMr.split('\n')[0]);await expect(page.locator('.login-school-brand')).toContainText(identity.schoolNameMr);await expect(page.locator('.login-school-brand')).toContainText(identity.addressMr);await screenshot(page,'login');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('schoolSettings')));expect(saved.schoolName).toBe(identity.schoolNameMr);expect(saved.sansthaName).toBe(identity.institutionNameMr);expect(saved.address).toBe(identity.addressMr);expect(saved.schoolCode).toBe('KEEP-CODE');expect(saved.customField).toBe('preserve');expect(saved.schoolNameEn).toBe('');expect(await page.evaluate(revision=>JSON.parse(localStorage.getItem('schoolSettings_before_'+revision)).schoolName,identity.identityRevision)).toBe('Previous school label');
 await login(page);await expect(page.locator('.portal-brand')).toContainText(identity.institutionNameMr.split('\n')[1]);await expect(page.locator('.portal-brand')).toContainText(identity.addressMr);await screenshot(page,'dashboard');
 const source=await page.locator('.portal-brand img').getAttribute('src');expect(Buffer.from(source.split(',')[1],'base64')).toEqual(await fs.readFile('../assets/school-logo.jpg'));
 for(const[type,name]of [['Student ID Card','id-card'],['Bonafide Certificate','bonafide']]){await nav(page,'Formats');await page.getByLabel('Format',{exact:true}).selectOption(type);await page.getByLabel('Document student',{exact:true}).selectOption('review-student-1');await page.getByRole('button',{name:'Preview',exact:true}).click();const frame=page.frameLocator('iframe');await expect(frame.locator('header')).toContainText(identity.institutionNameMr.split('\n')[0]);await expect(frame.locator('header')).toContainText(identity.schoolNameMr);await expect(frame.locator('header')).toContainText(identity.addressMr);await expect(frame.getByAltText('School logo')).toBeVisible();const html=await page.locator('iframe').getAttribute('srcdoc');await fs.writeFile(`${folder}/${name}.html`,html);const document=await page.context().newPage();await document.setContent(html);await document.pdf({path:`${folder}/${name}.pdf`,format:'A4',printBackground:true});await document.close()}
 const formats=await page.evaluate(async()=>{const {formatTypes,defaultFormat,templateContext,renderFormat}=await import('/src/services/templates.js');const settings=JSON.parse(localStorage.getItem('schoolSettings'));return formatTypes.map(type=>({type,html:renderFormat(defaultFormat(type),templateContext({name:'Sample',id:'proof'},settings))}))});for(const result of formats){expect(result.html,result.type).toContain(identity.schoolNameMr);expect(result.html,result.type).toContain(identity.institutionNameMr);expect(result.html,result.type).toContain(identity.addressMr)}
 await nav(page,'Reports');await page.getByRole('button',{name:'Preview printable report',exact:true}).click();await expect(page.frameLocator('iframe').locator('header')).toContainText(identity.schoolNameMr);
 await nav(page,'Settings');for(const name of ['schoolNameEn','institutionNameEn','addressEn','contactNumber','schoolCode','udise','academicYear'])await expect(page.locator(`[name="${name}"]`)).toBeVisible();
 await page.setViewportSize({width:390,height:844});await nav(page,'Dashboard');await screenshot(page,'mobile-header');await page.getByRole('button',{name:'Open navigation',exact:true}).click();await screenshot(page,'mobile-menu');await page.goto('/download-app');await expect(page.locator('.app-download-brand')).toContainText(identity.schoolNameMr);await screenshot(page,'download-page');
});
test('older web entry also resolves official identity without replacing student data',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.goto('http://127.0.0.1:5174/');
 await page.evaluate(()=>{localStorage.setItem('v32_settings',JSON.stringify({school:'Previous label',address:'Previous address',mobile:'9876543210'}));localStorage.setItem('v32_students',JSON.stringify([{id:'identity-proof',name:'Sample student',className:'8'}]))});await page.reload();
 await expect(page.locator('#schoolTitle')).toHaveText(identity.schoolNameMr);await expect(page.locator('#schoolAddressTitle')).toHaveText(identity.addressMr);await expect(page.locator('.official-institution')).toHaveText(identity.institutionNameMr);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('v32_students'))[0].id)).toBe('identity-proof');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('v32_settings')).mobile)).toBe('9876543210');expect(errors).toEqual([]);
});
