import {test,expect} from '@playwright/test';
import {coreDesignFixture} from './fixtures/core-design.mjs';
import {portalGroups} from '../src/design/portalNavigation.js';
import {nav} from './portal-navigation.mjs';
import fs from 'node:fs/promises';
async function setup(page){await page.goto('/');await page.evaluate(data=>{localStorage.clear();for(const[k,v]of Object.entries(data))localStorage.setItem(k,JSON.stringify(v))},coreDesignFixture());await page.reload();await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('123456');await page.getByRole('button',{name:'Login',exact:true}).click();}
test('all dropdown destinations work; desktop, tablet and mobile portal review',async({page})=>{
 test.setTimeout(180000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.setViewportSize({width:1440,height:1000});
 for(const group of portalGroups){for(const item of group.items){await page.locator('.portal-group-trigger').filter({hasText:group.en}).click();await page.locator('.portal-dropdown:not([hidden])').getByRole('button',{name:item.en,exact:true}).click();await expect(page.locator('#school-main')).not.toBeEmpty();await expect(page.getByText('This page could not be displayed')).toHaveCount(0)}}
 await fs.mkdir('artifacts/portal-redesign',{recursive:true});
 for(const key of ['Dashboard','Students','Attendance','Academics','Formats','Trips','Sports','Library','Communications']){await nav(page,key);await page.screenshot({path:`artifacts/portal-redesign/${key}.png`,fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),key).toBe(true)}
 await nav(page,'Students');await page.getByRole('button',{name:'Import Excel',exact:true}).click();await page.screenshot({path:'artifacts/portal-redesign/ExcelImport.png',fullPage:true,animations:'disabled'});
 await nav(page,'Dashboard');await page.locator('.portal-group-trigger').filter({hasText:'Students'}).click();await page.screenshot({path:'artifacts/portal-redesign/Navigation.png',fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');
 for(const width of [1024,768,390,360]){await page.setViewportSize({width,height:844});for(const key of ['Dashboard','Students','Attendance','Academics','Formats','Trips','Sports','Library','Communications']){await nav(page,key);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${key} ${width}`).toBe(true)}}
 await page.setViewportSize({width:390,height:844});await nav(page,'Dashboard');await page.screenshot({path:'artifacts/portal-redesign/MobileDashboard.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.locator('.portal-group-trigger').filter({hasText:'Students'}).click();await page.screenshot({path:'artifacts/portal-redesign/MobileNavigation.png',animations:'disabled'});await page.keyboard.press('Escape');await page.getByRole('button',{name:'मराठी',exact:true}).click();await page.screenshot({path:'artifacts/portal-redesign/Marathi.png',fullPage:true,animations:'disabled'});expect(errors).toEqual([]);
});
test('notice publication, school identity, gallery ordering and role previews',async({page})=>{
 await setup(page);await nav(page,'PortalContent');await page.getByLabel('Title (English)',{exact:true}).fill('Science exhibition');await page.getByLabel('Title (Marathi)',{exact:true}).fill('विज्ञान प्रदर्शन');await page.getByLabel('Announcement',{exact:true}).fill('School hall at 10 AM.');await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect(page.locator('.announcement-copy')).not.toContainText('Science exhibition');await page.getByRole('button',{name:'Publish',exact:true}).click();await nav(page,'Dashboard');await expect(page.locator('.announcement-copy')).toContainText('Science exhibition');
 await nav(page,'PortalContent');await page.getByRole('button',{name:'Unpublish',exact:true}).click();await nav(page,'Dashboard');await expect(page.locator('.announcement-copy')).not.toContainText('Science exhibition');
 await nav(page,'PortalContent');await page.getByRole('button',{name:'Event slider',exact:true}).click();for(const name of ['School event one','School event two']){await page.getByLabel('Photo caption',{exact:true}).fill(name);await page.getByLabel('Upload slider image',{exact:true}).setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8l8AAAAASUVORK5CYII=','base64')});await expect(page.getByRole('heading',{name,exact:true})).toBeVisible()}
 await page.getByRole('button',{name:'Move School event two earlier',exact:true}).click();await nav(page,'Dashboard');await expect(page.locator('.portal-hero h1')).toHaveText('School event two');await page.getByRole('button',{name:'Next slide',exact:true}).click();await expect(page.locator('.portal-hero h1')).toHaveText('School event one');
 await page.getByLabel('Role preview',{exact:true}).selectOption('Library Staff');await expect(page.locator('.portal-nav [data-nav="Settings"]')).toHaveCount(0);await expect(page.locator('.portal-nav [data-nav="Library"]')).not.toHaveCount(0);await nav(page,'PortalContent');await expect(page.getByRole('button',{name:'Save draft',exact:true})).toHaveCount(0);
 await page.getByLabel('Role preview',{exact:true}).selectOption('Admin');await nav(page,'Settings');await page.locator('input[name="schoolCode"]').fill('GBS-REVIEW');await page.locator('input[name="udise"]').fill('12345678901');await page.getByRole('button',{name:'Save Settings',exact:true}).click();await expect(page.locator('.portal-brand')).toContainText('GBS-REVIEW');await expect(page.locator('.portal-brand')).toContainText('12345678901');
});
