import {sharedOperationalEnabled} from './backend/sharedReadCache';
import {useSharedDataGate} from "./backend/useSharedDataGate";
import {CommunicationSession} from "./backend/CommunicationSession";
import useSchoolSession from "./backend/useSchoolSession";
import AccountSecurity from "./pages/AccountSecurity";
import AcademicYears from './pages/AcademicYears';
import EmergencyContacts from './pages/EmergencyContacts';
import StudentLifecycle from './pages/StudentLifecycle';
import LongAbsence from './pages/LongAbsence';
import { useEffect, useState } from "react";
import { readStored } from "./storage";
import PortalHome, { Academics } from "./pages/PortalHome";
import PortalShell from "./design/PortalShell";
import PortalContent from "./pages/PortalContent";
import PortalInfo from "./pages/PortalInfo";

import TeacherDashboard from "./pages/TeacherDashboard";
import Students from "./pages/Students";
import Teachers from "./pages/Teachers";
import Attendance from "./pages/Attendance";
import Homework from "./pages/Homework";
import Classwork from "./pages/Classwork";
import SchoolFormats from "./pages/SchoolFormats";
import Certificates from "./pages/Certificates";
import IDCard from "./pages/IDCard";
import Results from "./pages/Results";
import GeneralRegister from "./pages/GeneralRegister";
import Scholarships from "./pages/Scholarships";
import Communications from "./pages/Communications";
import AccessSetup from "./pages/AccessSetup";
import BackupRestore from "./pages/BackupRestore";
import Reports from "./pages/Reports";
import Settings from "./pages/Settings";
import Parents from "./pages/Parents";
import Trips from "./pages/Trips";
import Sports from "./pages/Sports";
import Library from "./pages/Library";
import SchoolLogin from "./pages/SchoolLogin";
import OperationalModules from "./pages/OperationalModules";
import SchoolOperations from "./pages/SchoolOperations";
import Feedback, { PageBoundary } from "./components/Feedback";
import "./App.css";
import PhotoImport from "./pages/PhotoImport";
import AutomationSettings from "./pages/AutomationSettings";
import StudentCheckout from "./pages/StudentCheckout";
import Fees from "./pages/Fees";
import ParentInteractions from "./pages/ParentInteractions";
import {prepareDailyMessages} from "./services/messageStore";
import {notify} from "./components/Feedback";

const pages = { AcademicYears, EmergencyContacts, Lifecycle: StudentLifecycle, LongAbsence, PhotoImport, Automation: AutomationSettings, Checkout: StudentCheckout, Fees, Meetings: ParentInteractions, Visits: ParentInteractions, PortalInfo, PortalContent, Academics, Students, Teachers, Attendance, Homework, Classwork, Certificates, Formats: SchoolFormats, Admissions: GeneralRegister, Scholarships, Communications, AccessSetup, Backup: BackupRestore, Results, IDCard, Reports, Parents, Trips, Sports, Library };
const defaults = {};

export default function App() {
  const [settings,setSettings]=useState(()=>readStored("schoolSettings",defaults));
  const [pageVersion,setPageVersion]=useState(0);
  const {session,status,logout}=useSchoolSession();
  const dataGate=useSharedDataGate(session);
  const login=!!session, role=session?.role;
  const allowed=page=>!!session && (page==="AccountSecurity" || session.modules.includes(page));
  const [active,setActive]=useState("Dashboard"),[pageOptions,setPageOptions]=useState({});
  const navigate=(key,options={})=>{setPageVersion(v=>v+1);if(!allowed(key)){setActive("PortalInfo");setPageOptions({title:"Access not granted to this account",titleMr:"या भूमिकेच्या पूर्वदृश्यात प्रवेश उपलब्ध नाही"});return;}setActive(key);setPageOptions(options);window.scrollTo({top:0});};
  useEffect(()=>{if(!login||sharedOperationalEnabled)return;const prepare=()=>{try{prepareDailyMessages()}catch(e){notify(e.message)}};prepare();const timer=setInterval(prepare,60000);return()=>clearInterval(timer)},[login]);
  useEffect(()=>{const changed=()=>setSettings(readStored("schoolSettings",defaults));window.addEventListener("academic-year-changed",changed);return()=>window.removeEventListener("academic-year-changed",changed)},[]);
  const Page=pages[active];
  useEffect(()=>{const changed=()=>setSettings(sharedOperationalEnabled?readStored('schoolSettings',session?.school||{}):session?.school?{...session.school,tenantId:session.schoolId,sansthaName:session.school.institutionName}:readStored('schoolSettings',defaults));changed();window.addEventListener('school-data-changed',changed);return()=>window.removeEventListener('school-data-changed',changed);},[session?.schoolId,session?.school]);
  return <CommunicationSession.Provider value={session}><div className="design-system portal-design"><Feedback/>{session?.development && <div role="status" style={{background:"#fff3cd",color:"#553c00",padding:"10px",textAlign:"center",fontWeight:700}}>DEVELOPMENT / TEST MODE</div>}{login&&session.schoolId&&<div className="perfectedu-tenant-banner">PerfectEdu ? {settings.schoolName} ? UDISE: {session.udise||"Awaiting verified code"} ? {settings.academicYear||"2026-27"}</div>}{!login?<SchoolLogin settings={settings} status={status}/>:<PortalShell key={session.schoolId||'production'} settings={settings} active={active} role={role} allowed={allowed} onNavigate={navigate} onLogout={logout}><PageBoundary key={active}>{!dataGate.ready?<p role="status">{dataGate.error||"Connecting to the shared school database..."}</p>:active==="AccountSecurity"?<AccountSecurity session={session}/>:!allowed(active)?<AccountSecurity session={session}/>:active==="Dashboard"?<PortalHome settings={settings} allowed={allowed} role={role} onNavigate={navigate}/>:active==="TeacherDashboard"?<TeacherDashboard onNavigate={navigate}/>:active==="Settings"?<Settings onSaved={setSettings} onNavigate={navigate}/>: ["Inventory","Timetable","Calendar","Staff"].includes(active)?<SchoolOperations key={active} module={active}/>:Page?<Page key={active+JSON.stringify(pageOptions)+pageVersion} kind={active==="Visits"?"Visit":"Meeting"} {...pageOptions} settings={settings} role={role} onNavigate={navigate}/>:<OperationalModules key={active} module={active}/>}</PageBoundary></PortalShell>}</div></CommunicationSession.Provider>;
}
