import AcademicYearControl from './AcademicYearControl';
import {currentAcademicYear} from '../services/academicYears';
import { useEffect, useRef, useState } from 'react';
import { useLanguage } from './language';
import { SchoolMark, LanguageSwitch, Avatar } from './SchoolUI';
import { portalGroups, roles, canView } from './portalNavigation';
import Icon from '../components/Icon';
import { readStored } from '../storage';

export default function PortalShell({ settings, active, onNavigate, role, onRole, onLogout, children }) {
  const { t } = useLanguage(); const [open,setOpen]=useState(''),[mobile,setMobile]=useState(false); const nav=useRef(null), hamburger=useRef(null);
  const [,refresh]=useState(0);
  useEffect(()=>{const changed=()=>refresh(n=>n+1);window.addEventListener('portal-content-changed',changed);window.addEventListener('academic-year-changed',changed);window.addEventListener('storage',changed);return()=>{window.removeEventListener('portal-content-changed',changed);window.removeEventListener('academic-year-changed',changed);window.removeEventListener('storage',changed)}},[]);
  const groups=portalGroups.map(g=>({...g,items:g.items.filter(i=>canView(role,i.page))})).filter(g=>g.items.length);
  const go=(page,options)=>{onNavigate(page,options);setOpen('');setMobile(false)};
  useEffect(()=>{const close=e=>{if(e.key==='Escape'){setOpen('');setMobile(false);hamburger.current?.focus()} if(e.type==='pointerdown'&&!nav.current?.contains(e.target)&&!hamburger.current?.contains(e.target)){setOpen('');setMobile(false)}};document.addEventListener('keydown',close);document.addEventListener('pointerdown',close);return()=>{document.removeEventListener('keydown',close);document.removeEventListener('pointerdown',close)}},[]);
  const notices=readStored('erp_pro_portal_notices',[]).filter(n=>n.published);
  const [noticeIndex,setNoticeIndex]=useState(0),[paused,setPaused]=useState(false),[hovered,setHovered]=useState(false);
  useEffect(()=>{if(paused||hovered||notices.length<2||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setInterval(()=>setNoticeIndex(i=>i+1),6500);return()=>clearInterval(id)},[paused,hovered,notices.length]);
  const notice=notices[noticeIndex%Math.max(notices.length,1)];
  return <div className="portal-shell"><a className="skip-link" href="#school-main">{t('Skip to content','मुख्य भागाकडे जा')}</a>
    <div className="portal-utility"><span><Icon name="cap" size={15}/>{t('KNOWLEDGE • CHARACTER • OPPORTUNITY','ज्ञान • चारित्र्य • संधी')}</span><span>{t('Academic year','शैक्षणिक वर्ष')} {currentAcademicYear()} <span className="utility-dot">•</span> {t('School office portal','शालेय कार्यालय पोर्टल')}</span></div>
    <header className="portal-masthead"><button className="portal-hamburger" ref={hamburger} aria-label="Open navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><Icon name="menu"/></button><button className="portal-brand" onClick={()=>go('Dashboard')} aria-label={t('School home','शाळेचे मुख्यपृष्ठ')}><SchoolMark logo={settings.logo}/><span><small>{settings.sansthaName || t('Institution / Trust name','संस्था / मंडळाचे नाव')}</small><strong>{settings.schoolName}</strong><span>{settings.address}</span><em>{t('School code','शाळा संकेतांक')}: {settings.schoolCode||'—'} <b>·</b> UDISE: {settings.udise||t('To be configured','नोंद करणे बाकी')}</em></span></button><div className="institution-badge"><Icon name="award" size={30}/><strong>{settings.recognition||t("School office","शालेय कार्यालय")}</strong><small>{settings.affiliation||t("Learning • Care • Achievement","शिक्षण • काळजी • यश")}</small></div></header><div className="portal-command-bar"><AcademicYearControl role={role} onNavigate={go}/><div className="portal-account"><LanguageSwitch/><button aria-label="Open noticeboard" className="portal-icon-button" onClick={()=>go('PortalContent',{tab:'notices'})}><Icon name="bell"/>{notices.length>0&&<i/>}</button><button className="portal-profile" onClick={()=>go('TeacherDashboard')} aria-label="Open teaching workspace"><Avatar name="School Admin"/><span>{t('School office','शालेय कार्यालय')}<small>{t('Local review','स्थानिक आढावा')}</small></span></button><button className="portal-icon-button" onClick={onLogout} aria-label="Logout"><Icon name="logout"/></button></div></div>
    <div className="portal-nav-wrap" ref={nav}><nav className={`portal-nav ${mobile?'is-open':''}`} aria-label="Main navigation"><button className={`portal-home-link ${active==='Dashboard'?'selected':''}`} data-nav="Dashboard" onClick={()=>go('Dashboard')}><Icon name="grid" size={16}/>{t('Home','मुख्यपृष्ठ')}</button>{groups.map(g=><div className={`portal-nav-group ${open===g.en?'expanded':''}`} key={g.en}><button className="portal-group-trigger" aria-expanded={open===g.en} aria-controls={`menu-${g.en.replaceAll(' ','-')}`} onClick={()=>setOpen(open===g.en?'':g.en)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(g.en);setTimeout(()=>document.getElementById(`menu-${g.en.replaceAll(' ','-')}`)?.querySelector('button')?.focus(),0)}}}>{t(g.en,g.mr)}<span aria-hidden="true">⌄</span></button><div className="portal-dropdown" id={`menu-${g.en.replaceAll(' ','-')}`} hidden={open!==g.en}><div className="portal-menu-heading"><Icon name={g.icon}/><div><strong>{t(g.en,g.mr)}</strong><small>{t('Your school, connected','आपली शाळा, एकत्र जोडलेली')}</small></div></div><div className="portal-menu-items">{g.items.map((i,index)=><button key={`${i.en}-${index}`} data-nav={i.page} onClick={()=>go(i.page,i.options)}><span>{t(i.en,i.mr)}</span><Icon name="chevron" size={14}/></button>)}</div></div></div>)}<button className="portal-mobile-logout" onClick={onLogout} aria-label="Logout"><Icon name="logout" size={17}/>{t("Sign out","बाहेर पडा")}</button></nav></div>
    <div className="portal-announcement" onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)}><strong><Icon name="bell" size={15}/>{t('NOTICEBOARD','सूचना फलक')}</strong><button className="announcement-copy" onClick={()=>go('PortalContent',{tab:'notices'})}>{notice ? (t(notice.title,notice.titleMr||notice.title)) : t('Welcome to your school portal. Published announcements will appear here.','शालेय पोर्टलवर स्वागत. प्रकाशित सूचना येथे दिसतील.')}</button>{notices.length>1&&<button className="ticker-pause" aria-label={paused?'Play announcements':'Pause announcements'} onClick={()=>setPaused(!paused)}>{paused?'▶':'Ⅱ'}</button>}<button className="announcement-all" onClick={()=>go('PortalContent',{tab:'notices'})}>{t('View all','सर्व पहा')} →</button></div>
    <div className="portal-context"><span>{t('My school','आपली शाळा')} <span>/</span> {active==='Dashboard'?t('Overview','आढावा'):active}</span><label>{t('Role preview','भूमिका पूर्वदृश्य')}<select aria-label="Role preview" value={role} onChange={e=>{onRole(e.target.value);go('Dashboard')}}>{roles.map(r=><option key={r}>{r}</option>)}</select><small>{t('UI only · account permissions pending','केवळ दृश्य · खाते परवानग्या प्रलंबित')}</small></label></div>
    <main id="school-main" className="portal-main" tabIndex={-1}>{children}</main><footer className="portal-footer"><SchoolMark logo={settings.logo}/><div><strong>{settings.schoolName}</strong><p>{t('Nurturing learners. Inspiring tomorrow.','विद्यार्थ्यांना घडवूया. उद्याला प्रेरणा देऊया.')}</p></div><span>{currentAcademicYear()}<br/>{t('School portal • Local review','शालेय पोर्टल • स्थानिक आढावा')}</span></footer>
    <nav className="portal-bottom" aria-label="Quick navigation">{[['Dashboard','Home','मुख्यपृष्ठ','grid'],['Students','Students','विद्यार्थी','users'],['Attendance','Attendance','उपस्थिती','calendar'],['Communications','Parents','पालक','message']].filter(([p])=>canView(role,p)).map(([p,en,mr,icon])=><button key={p} aria-current={active===p?'page':undefined} onClick={()=>go(p)}><Icon name={icon} size={20}/>{t(en,mr)}</button>)}</nav>
  </div>;
}
