const item = (en, mr, page, options = {}) => ({ en, mr, page, options });
const setup = (en, mr) => item(en, mr, 'PortalInfo', { title: en, titleMr: mr });
const format = (en, mr, type = en) => item(en, mr, 'Formats', { initialType: type });
const report = (en, mr, type) => item(en, mr, 'Reports', { reportType: type });
export const portalGroups = [
  { en: 'About', mr: 'शाळा', icon: 'cap', items: [setup('About Trust / Institution','संस्था / मंडळाविषयी'),setup('About School','शाळेविषयी'),setup('Vision & Mission','ध्येय व उद्दिष्टे'),setup('Management','व्यवस्थापन'),setup("Headmaster’s Desk",'मुख्याध्यापकांचे मनोगत'),item('Staff','कर्मचारी','Staff'),setup('School Information','शाळेची माहिती'),setup('Recognition / Affiliation','मान्यता / संलग्नता'),setup('Infrastructure','पायाभूत सुविधा')] },
  { en: 'Students', mr: 'विद्यार्थी', icon: 'users', items: [item('Promote Students / Year-End','विद्यार्थी पदोन्नती','Lifecycle'),item('Student Lifecycle / History','विद्यार्थी शैक्षणिक इतिहास','Lifecycle'),item('Student Master','विद्यार्थी नोंदणी','Students'),item('Add Student','विद्यार्थी जोडा','Students',{mode:'add'}),item('Excel Import','Excel आयात','Students',{mode:'import'}),item('Photo Folder Import','छायाचित्र फोल्डर आयात','PhotoImport'),report('Excel Export','Excel निर्यात','Students'),item('Student Profile','विद्यार्थी माहिती','Students'),item('General Register','जनरल रजिस्टर','Admissions'),item('Admission','प्रवेश','Admissions'),item('Student Documents','विद्यार्थी कागदपत्रे','Admissions'),item('ID Cards','ओळखपत्रे','IDCard'),item('QR Cards','QR ओळखपत्रे','IDCard'),item('School Left','शाळा सोडलेले विद्यार्थी','Lifecycle',{initialStatus:'School Left'}),item('Archived Students','संग्रहित विद्यार्थी','Students',{archived:true})] },
  { en:'Academics',mr:'शैक्षणिक',icon:'book',items:[item('Academic Years','शैक्षणिक वर्षे','AcademicYears'),item('Study Material','अभ्यास साहित्य','Homework'),item('Academic Overview','शैक्षणिक आढावा','Academics'),...['8','9','10','11','12'].map(c=>item(`Class ${c}`,`इयत्ता ${c}`,'Students',{initialClass:c})),setup('Subjects','विषय'),item('Timetable','वेळापत्रक','Timetable'),item('Homework','गृहपाठ','Homework'),item('Assignments','स्वाध्याय','Classwork'),item('Examinations','परीक्षा','Results'),item('Marks Entry','गुण नोंदणी','Results'),item('Excel Marks Import','Excel गुण आयात','Results'),item('Results','निकाल','Results'),format('Progress Cards','प्रगती पत्रके','Progress Card'),format('Annual Results','वार्षिक निकाल','Annual Result')] },
  { en:'Attendance',mr:'उपस्थिती',icon:'calendar',items:[item('Long Absent Students','दीर्घ अनुपस्थित विद्यार्थी','LongAbsence'),item('Daily Attendance','दैनंदिन उपस्थिती','Attendance'),item('Student Checkout','विद्यार्थी निर्गमन','Checkout'),item('Class Attendance','वर्ग उपस्थिती','Attendance'),report('Monthly Attendance','मासिक उपस्थिती','Attendance Summary'),item('Absent Students','अनुपस्थित विद्यार्थी','Attendance',{initialStatus:'Absent'}),item('Late Students','उशिरा आलेले विद्यार्थी','Attendance',{initialStatus:'Late'}),item('Leave','रजा','Attendance',{initialStatus:'Leave'}),report('Attendance Reports','उपस्थिती अहवाल','Attendance'),item('Parent Alert','पालक सूचना','Communications')] },
  { en:'Certificates',mr:'प्रमाणपत्रे',icon:'award',items:[item('Certificate Studio','प्रमाणपत्र केंद्र','Certificates'),format('Bonafide','बोनाफाईड','Bonafide Certificate'),format('Leaving Certificate','शाळा सोडल्याचे प्रमाणपत्र'),format('Character Certificate','चारित्र्य प्रमाणपत्र'),format('Study Certificate','शिक्षण प्रमाणपत्र'),item('ID Card','ओळखपत्र','IDCard'),format('Marksheet','गुणपत्रक'),item('Custom Certificates','सानुकूल प्रमाणपत्रे','Formats'),item('Bulk Generate','एकत्रित प्रमाणपत्रे','Formats'),item('Certificate History','प्रमाणपत्र इतिहास','Formats')] },
  { en:'Educational Trip',mr:'शैक्षणिक सहल',icon:'pin',items:[...['Create Trip|सहल तयार करा','Select Students|विद्यार्थी निवडा','Medical Information|आरोग्य माहिती','Emergency Contacts|आपत्कालीन संपर्क','Trip Attendance|सहल उपस्थिती','Live Location / GPS|स्थान / GPS','Parent Updates|पालकांना माहिती','WhatsApp / SMS|WhatsApp / SMS','Audio Updates|ध्वनी संदेश'].map(s=>{const [en,mr]=s.split('|');return item(en,mr,'Trips')}),format('Trip Student List','सहल विद्यार्थी यादी'),format('Parent Consent','पालक संमती'),format('Trip Documents','सहल कागदपत्रे','Educational Trip Form'),report('Trip Reports','सहल अहवाल','Trip Students')] },
  { en:'Sports',mr:'क्रीडा',icon:'trophy',items:[...['Player Registration|खेळाडू नोंदणी','Sports List|खेळांची यादी','Competition|स्पर्धा','Age / Weight Category|वय / वजन गट','District / Division / State / National|जिल्हा / विभाग / राज्य / राष्ट्रीय','Achievements|यशोगाथा','Equipment Issue / Return|साहित्य वितरण / परतावा'].map(s=>{const[en,mr]=s.split('|');return item(en,mr,'Sports')}),format('Sports Certificates','क्रीडा प्रमाणपत्रे','Sports Certificate'),item('Sports Attendance','क्रीडा उपस्थिती','Attendance',{initialStatus:'Sports Duty'})] },
  { en:'Scholarship',mr:'शिष्यवृत्ती',icon:'award',items:['Scholarship Master|शिष्यवृत्ती नोंदणी','Eligible Students|पात्र विद्यार्थी','Applications|अर्ज','Documents|कागदपत्रे','Pending|प्रलंबित','Approved|मंजूर','Deadline Alerts|अंतिम मुदत सूचना'].map(s=>{const[en,mr]=s.split('|');return item(en,mr,'Scholarships')}) },
  { en:'Library',mr:'ग्रंथालय',icon:'book',items:['Book Master|पुस्तक नोंदणी','Issue Book|पुस्तक वितरण','Return Book|पुस्तक परतावा','Student History|विद्यार्थी इतिहास','Due / Overdue|परताव्याची मुदत','QR / Barcode|QR / बारकोड'].map(s=>{const[en,mr]=s.split('|');return item(en,mr,'Library')}) },
  { en:'Parents',mr:'पालक',icon:'message',items:[report('Parent Directory','पालक यादी','Parent Contact List'),item('Parent Meetings','पालक सभा','Meetings'),item('Parent Visit Register','पालक भेट नोंद','Visits'),...['Communication|पालक संवाद','WhatsApp|WhatsApp','SMS|SMS','Call|दूरध्वनी','Audio Message|ध्वनी संदेश','Communication History|संवाद इतिहास'].map(s=>{const[en,mr]=s.split('|');return item(en,mr,'Communications')}),item('Emergency Contacts','आपत्कालीन संपर्क','EmergencyContacts')] },
  { en:'Staff',mr:'कर्मचारी',icon:'badge',items:[item('Teacher Master','शिक्षक नोंदणी','Teachers'),item('Teaching Workspace','शिक्षक कार्यस्थान','TeacherDashboard'),...['Teacher Login|शिक्षक खाते','Class Assignment|वर्ग नेमणूक','Subject Assignment|विषय नेमणूक','Roles & Permissions|भूमिका व परवानग्या'].map(s=>{const[en,mr]=s.split('|');return item(en,mr,'AccessSetup')}),setup('Staff Attendance','कर्मचारी उपस्थिती')] },
  { en:'Reports',mr:'अहवाल',icon:'chart',items:[...['Student Reports|विद्यार्थी अहवाल|Students','Attendance Reports|उपस्थिती अहवाल|Attendance Summary','Academic Reports|शैक्षणिक अहवाल|Homework','Result Reports|निकाल अहवाल|Results','Sports Reports|क्रीडा अहवाल|Sports Students','Trip Reports|सहल अहवाल|Trip Students','Scholarship Reports|शिष्यवृत्ती अहवाल|Scholarship Students','Library Reports|ग्रंथालय अहवाल|Library'].map(s=>{const[en,mr,type]=s.split('|');return report(en,mr,type)}),item('Custom Reports','सानुकूल अहवाल','Reports')] },
  { en:'More',mr:'अधिक',icon:'grid',items:[item('Notices','सूचना','PortalContent',{tab:'notices'}),item('Office Notice Register','कार्यालयीन सूचना नोंदवही','Notices'),format('Circulars','परिपत्रके'),item('Gallery','छायाचित्र संग्रह','PortalContent',{tab:'slides'}),item('Events','कार्यक्रम','Calendar'),item('Downloads','डाउनलोड','Formats'),item('Forms','नमुने','Formats'),item('Fees','शुल्क','Fees'),item('Transport','वाहतूक','Transport'),item('School Assets','शालेय मालमत्ता','Inventory'),item('Automation','स्वयंचलित कामकाज','Automation'),item('Settings','सेटिंग्ज','Settings'),item('Backup','बॅकअप','Backup'),item('Audit Logs','कामकाज इतिहास','Backup')] },
];
const facilities={en:'Facilities',mr:'सुविधा',icon:'cap',items:[item('Library','ग्रंथालय','Library'),item('Sports','क्रीडा','Sports'),setup('Laboratory','प्रयोगशाळा'),setup('Computer Lab','संगणक कक्ष'),item('School Transport','शालेय वाहतूक','Transport'),item('School Assets','शालेय मालमत्ता','Inventory'),setup('Other Facilities','इतर सुविधा')]};
portalGroups.splice(portalGroups.length-1,0,facilities);
const staff=portalGroups.find(g=>g.en==='Staff'),scholarship=portalGroups.find(g=>g.en==='Scholarship');
portalGroups.find(g=>g.en==='More').items.push(...staff.items,...scholarship.items);
portalGroups.splice(portalGroups.indexOf(staff),1);portalGroups.splice(portalGroups.indexOf(scholarship),1);
portalGroups.splice(4,0,{en:'Exam',mr:'परीक्षा',icon:'file',items:[item('Exams & Results','परीक्षा व निकाल','Results'),item('Marks Entry','गुण नोंद','Results'),format('Progress Cards','प्रगती पत्रके','Progress Card'),format('Annual Results','वार्षिक निकाल','Annual Result')]});
// Keep the primary school navigation in a stable administrative order.
portalGroups.push({en:'Exam',mr:'???????',icon:'book',items:[item('Exam & Marks Entry','??????? ? ???','Results'),item('Exam Timetable','??????? ?????????','Timetable')]},{en:'Results',mr:'?????',icon:'chart',items:[item('Student Results','?????????? ?????','Results'),format('Result Documents','????? ?????????','Progress Card')]});
const primaryOrder=['About','Students','Academics','Attendance','Exam','Results','Sports','Educational Trip','Library','Parents','Certificates','Reports','More'];
const scholarshipAgain=portalGroups.find(g=>g.en==='Scholarship'),more=portalGroups.find(g=>g.en==='More');
if(scholarshipAgain&&more){more.items.push(...scholarshipAgain.items);portalGroups.splice(portalGroups.indexOf(scholarshipAgain),1);}
portalGroups.sort((a,b)=>primaryOrder.indexOf(a.en)-primaryOrder.indexOf(b.en));
const studentMenu=portalGroups.find(g=>g.en==='Students');
studentMenu.items.sort((a,b)=>{const order=['Student Master','Add Student','Excel Import','Photo Folder Import'];const rank=x=>order.includes(x.en)?order.indexOf(x.en):4;return rank(a)-rank(b)});

export const roles = ['Super Admin','Headmaster','Admin','Class Teacher','Subject Teacher','Sports Teacher','Trip In-charge','Library Staff','Office Staff','Accounts Staff'];
const permissions = {
 'Accounts Staff':['Dashboard','Students','Fees','Reports','Communications'],
 'Class Teacher':['EmergencyContacts','LongAbsence','Lifecycle','Checkout','Meetings','Visits','Dashboard','PortalInfo','Academics','TeacherDashboard','Students','Attendance','Homework','Classwork','Results','Timetable','Communications','Parents','Reports','Calendar'],
 'Subject Teacher':['Dashboard','PortalInfo','Academics','TeacherDashboard','Homework','Classwork','Results','Timetable','Attendance','Calendar'],
 'Sports Teacher':['Dashboard','PortalInfo','Students','Sports','Attendance','Communications','Reports'],
 'Trip In-charge':['EmergencyContacts','Dashboard','PortalInfo','Students','Trips','Communications','Reports'],
 'Library Staff':['Dashboard','PortalInfo','Students','Library','Reports'],
 'Office Staff':['EmergencyContacts','Lifecycle','LongAbsence','PhotoImport','Checkout','Meetings','Visits','Dashboard','PortalInfo','Students','Admissions','Formats','Certificates','IDCard','Fees','Parents','Communications','Reports','Meetings','Staff','Inventory','Transport'],
};
export const canView = (role,page) => ['Dashboard','PortalContent'].includes(page) || ['Super Admin','Headmaster','Admin'].includes(role) || (permissions[role] || []).includes(page);
