import {isSharedKey,sharedSnapshot,sharedOperationalEnabled} from '../backend/sharedReadCache';
export const yearKey='erp_pro_academic_years',contextKey='erp_pro_academic_context';
export function normalizeYear(value){const m=/^(\d{4})[-–](\d{2}|\d{4})$/.exec(String(value||'').trim());if(!m)return '';const y=Number(m[1]);return Number(m[2])===(y+1)%100||Number(m[2])===y+1?`${y}-${String(y+1).slice(-2)}`:'';}
export function defaultYear(date=new Date()){const y=date.getMonth()>=5?date.getFullYear():date.getFullYear()-1;return `${y}-${String(y+1).slice(-2)}`;}
const read=(key,fallback)=>{try{return JSON.parse(isSharedKey(key)?sharedSnapshot(key):localStorage.getItem(key))||fallback}catch{return fallback}};
export function currentAcademicYear(){if(sharedOperationalEnabled)return normalizeYear(read(yearKey,[]).find(y=>y.current)?.id)||defaultYear();return normalizeYear(read(contextKey,{}).current)||normalizeYear(read('schoolSettings',{}).academicYear)||defaultYear();}
export function academicYears(){const saved=read(yearKey,[]),current=currentAcademicYear();return saved.some(y=>y.id===current)?saved:[{id:current,startDate:`${current.slice(0,4)}-06-01`,endDate:`${Number(current.slice(0,4))+1}-05-31`,status:'Open',implicit:true},...saved];}
export function yearForDate(date){const matches=academicYears().filter(y=>date>=y.startDate&&date<=y.endDate);if(matches.length===1)return matches[0].id;if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return '';const y=Number(date.slice(0,4))-(Number(date.slice(5,7))<6?1:0);return `${y}-${String(y+1).slice(-2)}`;}
export function validateYear(record,existing){if(!normalizeYear(record.id))throw Error('Use a consecutive academic year such as 2026-27.');if(existing.some(y=>normalizeYear(y.id)===normalizeYear(record.id)))throw Error('Academic year already exists.');for(const field of ['startDate','endDate'])if(!/^\d{4}-\d{2}-\d{2}$/.test(record[field])||!Number.isFinite(Date.parse(record[field]))||new Date(record[field]).toISOString().slice(0,10)!==record[field])throw Error('Choose valid start and end dates.');if(record.startDate>=record.endDate)throw Error('End date must be after start date.');if(existing.some(y=>record.startDate<=y.endDate&&record.endDate>=y.startDate))throw Error('Academic dates overlap an existing year.');return {...record,id:normalizeYear(record.id),status:'Open'};}
export const yearCollections={erp_pro_students:'Student enrollment',erp_pro_homework:'Homework',erp_pro_results:'Exams / results',erp_pro_fee_ledger:'Fees',erp_pro_scholarship_applications:'Scholarships',erp_pro_sports:'Sports',erp_pro_sports_athletes:'Sports athletes',erp_pro_trips:'Educational trips',erp_pro_library_loans:'Library loans',erp_pro_equipment_loans:'Equipment loans'};
export function tagNewYearRecords(key,value,previous=[]){if(!yearCollections[key]||!Array.isArray(value))return value;const ids=new Set((Array.isArray(previous)?previous:[]).map(r=>r.id));return value.map(r=>{if(ids.has(r.id))return r;const academicYear=normalizeYear(r.academicYear)||yearForDate(r.date||r.startDate||r.issueDate)||currentAcademicYear();if(academicYears().some(y=>y.id===academicYear&&y.status!=='Open'))throw Error('This academic year is closed or archived. Open an academic year before adding records.');return {...r,academicYear};});}
