import {lifecycleActive} from './studentLifecycle';
import {readStored,writeStored,localDate} from '../storage';
import {parentContacts} from './absenceCommunication';
import {defaultWorkflow,renderMessage,selectFallback,dailyEvents} from './messageWorkflow';
export const workflowKey='erp_pro_message_settings',jobsKey='erp_pro_message_jobs';
export function preparedJobIssue(job){
 const student=readStored('erp_pro_students',[]).find(s=>String(s.id)===String(job.studentId)&&lifecycleActive(s));if(!student)return 'Student is missing or archived. Reopen Student Master.';
 if(['Present','Absent','Late'].includes(job.type)&&readStored('erp_pro_attendance',{})[job.details?.Date]?.[job.studentId]!==job.type)return 'Attendance changed after preparation. Prepare a new message from the register.';
 if(job.type==='School Closed'&&readStored('erp_pro_attendance',{})[job.details?.Date]?.[job.studentId]!=='Present')return 'Present attendance no longer matches this closing draft.';
 if(job.type==='Library Due'){const id=job.key.split(':').slice(2).join(':'),loan=readStored('erp_pro_library_loans',[]).find(l=>String(l.id)===id);if(!loan||loan.returned||loan.dueDate!==job.details?.['Due Date'])return 'Library loan changed or was returned. Review the current loan.';}
 if(job.type==='Fee Reminder'){const id=job.key.split(':').slice(2).join(':'),fee=readStored('erp_pro_fee_ledger',[]).find(f=>String(f.id)===id);if(!fee||Number(fee.total)-Number(fee.paid)!==Number(job.details?.Amount))return 'Outstanding fee changed. Prepare a new message from Fees.';}
 return '';
}
export function queueMessages(events,{force=false}={}){const settings=readStored(workflowKey,defaultWorkflow),students=readStored('erp_pro_students',[]),jobs=readStored(jobsKey,[]),keys=new Set(jobs.map(j=>j.key)),added=[];for(const event of events){if(keys.has(event.key)||(!force&&!settings.enabled?.[event.type]))continue;const student=students.find(s=>String(s.id)===String(event.studentId)&&lifecycleActive(s));if(!student)continue;const contact=parentContacts(student).find(c=>c.mobile);const fallback=selectFallback(settings);added.push({id:crypto.randomUUID(),...event,studentId:student.id,studentName:student.name,parentName:contact?.name||'',parentMobile:contact?.mobile||'',message:renderMessage(event.type,student,event.details,settings),audio:settings.templates?.[event.type]?.audio||null,channel:fallback.channel||'none',status:'Prepared',failureReason:contact?fallback.reason:'Valid parent contact required in Student Master.',initiatedBy:'local-review',initiatedAt:new Date().toISOString()});keys.add(event.key)}if(added.length&&!writeStored(jobsKey,[...jobs,...added]))throw Error('Notification drafts could not be saved. School record may already be saved; review the queue.');return added.length;}
export function prepareDailyMessages(now=new Date()){const settings=readStored(workflowKey,defaultWorkflow),date=localDate(),time=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;return queueMessages(dailyEvents({students:readStored('erp_pro_students',[]).filter(s=>lifecycleActive(s)),attendance:readStored('erp_pro_attendance',{})[date]||{},loans:readStored('erp_pro_library_loans',[]),fees:readStored('erp_pro_fee_ledger',[]),meetings:readStored('erp_pro_parent_meetings',[]),date,time,settings}));}
