import {useSharedRecords} from '../backend/useSharedRecords';
import {useState} from 'react';
import {readStored,commitStoredBatch} from '../storage';
import {academicYears,currentAcademicYear,yearKey,contextKey,validateYear,yearForDate,yearCollections,normalizeYear} from '../services/academicYears';
import {PageHeading} from '../design/SchoolUI';
import {notify} from '../components/Feedback';
import {exportRows} from '../services/excel';
export default function AcademicYears({initialYear,role,onNavigate}){
 const [sharedYears,saveSharedYears,connection]=useSharedRecords("academic_years",yearKey);
 const [,refresh]=useState(0),[selected,setSelected]=useState(initialYear||currentAcademicYear()),[form,setForm]=useState({id:'',startDate:'',endDate:''});
 const years=(connection.shared?sharedYears:academicYears()).slice().sort((a,b)=>a.id.localeCompare(b.id)),current=currentAcademicYear(),admin=['Admin','Super Admin','Headmaster'].includes(role),position=years.findIndex(y=>y.id===current);
 const save=async entries=>{try{if(connection.shared){const next=entries[yearKey]||sharedYears;const active=entries[contextKey]?.current;if(!await saveSharedYears(next.map(y=>({...y,name:y.id,...(active?{current:y.id===active}:{})}))))return false;}else commitStoredBatch(entries);refresh(n=>n+1);window.dispatchEvent(new Event('academic-year-changed'));return true}catch(e){notify(e.message);return false}};
 const create=async()=>{if(!admin)return;try{const row=validateYear(form,years);if(await save({[yearKey]:[...years.map(({implicit:_implicit,...y})=>y),row]})){setForm({id:'',startDate:'',endDate:''});setSelected(row.id)}}catch(e){notify(e.message)}};
 const change=(y,status)=>{if(!admin)return;if(y.id===current&&status!=='Open')return notify('Activate another open year before closing or archiving the current year.');if(!confirm(`${status==='Open'?'Reopen':status} academic year ${y.id}? All records will remain available.`))return;save({[yearKey]:years.map(({implicit:_implicit,...r})=>r.id===y.id?{...r,status}:r)})};
 const activate=y=>{if(!admin||y.status!=='Open')return;if(!confirm(`Activate ${y.id}? Students are not promoted automatically. Existing records keep their years.`))return;save({[contextKey]:{...readStored(contextKey,{}),current:y.id},[yearKey]:years.map(({implicit:_implicit,...r})=>r),schoolSettings:{...readStored('schoolSettings',{}),academicYear:y.id}})};
 const records=Object.entries(yearCollections).flatMap(([key,module])=>readStored(key,[]).map(r=>({module,year:normalizeYear(r.academicYear)||yearForDate(r.date||r.startDate||r.issueDate)||'Unassigned legacy record',basis:r.academicYear?'Saved year':r.date||r.startDate||r.issueDate?'Date-based view (legacy)':'Unassigned',id:r.id,student:r.studentName||r.name||r.studentId||'',class:r.className||'',division:r.division||'',roll:r.rollNo||'',date:r.date||r.startDate||r.issueDate||''}))).concat(readStored('erp_pro_academic_history',[]).map(r=>({module:'Previous student enrollment',year:normalizeYear(r.academicYear)||'Unassigned legacy record',basis:'Saved snapshot',id:r.studentId,student:readStored('erp_pro_students',[]).find(s=>s.id===r.studentId)?.name,class:r.className,division:r.division,roll:r.rollNo})),Object.entries(readStored('erp_pro_attendance',{})).map(([date,day])=>({module:'Attendance',year:readStored('erp_pro_attendance_years',{})[date]||yearForDate(date),basis:readStored('erp_pro_attendance_years',{})[date]?'Saved year':'Date-based view (legacy)',date,recordedStudents:Object.keys(day).length}))).filter(r=>r.year===selected);
 return <div className="core-page"><PageHeading eyebrow="ACADEMIC PLANNING" title="Academic Years" description="A clear record of every school year. Switching the current year never overwrites history or promotes students."/><div className="year-summary">{[['Previous',years[position-1]?.id],['Current',current],['Next',years[position+1]?.id]].map(([label,value])=><article key={label}><span>{label} academic year</span><strong>{value||'Not created'}</strong></article>)}</div>
 {admin&&<section className="school-panel workflow-panel"><h2>Create academic year</h2><div className="form-grid"><label>Academic year name<input placeholder="2027-28" value={form.id} onChange={e=>{const id=e.target.value,y=Number(id.slice(0,4));setForm({...form,id,...(normalizeYear(id)?{startDate:`${y}-06-01`,endDate:`${y+1}-05-31`}:{})})}}/></label><label>Start date<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>End date<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div><button onClick={create}>Create Academic Year</button></section>}
 <div className="year-cards">{years.map(y=><article className={`school-panel workflow-panel ${y.id===current?'current-year':''}`} key={y.id}><span className="portal-tag">{y.id===current?'CURRENT YEAR':y.status}</span><h2>{y.id}</h2><p>{y.startDate} — {y.endDate}</p><div className="import-actions"><button onClick={()=>setSelected(y.id)}>View year records</button>{admin&&<><button disabled={y.id===current||y.status!=='Open'} onClick={()=>activate(y)}>Activate year</button><button disabled={y.id===current||y.status==='Closed'} onClick={()=>change(y,'Closed')}>Close year</button><button disabled={y.id===current||y.status==='Archived'} onClick={()=>change(y,'Archived')}>Archive year</button>{y.status!=='Open'&&<button onClick={()=>change(y,'Open')}>Reopen year</button>}</>}</div></article>)}</div><section className="school-panel workflow-panel"><div className="domain-toolbar"><label>Review academic year<select aria-label="Review academic year" value={selected} onChange={e=>setSelected(e.target.value)}>{years.map(y=><option key={y.id}>{y.id}</option>)}<option>Unassigned legacy record</option></select></label><button onClick={()=>exportRows(records,`academic-records-${selected}.xlsx`)}>Export year records</button>{admin&&<button onClick={()=>onNavigate('Lifecycle')}>Preview year-end promotion</button>}</div><p>Saved years stay attached to records. Older dated records use a labelled date-based view; undated legacy records are not guessed into a year. Active operational pages retain their existing date filters; this screen is the cross-module year review.</p><div className="table-scroll"><table><thead><tr><th>Module</th><th>Student / ID</th><th>Class / Division / Roll</th><th>Date</th><th>Year source</th></tr></thead><tbody>{records.map((r,i)=><tr key={i}><td>{r.module}</td><td>{r.student||r.id||`${r.recordedStudents} attendance entries`}</td><td>{[r.class,r.division,r.roll].filter(Boolean).join(' / ')}</td><td>{r.date}</td><td>{r.basis}</td></tr>)}</tbody></table></div>{!records.length&&<p>No records found for this year.</p>}</section></div>;
}
