import {lifecycleActive} from '../services/studentLifecycle';
import AudioRecorder from "../components/AudioRecorder";
import {defaultWorkflow,messageTemplates} from "../services/messageWorkflow";
import {jobsKey,preparedJobIssue} from "../services/messageStore";
import { useLanguage } from "../design/language";
import { useState } from "react";
import { readStored, writeStored, useStoredState, localDate } from "../storage";
import { parentContacts, communicationLink, communicationRecord, communicationKeys } from "../services/absenceCommunication";
import { saveAsset, readAsset } from "../services/assets";
import AssetLink from "../components/AssetLink";
import { PageHeading, EmptyState } from "../design/SchoolUI";
import { notify } from "../components/Feedback";
import { exportRows } from "../services/excel";

export default function Communications({ initialClass = "", initialDivision = "", initialStudentIds, initialMessage = "", audioAsset, sourceJobId }) {
  const { t } = useLanguage();
  const students = readStored("erp_pro_students", []).filter(s => lifecycleActive(s));
  const [history, saveHistory] = useStoredState(communicationKeys.history, []), [className, setClass] = useState(initialClass), [division, setDivision] = useState(initialDivision), [query, setQuery] = useState("");
  const [message, setMessage] = useState(initialMessage), [selected, setSelected] = useState(initialStudentIds || []), [contacts, setContacts] = useState({}), [queue, setQueue] = useState(null), [audio, setAudio] = useState(audioAsset || null), [busy, setBusy] = useState(false);
  const workflow=readStored("erp_pro_message_settings",defaultWorkflow);
  const enabled=channel=>(readStored("erp_pro_message_settings",defaultWorkflow).channels||defaultWorkflow.channels).some(c=>c.id===channel&&c.enabled);
  const messageFor=s=>message.replaceAll("[Student Name]",workflow.language==="mr"?(s.student_name_mr||s.name):s.name).replaceAll("[Class]",`${s.className}/${s.division||""}`).replaceAll("[Date]",localDate());
  const roster = students.filter(s => (!className || s.className === className) && (!division || s.division === division) && (!initialStudentIds || initialStudentIds.includes(s.id)) && [s.name, s.grNo].join(" ").toLowerCase().includes(query.toLowerCase()));
  const contactFor = s => { const available = parentContacts(s).filter(c => c.mobile); return available.find(c => c.id === contacts[s.id]) || available[0]; };
  const record = (s, channel, extra) => { if(sourceJobId){const job=readStored(jobsKey,[]).find(j=>j.id===sourceJobId);const issue=job?preparedJobIssue(job):"Prepared draft missing.";if(issue){notify(issue);return false;}} const contact = contactFor(s), current = readStored("erp_pro_students", []).find(item => item.id === s.id && lifecycleActive(item)); if (!enabled(channel) || !contact || !current || !parentContacts(current).some(c => c.id === contact.id && c.mobile === contact.mobile)) return false; return saveHistory([...readStored(communicationKeys.history, []), communicationRecord(current, contact, localDate(), channel, "local-review", { source: "Parent communication", sourceJobId, status: channel === "call" ? "Call Initiated" : "Manual", failureReason: "Device action; sending/delivery unverified", ...extra })]); };
  const link = (s, channel) => communicationLink(channel, contactFor(s)?.mobile, messageFor(s), navigator.userAgent);
  const sendAudio = async s => {
    if (!audio) return notify("Upload an audio notice first.");
    try { const stored = await readAsset(audio.id); if (!stored) throw new Error("Audio is missing from this browser."); const file = new File([stored.blob], stored.name, { type: stored.type }); if (!enabled("audio")) return notify("Audio channel is disabled."); if (navigator.canShare?.({ files: [file] })) { if(!record(s,"audio",{status:"Manual",audio:audio,audioName:stored.name,message:messageFor(s)}))return notify("Audio action could not be logged. Sharing stopped."); await navigator.share({ files: [file], title: "School audio notice", text: messageFor(s) }); record(s, "audio", { status: "Share sheet completed; recipient/delivery unverified", audioName: stored.name }); } else notify("File sharing is unavailable. Download the audio below, open the parent's composer and attach the file manually."); } catch (error) { if (error.name !== "AbortError") notify(error.message); }
  };
  const upload = async event => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setBusy(true); try { setAudio(await saveAsset(file, true)); } catch (error) { notify(error.message); } finally { setBusy(false); } };
  const action = (s, channel, title) => <a className="school-button secondary" href={link(s, channel) || undefined} target={channel === "whatsapp" ? "_blank" : undefined} rel="noopener noreferrer" aria-disabled={!contactFor(s)||!enabled(channel)} onClick={e => { if(channel!=="call"&&/\[[^\]]+\]/.test(messageFor(s))){e.preventDefault();notify("Replace remaining template placeholders before sending.");return;} if (!enabled(channel) || !contactFor(s) || !record(s, channel, { message: channel === "call" ? "" : messageFor(s) })) { e.preventDefault(); notify("An enabled channel, valid contact and saved communication record are required."); } else if(sourceJobId){writeStored(jobsKey,readStored(jobsKey,[]).map(j=>j.id===sourceJobId?{...j,status:"Manual",lastActionAt:new Date().toISOString()}:j));} }}>{title}</a>;
  const queueStudents = queue ? students.filter(s => queue.ids.includes(s.id)) : [];
  return <div className="core-page"><PageHeading eyebrow="A STRONGER SCHOOL–HOME CONNECTION" title="Parent communication" description="Contacts come from Student Master. Calls stay individual; messages open the device composer." /><section className="school-panel workflow-panel"><div className="domain-toolbar"><label>{t("Class")}<select aria-label="Class" value={className} onChange={e => setClass(e.target.value)}><option value="">All classes</option>{[...new Set(students.map(s => s.className))].map(c => <option key={c}>{c}</option>)}</select></label><label>{t("Division")}<input value={division} onChange={e => setDivision(e.target.value)} /></label><label>Find student<input value={query} onChange={e => setQuery(e.target.value)} /></label></div><label>Reusable template<select defaultValue="" onChange={e=>{const key=e.target.value;if(!key)return;setMessage(workflow.templates[key]?.[workflow.language]||messageTemplates[key][workflow.language==="mr"?1:0]);setAudio(workflow.templates[key]?.audio||null)}}><option value="">Choose template</option>{Object.keys(messageTemplates).map(key=><option key={key}>{key}</option>)}</select></label><label>Message (English / Marathi)<textarea aria-label="Message (English / Marathi)" value={message} onChange={e => setMessage(e.target.value)} /></label><label>Common audio notice<input type="file" accept="audio/mpeg,audio/wav,audio/ogg,audio/webm" disabled={busy} onChange={upload} /></label><AudioRecorder onRecorded={setAudio}/><AssetLink asset={audio} /><div className="import-actions"><button onClick={() => setSelected(roster.map(s => s.id))}>Select visible parents</button><button onClick={() => setSelected([])}>Clear selection</button>{["whatsapp", "sms", "audio"].filter(enabled).map(channel => <button key={channel} disabled={!selected.length || (channel === "audio" && !audio)} onClick={() => setQueue({ channel, ids: selected })}>Prepare {channel} for selected ({selected.length})</button>)}<button disabled={!selected.length} onClick={() => exportRows(students.filter(s => selected.includes(s.id)).map(s => ({ Student: s.name, GR: s.grNo, Parent: contactFor(s)?.name, Mobile: contactFor(s)?.mobile })), "selected-parent-contacts.xlsx")}>Export selected parent list</button></div><p>Provider status: NEEDS API / CREDENTIALS. Device fallback is available according to enabled channels. Review each recipient; automatic sending is inactive.</p><p>Opening a composer/dialer does not prove sending, delivery, call connection or duration. Bulk communication uses a reviewed recipient queue; automatic dispatch needs a provider API.</p></section>
    {queue && <section className="school-panel workflow-panel"><h3>{queue.channel} recipient queue</h3>{queueStudents.map(s => <div className="import-actions" key={s.id}><strong>{s.name} · {contactFor(s)?.name || "No valid contact"}</strong>{queue.channel === "audio" ? <button onClick={() => sendAudio(s)}>Share audio notice</button> : action(s, queue.channel, "Open parent composer")}</div>)}<button onClick={() => setQueue(null)}>Close queue</button></section>}
    {roster.length ? <div className="table-scroll"><table><thead><tr><th>Select / student</th><th>Parent contact</th><th>Quick actions</th></tr></thead><tbody>{roster.map(s => <tr key={s.id}><td><label><input type="checkbox" checked={selected.includes(s.id)} onChange={e => setSelected(e.target.checked ? [...selected, s.id] : selected.filter(id => id !== s.id))} />{s.name} · GR {s.grNo}</label></td><td><select aria-label={`Parent contact ${s.grNo}`} value={contactFor(s)?.id || ""} onChange={e => setContacts({ ...contacts, [s.id]: e.target.value })}>{!contactFor(s) && <option value="">No valid contact</option>}{parentContacts(s).filter(c => c.mobile).map(c => <option key={c.id} value={c.id}>{c.label} · {c.name} · ••••{c.mobile.slice(-4)}</option>)}</select></td><td><div className="import-actions">{action(s, "whatsapp", "WhatsApp")}{action(s, "sms", "SMS")}{action(s, "call", "Call Parent")}<button onClick={() => sendAudio(s)}>Audio</button></div></td></tr>)}</tbody></table></div> : <EmptyState icon="message" title="Keep families in the loop" description="Add parent contacts in Student Master or adjust your class filters." />}
    <section className="school-panel workflow-panel"><h3>Communication history</h3><button onClick={() => exportRows(history, "communication-history.csv")}>Export history CSV</button>{history.length ? <div className="table-scroll"><table><thead><tr><th>Student / parent</th><th>Date / channel / actor</th><th>Status</th><th>Remark / parent response</th></tr></thead><tbody>{history.slice().reverse().map(h => <tr key={h.id}><td>{h.studentName} · {h.parentName} · ••••{h.parentMobile?.slice(-4)}</td><td>{h.initiatedAt} · {h.channel} · {h.initiatedBy}</td><td>{h.status}</td><td><input aria-label={`Remark ${h.id}`} defaultValue={h.remark || ""} onBlur={e => { if (e.target.value !== (h.remark || "")) saveHistory(readStored(communicationKeys.history, []).map(item => item.id === h.id ? { ...item, remark: e.target.value } : item)); }} /></td></tr>)}</tbody></table></div> : <p>No communication actions recorded.</p>}<details><summary>Previous manual communication notes</summary>{readStored("erp_pro_communications", []).map(i => <pre key={i.id}>{JSON.stringify(i, null, 2)}</pre>)}</details></section></div>;
}
