import { readStored, localDate } from "../storage";
import Icon from "../components/Icon";
import { useLanguage } from "../design/language";
import { CampusIllustration, EmptyState, PageHeading, Panel } from "../design/SchoolUI";
import AcademicCalendar from "../design/AcademicCalendar";
import { attendanceSummary, calendarEvent, classKey, isActiveStudent } from "../services/schoolOverview";

export default function Dashboard({ onNavigate }) {
  const { language, t } = useLanguage();
  const students = readStored("erp_pro_students", []).filter(isActiveStudent);
  const teachers = readStored("erp_pro_teachers", []);
  const today = localDate();
  const attendance = readStored("erp_pro_attendance", {})[today] || {};
  const summary = attendanceSummary(students, attendance);
  const homework = readStored("erp_pro_homework", []);
  const calendar = readStored("erp_pro_calendar", []).map(calendarEvent);
  const notices = readStored("erp_pro_notices", []).slice(-3).reverse();
  const classes = [...new Set(students.map(classKey).filter(Boolean))].sort((a, b) => a.localeCompare(b, "en", { numeric: true }));
  const dateLabel = new Date().toLocaleDateString(language === "mr" ? "mr-IN" : "en-IN", { weekday: "long", day: "numeric", month: "long" });
  return <div className="core-page school-dashboard">
    <section className="school-office-desk" aria-label="School office desk"><div><span className="academic-eyebrow">{t("YOUR SCHOOL OFFICE", "आपले शालेय कार्यालय")}</span><strong>{t("Ready for the school day", "शालेय दिवसासाठी सज्ज")}</strong></div><button onClick={() => onNavigate("Students", { mode: "import" })}><Icon name="upload" />{t("Student Excel Import", "विद्यार्थी Excel आयात")}</button><button onClick={() => onNavigate("Formats")}><Icon name="award" />{t("School formats", "शालेय नमुने")}</button><button onClick={() => onNavigate("Communications")}><Icon name="message" />{t("Reach a parent", "पालक संपर्क")}</button></section>
    <PageHeading eyebrow={t("SCHOOL OVERVIEW", "शाळेचा आढावा")} title={t("A school day, well connected.", "आपली शाळा, एकत्र जोडलेली.")} description={dateLabel}><button className="school-button secondary" onClick={() => onNavigate("Reports")}><Icon name="chart" size={17} />{t("View reports", "अहवाल पहा")}</button></PageHeading>
    <section className="school-welcome"><div><span className="welcome-kicker"><span />{t("LEARNING STARTS WITH SHOWING UP", "उपस्थितीपासून प्रगतीकडे")}</span><h2>{t("Every school day,", "प्रत्येक शालेय दिवस,")}<br /><em>{t("a new possibility.", "एक नवी संधी.")}</em></h2><p>{summary.pending ? t(`${summary.pending} students still need today's attendance recorded. Let's get the school day ready.`, `${summary.pending} विद्यार्थ्यांची आजची उपस्थिती नोंदवणे बाकी आहे. आजच्या कामाला सुरुवात करूया.`) : t("Your students, teachers and daily schoolwork. Thoughtfully brought together.", "विद्यार्थी, शिक्षक आणि दैनंदिन कामकाज — एकाच कार्यस्थानात.")}</p><div className="welcome-actions"><button className="school-button" onClick={() => onNavigate("Attendance")}><Icon name="calendar" size={17} />{t("Take attendance", "उपस्थिती नोंदवा")}<Icon name="arrow" size={16} /></button><button className="school-link" onClick={() => onNavigate("TeacherDashboard")}>{t("Teaching workspace", "शिक्षक कार्यस्थान")}<Icon name="arrow" size={16} /></button></div></div><CampusIllustration /></section>
    <section className="school-metrics" aria-label={t("School statistics", "शाळेची आकडेवारी")}>{[
      ["Students", t("Enrolled students", "नोंदणीकृत विद्यार्थी"), students.length, t(`${classes.length} classes & divisions`, `${classes.length} वर्ग व तुकड्या`), "users", "blue"],
      ["Teachers", t("Teaching staff", "शिक्षक वृंद"), teachers.length, t("Supporting every learner", "प्रत्येक विद्यार्थ्याला साथ"), "cap", "blue"],
      ["Attendance", t("Present today", "आज उपस्थित"), summary.present, t("From recorded attendance", "नोंदवलेल्या उपस्थितीनुसार"), "check", "green"],
      ["Attendance", t("Absent today", "आज अनुपस्थित"), summary.absent, t("Parent follow-up available", "पालक संपर्क उपलब्ध"), "message", "amber"],
    ].map(([key, label, count, detail, icon, tone]) => <button className="school-metric" key={label} onClick={() => onNavigate(key)}><span className={`metric-icon tone-${tone}`}><Icon name={icon} size={21} /></span><span className="metric-copy"><span>{label}</span><strong>{count.toLocaleString(language === "mr" ? "mr-IN" : "en-IN")}</strong><small>{detail}</small></span><Icon name="arrow" size={16} /></button>)}</section>
    <div className="dashboard-columns"><div className="dashboard-main-column">
      <Panel title={t("Today's attendance", "आजची उपस्थिती")} subtitle={t("A clear picture, class by class.", "प्रत्येक वर्गाचा स्पष्ट आढावा.")} action={<button className="school-link" onClick={() => onNavigate("Attendance")}>{t("Open register", "नोंदवही उघडा")}<Icon name="arrow" size={15} /></button>}>
        <div className="attendance-insight"><strong>{summary.rate === null ? "—" : `${summary.rate}%`}<span>{t("present in recorded entries", "नोंदवलेल्या विद्यार्थ्यांमध्ये उपस्थित")}</span></strong><div className="attendance-chart-legend">{[["present", t("Present", "उपस्थित"), summary.present], ["absent", t("Absent", "अनुपस्थित"), summary.absent], ["other", t("Other leave / duty", "रजा / इतर कार्य"), summary.other], ["pending", t("Unmarked", "नोंद बाकी"), summary.pending]].map(([tone, label, count]) => <span key={tone}><i className={tone} />{label}<b>{count}</b></span>)}</div></div>
        {classes.length ? <div className="class-attendance-list">{classes.slice(0, 6).map(group => { const members = students.filter(s => classKey(s) === group); const stats = attendanceSummary(members, attendance); return <button className="class-attendance-row" key={group} onClick={() => onNavigate("Attendance", { initialClass: members[0].className, initialDivision: members[0].division })}><span>{t("Class", "इयत्ता")} {group}</span><div className="attendance-stack" aria-label={`${stats.present} present, ${stats.absent} absent, ${stats.other} other, ${stats.pending} unmarked`}>{["present", "absent", "other", "pending"].map(key => <i key={key} className={key} style={{ width: `${stats[key] / stats.total * 100}%` }} />)}</div><strong>{stats.recorded}/{stats.total}</strong><Icon name="chevron" size={14} /></button>; })}</div> : <EmptyState icon="users" title={t("Your first class starts here", "पहिल्या वर्गाची सुरुवात इथून")} description={t("Add or import students to see class attendance.", "वर्गनिहाय उपस्थितीसाठी विद्यार्थी जोडा किंवा आयात करा.")} action={<button className="school-button secondary" onClick={() => onNavigate("Students", { mode: "import" })}><Icon name="upload" size={16} />{t("Import students", "विद्यार्थी आयात करा")}</button>} />}
        <div className="panel-footnote"><Icon name="clock" size={14} />{t(`${summary.recorded} of ${summary.total} entries recorded today.`, `आज ${summary.total} पैकी ${summary.recorded} उपस्थिती नोंदी जतन केल्या आहेत.`)}</div>
      </Panel>
      <section className="school-shortcuts" aria-label={t("Quick actions", "त्वरित कृती")}>{[["Homework", "book", "Homework", "गृहपाठ", "Plan the next lesson", "पुढील अभ्यासाचे नियोजन"], ["Results", "chart", "Exams & results", "परीक्षा व निकाल", "Follow student progress", "विद्यार्थ्यांची प्रगती पहा"], ["Certificates", "award", "Certificates", "प्रमाणपत्रे", "Prepare school documents", "शालेय कागदपत्रे तयार करा"], ["Trips", "pin", "Educational trips", "शैक्षणिक सहल", "Learning beyond class", "वर्गाबाहेरील शिक्षण"]].map(([key, icon, en, mr, subEn, subMr]) => <button key={key} onClick={() => onNavigate(key)}><Icon name={icon} size={24} /><strong>{t(en, mr)}</strong><span>{t(subEn, subMr)}</span><Icon name="arrow" size={15} /></button>)}</section>
      <Panel title={t("Learning in motion", "अभ्यासाची वाटचाल")} subtitle={t("Recently assigned homework", "अलीकडे दिलेला गृहपाठ")} action={<button className="school-link" onClick={() => onNavigate("Homework")}>{t("View all", "सर्व पहा")}<Icon name="arrow" size={15} /></button>}>
        {homework.length ? <div className="academic-records">{homework.slice(-3).reverse().map(item => <button key={item.id} onClick={() => onNavigate("Homework")}><span className="subject-symbol"><Icon name="book" /></span><span><strong>{item.subject || t("Homework", "गृहपाठ")}</strong><small>{t("Class", "इयत्ता")} {item.className} · {item.date || "—"}</small></span><p>{item.homework || item.description || item.content || ""}</p><Icon name="chevron" size={15} /></button>)}</div> : <EmptyState compact title={t("Ready for the next lesson", "पुढील अभ्यासासाठी सज्ज")} description={t("Published homework will appear here.", "जतन केलेला गृहपाठ येथे दिसेल.")} action={<button className="school-link" onClick={() => onNavigate("Homework")}>{t("Create homework", "गृहपाठ तयार करा")}<Icon name="plus" size={15} /></button>} />}
      </Panel>
    </div><aside className="dashboard-side-column"><AcademicCalendar events={calendar} onNavigate={onNavigate} />
      <Panel title={t("School noticeboard", "शालेय सूचना फलक")} action={<button className="icon-button" aria-label={t("View notices", "सूचना पहा")} onClick={() => onNavigate("Notices")}><Icon name="arrow" size={17} /></button>}>
        {notices.length ? <div className="school-notices">{notices.map(notice => <button key={notice.id} onClick={() => onNavigate("Notices")}><span className="notice-type">{notice["लक्ष्य वर्ग / गट"] || t("SCHOOL NOTICE", "शालेय सूचना")}</span><strong>{notice.title || notice["सूचना शीर्षक"] || t("School notice", "शालेय सूचना")}</strong><p>{notice.message || notice["संदेश"]}</p><small>{notice.date || notice["दिनांक"] || notice.createdAt}</small></button>)}</div> : <EmptyState compact icon="bell" title={t("All caught up", "सध्या नवीन सूचना नाहीत")} description={t("School announcements will appear here.", "शाळेच्या नवीन सूचना येथे दिसतील.")} />}
      </Panel>
    </aside></div>
  </div>;
}
