import {useEffect,useState} from 'react';
import {demoRequest} from '../backend/demoClient';
import {navigationItems} from '../design/navigation';
import {portalGroups} from '../design/portalNavigation';
const roles=['SUPER_ADMIN','ADMIN','HEADMASTER','TEACHER','CLASS_TEACHER','SPORTS_TEACHER','CLERK','ACCOUNTANT','LIBRARIAN','STAFF','VIEW_ONLY'];
const modules=[...new Set([...navigationItems.map(r=>r[0]),...portalGroups.flatMap(g=>g.items.map(i=>i.page))])].sort();
const blank=()=>({name:'',marathiName:'',employeeId:'',mobile:'',whatsapp:'',email:'',username:'',role:'TEACHER',assignedClass:'',division:'',academicYear:'2026-27',active:true,writeModules:['Attendance','Communications','Homework','Results'],modules:['Students','Attendance','Communications','Notices']});
const fields={name:'Full Name',marathiName:'Marathi Name',employeeId:'Employee ID',mobile:'Mobile Number',whatsapp:'WhatsApp Number',email:'Email',username:'Username',assignedClass:'Assigned Class',division:'Division',academicYear:'Academic Year'};
export default function DevelopmentUsers(){
 const [audit,setAudit]=useState(null),[users,setUsers]=useState([]),[form,setForm]=useState(null),[password,setPassword]=useState(''),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>setUsers((await demoRequest('users')).users);
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 const update=async(user,temporary='')=>{setBusy(true);try{await demoRequest('save-user',{user,password:temporary});await load();setForm(null);setPassword('');setMessage('Development account saved. Production Firebase is unchanged.');}catch(e){setMessage(e.message);}finally{setBusy(false);}};
 return <section className="school-panel workflow-panel"><h2>Users & Permissions</h2><p>DEVELOPMENT / TEST MODE. Individual accounts use the shared demo server. Passwords are salted and hashed on that server. OTP delivery requires a provider and is not enabled.</p>
 <button onClick={()=>demoRequest('audit').then(result=>setAudit(result.audit)).catch(error=>setMessage(error.message))}>View server audit history</button>{audit&&<details open><summary>Server audit history ({audit.length})</summary><div className="table-responsive"><table><thead><tr><th>Date / Time</th><th>User</th><th>Action</th><th>School</th><th>Registers</th></tr></thead><tbody>{audit.slice().reverse().map(entry=><tr key={entry.id}><td>{entry.at}</td><td>{entry.actorUid}</td><td>{entry.action}</td><td>{entry.schoolId}</td><td>{entry.changes.map(change=>change.module).join(", ")}</td></tr>)}</tbody></table></div></details>}<button onClick={()=>{setForm(blank());setPassword('');}}>+ Add User</button><label>Search users<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p role="status">{message}</p>
 {form&&<form onSubmit={e=>{e.preventDefault();void update(form,password);}}><h3>{form.uid?'Edit User':'Add User'}</h3><div className="form-grid">{Object.entries(fields).map(([key,label])=><label key={key}>{label}<input required={['name','username','email'].includes(key)} type={key==='email'?'email':'text'} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Temporary Password<input type="password" autoComplete="new-password" minLength={12} required={!form.uid} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Role<select aria-label="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Active</label></div><p>Leave password empty to preserve it when editing. Enter a new temporary password to reset a demo staff account. Minimum 12 characters.</p><fieldset><legend>Permitted modules</legend>{modules.map(module=><label key={module} style={{display:'inline-block',margin:8}}><input type="checkbox" checked={form.modules.includes(module)} onChange={e=>setForm({...form,modules:e.target.checked?[...form.modules,module]:form.modules.filter(m=>m!==module)})}/>{module}</label>)}</fieldset><fieldset><legend>Create / Edit / Delete permission (in addition to module access)</legend>{modules.map(module=><label key={module} style={{display:'inline-block',margin:8}}><input type="checkbox" checked={(form.writeModules||[]).includes(module)} onChange={e=>setForm({...form,writeModules:e.target.checked?[...(form.writeModules||[]),module]:(form.writeModules||[]).filter(m=>m!==module)})}/>{module}</label>)}</fieldset><fieldset><legend>Student actions (requires Students module write access)</legend>{['add','edit','archive','restore'].map(action=><label key={action} style={{display:'inline-block',margin:8}}><input type="checkbox" checked={(form.studentActions??['add','edit','archive','restore']).includes(action)} onChange={e=>{const current=form.studentActions??['add','edit','archive','restore'];setForm({...form,studentActions:e.target.checked?[...current,action]:current.filter(value=>value!==action)});}}/>{action}</label>)}<p>Permanent deletion is restricted to privileged administrators.</p></fieldset><button disabled={busy}>Save User</button><button type="button" onClick={()=>{setForm(null);setPassword('');}}>Cancel</button></form>}
 <div className="table-responsive"><table><thead><tr><th>Name</th><th>Username / Email</th><th>Role</th><th>Class / Division / Year</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.filter(u=>[u.name,u.email,u.username,u.employeeId].join(' ').toLowerCase().includes(query.toLowerCase())).map(u=><tr key={u.uid}><td>{u.name}<br/>{u.marathiName}</td><td>{u.username}<br/>{u.email}</td><td>{u.role}</td><td>{u.assignedClass} / {u.division} / {u.academicYear}</td><td>{u.archived?'Archived':u.active?'Active':'Inactive'}</td><td>{u.uid==='development-admin'?'Protected demo owner':<><button onClick={()=>{setForm(u);setPassword('');}}>Edit / Permissions</button><button disabled={busy} onClick={()=>update({...u,active:!u.active})}>{u.active?'Disable':'Activate'}</button><button onClick={()=>{setForm(u);setPassword('');setMessage('Enter a new temporary password and Save User.');}}>Reset Password</button><button disabled={busy} onClick={()=>{if(confirm(u.archived?'Restore this demo user?':'Archive this demo user?'))update({...u,archived:!u.archived,active:false});}}>{u.archived?'Restore':'Archive'}</button></>}</td></tr>)}</tbody></table></div></section>;
}
