import { notify } from "../components/Feedback";
import { useState } from "react";
import { readStored, useStoredState } from "../storage";

export default function Library() {
  const students = readStored("erp_pro_students", []);
  const [books, setBooks] = useStoredState("erp_pro_library_books", []);
  const [loans, setLoans] = useStoredState("erp_pro_library_loans", []);
  const [form, setForm] = useState({ bookId: "", name: "", author: "", copies: "", shelf: "" });
  const [loan, setLoan] = useState({ student: "", bookId: "", dueDate: "" });
  const [query, setQuery] = useState("");
  const addBook = () => { if (!form.bookId.trim() || !form.name.trim()) { notify("Book ID आणि पुस्तकाचे नाव भरा"); return; } if (!setBooks([...books, { id: crypto.randomUUID(), ...form }])) return; setForm({ bookId: "", name: "", author: "", copies: "", shelf: "" }); notify("पुस्तक नोंद जतन झाली"); };
  const issue = () => { if (!loan.student || !loan.bookId || !loan.dueDate) { notify("विद्यार्थी, पुस्तक आणि due date निवडा"); return; } if (!setLoans([...loans, { id: crypto.randomUUID(), ...loan, issueDate: new Date().toISOString().slice(0, 10), returned: false }])) return; setLoan({ student: "", bookId: "", dueDate: "" }); notify("पुस्तक issue झाले"); };
  const returned = (id) => setLoans(loans.map((item) => item.id === id ? { ...item, returned: true, returnDate: new Date().toISOString().slice(0, 10) } : item));
  const visibleBooks = books.filter((book) => Object.values(book).join(" ").toLowerCase().includes(query.toLowerCase()));
  return <div className="page module-page"><div className="module-heading"><div><span className="eyebrow">READING CULTURE</span><h2>ग्रंथालय</h2><p>पुस्तक master, issue/return आणि overdue history.</p></div><div className="module-count">{books.length}<span>पुस्तके</span></div></div><section className="workflow-panel"><div className="panel-title"><h3>Book Master</h3><span>Barcode/QR साठी Book ID तयार ठेवा</span></div><div className="form-grid">{[["Book ID","bookId"],["पुस्तकाचे नाव","name"],["लेखक","author"],["Available Copies","copies"],["Shelf / Rack","shelf"]].map(([label,key]) => <label key={key}>{label}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><button onClick={addBook}>पुस्तक जतन करा</button></section><section className="workflow-panel"><div className="panel-title"><h3>Book Issue</h3><span>परत आलेल्या पुस्तकाला Return करा</span></div><div className="form-grid"><label>विद्यार्थी<select value={loan.student} onChange={(event) => setLoan({ ...loan, student: event.target.value })}><option value="">विद्यार्थी निवडा</option>{students.map((student) => <option key={student.id} value={student.name}>{student.name} · {student.grNo}</option>)}</select></label><label>पुस्तक<select value={loan.bookId} onChange={(event) => setLoan({ ...loan, bookId: event.target.value })}><option value="">पुस्तक निवडा</option>{books.map((book) => <option key={book.id} value={book.bookId}>{book.name} · {book.bookId}</option>)}</select></label><label>Due Date<input type="date" value={loan.dueDate} onChange={(event) => setLoan({ ...loan, dueDate: event.target.value })} /></label></div><button onClick={issue}>पुस्तक Issue करा</button></section><input className="module-search" aria-label="पुस्तक शोधा" placeholder="Book ID, नाव किंवा लेखक शोधा" value={query} onChange={(event) => setQuery(event.target.value)} />{visibleBooks.length ? <div className="record-grid">{visibleBooks.map((book) => <article className="record-card text-record" key={book.id}><div className="record-card-body"><span className="record-kicker">{book.bookId} · {book.shelf || "Shelf नोंद नाही"}</span><h3>{book.name}</h3><p>{book.author || "लेखक नोंद नाही"} · Copies {book.copies || "-"}</p></div></article>)}</div> : <div className="empty-state"><strong>पुस्तक नोंदी उपलब्ध नाहीत</strong><span>Book Masterमध्ये पहिली नोंद तयार करा.</span></div>}<div className="workflow-panel"><div className="panel-title"><h3>Issue History</h3><span>{loans.filter((item) => !item.returned).length} active loans</span></div>{loans.length ? loans.slice().reverse().map((item) => <div className="activity-row" key={item.id}><strong>{item.student}</strong><span>{item.bookId} · Due {item.dueDate} · {item.returned ? `Returned ${item.returnDate}` : <button onClick={() => returned(item.id)}>Return</button>}</span></div>) : <div className="empty-state"><strong>Issue history रिकामी आहे</strong></div>}</div></div>;
}
