import {lifecycleActive} from '../services/studentLifecycle';
import { useLanguage } from "../design/language";
import StudentLookup from "../components/StudentLookup";
import { useState } from "react";
import { readStored, useStoredState, localDate } from "../storage";
import { availableUnits, validateLoan } from "../services/lending";
import { exportRows } from "../services/excel";
import { PageHeading, EmptyState } from "../design/SchoolUI";
import { notify } from "../components/Feedback";
import {queueMessages} from "../services/messageStore";
import {renderMessage,defaultWorkflow} from "../services/messageWorkflow";
import { qrImage } from "../qr";

export default function Library({onNavigate}) {
  const { t } = useLanguage();
  const students = readStored("erp_pro_students", []).filter(s => lifecycleActive(s));
  const [books, saveBooks] = useStoredState("erp_pro_library_books", []), [loans, saveLoans] = useStoredState("erp_pro_library_loans", []);
  const [form, setForm] = useState({ bookId: "", name: "", author: "", copies: "1", shelf: "" }), [loan, setLoan] = useState({ studentId: "", itemRef: "", quantity: "1", dueDate: "" }), [query, setQuery] = useState(""), [studentFilter, setStudentFilter] = useState(""), [fineRate, setFineRate] = useState("0");
  const legacy = readStored("erp_pro_library", []).map(item => ({ id: `legacy:${item.id}`, bookId: item["Book ID"], name: item["पुस्तकाचे नाव"], author: item["लेखक"], copies: Number(item["Available Copies"] || 0), shelf: item["Shelf / Rack"], legacy: true }));
  const catalog = [...books, ...legacy];
  const normalizedLoans = loans.map(l => ({ ...l, itemRef: l.itemRef || l.bookRef || (catalog.filter(b => b.bookId === l.bookId).length === 1 ? catalog.find(b => b.bookId === l.bookId).id : "unresolved") }));
  const available = book => availableUnits(book, normalizedLoans, book.id);
  const addBook = () => {
    if (!form.bookId.trim() || !form.name.trim() || !Number.isInteger(Number(form.copies)) || Number(form.copies) <= 0) return notify("Book ID, title and positive whole-number copies are required.");
    if (catalog.some(b => String(b.bookId).toLowerCase() === form.bookId.trim().toLowerCase())) return notify("Book ID already exists in a catalog.");
    if (saveBooks([...books, { ...form, bookId: form.bookId.trim(), copies: Number(form.copies), id: crypto.randomUUID() }])) setForm({ bookId: "", name: "", author: "", copies: "1", shelf: "" });
  };
  const issue = () => {
    const book = catalog.find(b => b.id === loan.itemRef), student = students.find(s => s.id === loan.studentId);
    const error = validateLoan(loan, book ? available(book) : 0, localDate()); if (error || !student) return notify(error || "Choose an active student.");
    if (saveLoans([...loans, { ...loan, id: crypto.randomUUID(), bookId: book.bookId, bookName: book.name, student: student.name, grNo: student.grNo, quantity: Number(loan.quantity), issueDate: localDate(), returned: false }])) { setLoan({ studentId: "", itemRef: "", quantity: "1", dueDate: "" }); notify("Book issued.");try{queueMessages([{type:"Library Issue",studentId:student.id,key:`library-issue:${readStored("erp_pro_library_loans",[]).at(-1).id}`,details:{Book:book.name,"Due Date":loan.dueDate}}])}catch(e){notify(e.message)} }
  };
  const returned = id => {const l=loans.find(l=>l.id===id);if(!l||l.returned)return;if(saveLoans(loans.map(l => l.id === id ? { ...l, returned: true, returnDate: localDate() } : l)))try{queueMessages([{type:"Library Return",studentId:l.studentId,key:`library-return:${id}`,details:{Book:l.bookName||l.bookId}}])}catch(e){notify(e.message)}};
  const visible = catalog.filter(b => Object.values(b).join(" ").toLowerCase().includes(query.toLowerCase())), history = loans.filter(l => !studentFilter || l.studentId === studentFilter);
  return <div className="core-page"><PageHeading eyebrow="A CULTURE OF READING" title="School library" description="Books, borrowers and the next good read. Both existing catalogs remain available without migration." /><StudentLookup students={students} onSelect={s => setLoan({ ...loan, studentId: s.id })} /><section className="school-panel workflow-panel"><h3>Book Master</h3><div className="form-grid">{[["Book ID / Barcode", "bookId"], ["Book title", "name"], ["Author", "author"], ["Total Copies", "copies"], ["Shelf / Rack", "shelf"]].map(([label, key]) => <label key={key}>{t(label)}<input type={key === "copies" ? "number" : "text"} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}</div><button onClick={addBook}>{t("Save book")}</button></section>
    <section className="school-panel workflow-panel"><h3>{t("Issue book")}</h3><div className="form-grid"><label>{t("Student")}<select aria-label="Student" value={loan.studentId} onChange={e => setLoan({ ...loan, studentId: e.target.value })}><option value="">Select student</option>{students.map(s => <option key={s.id} value={s.id}>{s.name} · {s.grNo}</option>)}</select></label><label>{t("Book")}<select aria-label="Book" value={loan.itemRef} onChange={e => setLoan({ ...loan, itemRef: e.target.value })}><option value="">Select book</option>{catalog.map(b => <option key={b.id} value={b.id}>{b.bookId} · {b.name} ({available(b)} available){b.legacy ? " · original catalog" : ""}</option>)}</select></label><label>{t("Quantity")}<input type="number" value={loan.quantity} onChange={e => setLoan({ ...loan, quantity: e.target.value })} /></label><label>{t("Due Date")}<input type="date" value={loan.dueDate} onChange={e => setLoan({ ...loan, dueDate: e.target.value })} /></label></div><button onClick={issue}>{t("Issue book")}</button></section>
    <div className="domain-toolbar"><label>Search book / barcode<input value={query} onChange={e => setQuery(e.target.value)} /></label><button onClick={() => exportRows(visible.map(b => ({ ...b, available: available(b) })), "library-books.xlsx")}>Export books</button><button onClick={() => exportRows(history, "library-loans.csv")}>Export loans CSV</button></div>{visible.length ? <div className="record-grid">{visible.map(b => <article className="school-panel workflow-panel" key={b.id}><h3>{b.name}</h3><p>{b.author} · {b.bookId} · {b.shelf}</p><p>{available(b)} / {b.copies} available {b.legacy ? "· Original catalog (preserved)" : ""}</p><img src={qrImage(`schoolerp:book:v1:${encodeURIComponent(b.id)}`)} alt={`Book reference ${b.bookId}`} width="70" height="70" /></article>)}</div> : <EmptyState icon="book" title="A library full of possibility" description="Register a book to begin lending, or clear your search." />}
    <section className="school-panel workflow-panel"><h3>Student-wise issue / return history</h3><div className="domain-toolbar"><label>Student filter<select aria-label="Student filter" value={studentFilter} onChange={e => setStudentFilter(e.target.value)}><option value="">All / legacy loans</option>{students.map(s => <option key={s.id} value={s.id}>{s.name} · {s.grNo}</option>)}</select></label><label>Fine estimate per overdue day (₹)<input type="number" min="0" value={fineRate} onChange={e => setFineRate(e.target.value)} /></label></div><p>Fine is an estimate, not a payment record. Legacy name-only loans remain visible in All; they are never guessed into a student account.</p>{history.length ? <div className="table-scroll"><table><thead><tr><th>{t("Student")}</th><th>{t("Book")}</th><th>Issue / due</th><th>Overdue / fine estimate</th><th>Return</th></tr></thead><tbody>{history.map(l => { const days = Math.max(0, Math.floor((Date.parse(l.returnDate || localDate()) - Date.parse(l.dueDate)) / 86400000)) || 0; return <tr key={l.id}><td>{l.student} · {l.grNo || "Legacy name-only"}</td><td>{l.bookId}</td><td>{l.issueDate} / {l.dueDate}</td><td>{days} days · ₹{(days * Math.max(0, Number(fineRate) || 0)).toFixed(2)}</td><td><button onClick={()=>{const s=students.find(s=>s.id===l.studentId);if(!s)return notify("Resolve this legacy loan to a student first.");onNavigate("Communications",{initialStudentIds:[s.id],initialMessage:renderMessage(l.returned?"Library Return":"Library Issue",s,{Book:l.bookName||l.bookId,"Due Date":l.dueDate},readStored("erp_pro_message_settings",defaultWorkflow))})}}>Prepare parent message</button>{l.returned ? l.returnDate : <button onClick={() => returned(l.id)}>{t("Return book")}</button>}</td></tr>; })}</tbody></table></div> : <p>No lending history for this selection.</p>}</section></div>;
}
