import FamilyContactCard from "../components/FamilyContactCard";
import {useContext} from "react";
import {CommunicationSession} from "../backend/CommunicationSession";
import {prepareLongAbsenceAlerts} from '../services/longAbsenceStore';
import {useEffect,useState} from 'react';
import {readStored,useStoredState,localDate,writeStored} from '../storage';
import {absenceStats,lifecycleActive,longAbsenceText,yearStart} from '../services/studentLifecycle';
import {parentContacts,communicationLink,communicationRecord,communicationKeys} from '../services/absenceCommunication';
import {defaultWorkflow} from '../services/messageWorkflow';
import {exportRows} from '../services/excel';
import {notify} from '../components/Feedback';
import AudioRecorder from '../components/AudioRecorder';
import AssetLink from '../components/AssetLink';
import {saveAsset} from '../services/assets';
import {PageHeading,Avatar} from '../design/SchoolUI';

const followups=['Not Contacted','Parent Contacted','No Answer','Medical Reason','Family Reason','Out of Station','At Risk of Dropout','Returned to School','Follow-up Required'];
const defaults={enabled:false,thresholds:'1,3,5,7',language:'en',parent:true,staff:true,audio:null};
export default function LongAbsence({onNavigate}){
 const actor=useContext(CommunicationSession);
 const [settings,saveSettings]=useStoredState('erp_pro_long_absence_settings',defaults),[form,setForm]=useState(settings),[date,setDate]=useState(localDate()),[minimum,setMinimum]=useState(1),[contacts,setContacts]=useState({}),[drafts,setDrafts]=useState({}),[followup,saveFollowup]=useStoredState('erp_pro_long_absence_followups',{}),[alerts,,reloadAlerts]=useStoredState('erp_pro_long_absence_alerts',[]);
 const attendance=readStored('erp_pro_attendance',{}),students=readStored('erp_pro_students',[]).filter(lifecycleActive);
 const rows=students.map(s=>({s,stats:absenceStats(s,attendance,date,yearStart(s.academicYear)?`${yearStart(s.academicYear)}-06-01`:`${date.slice(0,4)}-01-01`)})).filter(r=>r.stats.consecutive>=Number(minimum));
 const contact=s=>{const cs=parentContacts(s).filter(c=>c.mobile);return cs.find(c=>c.id===contacts[s.id])||cs[0]};
 const message=(s,stats)=>drafts[s.id]??longAbsenceText(s,stats.consecutive,form.language);
 useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 const save=()=>{const days=form.thresholds.split(',').map(Number);if(!days.length||days.some(n=>!Number.isInteger(n)||n<1||n>366))return notify('Enter comma-separated whole days between 1 and 366.');if(saveSettings(form))notify('Absence alert rules saved. Local alert preparation only; provider delivery is not connected.')};
 const prepare=()=>{try{prepareLongAbsenceAlerts(date);reloadAlerts();notify('Local alerts prepared. No provider sending performed.')}catch(e){notify(e.message)}};
 const record=(e,s,stats,channel)=>{const current=readStored('erp_pro_students',[]).find(i=>i.id===s.id),c=contact(s),enabled=channel==='call'||readStored('erp_pro_message_settings',defaultWorkflow).channels.some(v=>v.id===channel&&v.enabled);if(!actor?.uid||!enabled||!current||!lifecycleActive(current)||!c||!parentContacts(current).some(v=>v.id===c.id&&v.mobile===c.mobile)||JSON.stringify(readStored('erp_pro_attendance',{}))!==JSON.stringify(attendance)){e.preventDefault();notify('Contact, attendance or channel changed. Reopen this panel.');return;}const log=communicationRecord(current,c,date,channel,actor.uid,{source:'Long absence',message:message(s,stats),status:channel==='call'?'Call Initiated':'Manual',failureReason:'Device action; delivery unverified'});if(!writeStored(communicationKeys.history,[...readStored(communicationKeys.history,[]),log]))e.preventDefault();};
 const speak=text=>{if(!window.speechSynthesis||!window.SpeechSynthesisUtterance)return notify('Speech preview is not supported. Record or upload audio instead.');window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=form.language==='mr'?'mr-IN':'en-IN';window.speechSynthesis.speak(utterance)};
 const exported=rows.map(({s,stats})=>({studentId:s.id,name:s.name,gr:s.grNo,class:s.className,division:s.division,...stats,followup:followup[s.id]?.status||'Not Contacted'}));
 return <div className="core-page"><PageHeading eyebrow="ATTENDANCE FOLLOW-UP" title="Long Absent Students" description="Recorded school-day absence streaks, parent contact and staff follow-up in one place."/><p>Only saved attendance is counted. A date with attendance for other students but no mark for this student breaks the streak. Dates with no register are skipped, so holidays are not invented as absences. Year totals use the student's June–May academic year; missing academic years use the calendar year.</p>
 <section className="school-panel workflow-panel"><div className="form-grid"><label>As of date<input type="date" max={localDate()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Minimum consecutive days<input type="number" min="1" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label>Message language<select aria-label="Message language" value={form.language} onChange={e=>{setForm({...form,language:e.target.value});setDrafts({})}}><option value="en">English</option><option value="mr">Marathi</option></select></label></div><div className="import-actions"><button onClick={()=>exportRows(exported,'long-absent.xlsx')}>Export Excel</button><button onClick={()=>exportRows(exported,'long-absent.csv')}>Export CSV</button><button onClick={()=>window.print()}>Print / PDF</button><button onClick={()=>onNavigate('Lifecycle')}>Student Lifecycle</button></div></section>
 <section className="school-panel workflow-panel"><h2>{rows.length} students needing review</h2>{rows.map(({s,stats})=><article key={s.id} className="school-panel workflow-panel"><Avatar name={s.name} photo={s.photo}/><h3>{s.name} · {s.className}/{s.division}</h3><p>Absent today: {stats.absentToday?'Yes':'No / unmarked'} · Consecutive: {stats.consecutive} · Month: {stats.month} · Year: {stats.year} · Last present: {stats.lastPresent||'Not recorded'}</p><FamilyContactCard student={s} date={date} message={message(s,stats)} onNavigate={onNavigate}/><label>Parent contact<select aria-label={`Parent contact ${s.name}`} value={contact(s)?.id||''} onChange={e=>setContacts({...contacts,[s.id]:e.target.value})}>{parentContacts(s).filter(c=>c.mobile).map(c=><option key={c.id} value={c.id}>{c.label} · {c.name} · ••••••{c.mobile.slice(-4)}</option>)}</select></label><label>Editable absence message<textarea aria-label={`Absence message ${s.name}`} value={message(s,stats)} onChange={e=>setDrafts({...drafts,[s.id]:e.target.value})}/></label><div className="import-actions">{[['whatsapp','WhatsApp'],['sms','SMS'],['call','Call Parent']].map(([channel,label])=><a key={channel} className="school-button secondary" href={communicationLink(channel,contact(s)?.mobile,message(s,stats),navigator.userAgent)||undefined} onClick={e=>record(e,s,stats,channel)} target={channel==='whatsapp'?'_blank':undefined} rel="noopener noreferrer">{label}</a>)}<button onClick={()=>onNavigate('Communications',{initialStudentIds:[s.id],initialMessage:message(s,stats),audioAsset:form.audio})}>Audio / communication history</button><button onClick={()=>speak(message(s,stats))}>Text-to-speech preview</button><button onClick={()=>window.speechSynthesis?.cancel()}>Stop speech</button></div><label>Follow-up status<select aria-label="Follow-up status" value={followup[s.id]?.status||'Not Contacted'} onChange={e=>saveFollowup({...followup,[s.id]:{status:e.target.value,updatedAt:new Date().toISOString(),actor:'local-review'}})}>{followups.map(v=><option key={v}>{v}</option>)}</select></label></article>)}{!rows.length&&<p>No matching recorded absence streaks.</p>}</section>
 <section className="school-panel workflow-panel"><h2>Absence alert rules and audio template</h2><label><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enable local absence alerts</label><label>Threshold days<input value={form.thresholds} onChange={e=>setForm({...form,thresholds:e.target.value})}/></label><label><input type="checkbox" checked={form.parent} onChange={e=>setForm({...form,parent:e.target.checked})}/>Prepare parent alert</label><label><input type="checkbox" checked={form.staff} onChange={e=>setForm({...form,staff:e.target.checked})}/>Prepare staff alert (5+: teacher; 7+: headmaster/admin)</label><AudioRecorder onRecorded={audio=>setForm({...form,audio})}/><label>Upload recorded template<input type="file" accept="audio/*" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setForm({...form,audio:await saveAsset(file,true)})}catch(err){notify(err.message)}}}/></label><AssetLink asset={form.audio}/><p>Speech preview uses the device's installed voice; Marathi voice availability varies. It does not produce a shareable audio file. Use Record Audio or upload for sending. Server text-to-speech and automatic parent/staff delivery require approved services.</p><button onClick={save}>Save absence alert rules</button><button onClick={prepare}>Prepare absence alerts</button><h3>Prepared alerts ({alerts.length})</h3>{alerts.slice().reverse().map(a=><p key={a.id}>{a.date} · {students.find(s=>s.id===a.studentId)?.name||a.studentId} · {a.days} days · {a.parent?'Parent; ':''}{a.staff} · {a.status}</p>)}</section></div>;
}
