import {useState} from 'react';
import {developmentEnabled,developmentAccept} from '@development-auth';
import App from '../App';
import {navigationItems} from '../design/navigation';

const empty=()=>({udise:'',schoolNameEn:'',schoolNameMr:'',institutionName:'',institutionNameMr:'',schoolType:'Secondary',medium:'Marathi',address:'',district:'',taluka:'',state:'Maharashtra',pin:'',email:'',mobile:'',logo:'',institutionLogo:'',academicYear:'2026-27',subscriptionStatus:'DEVELOPMENT',softwareVersion:'1.0.0-demo-test',modules:['*']});
const labels={udise:'UDISE Number',schoolNameEn:'School Name English',schoolNameMr:'School Name Marathi',institutionName:'Institution / Trust English',institutionNameMr:'Institution / Trust Marathi',schoolType:'School Type',medium:'Medium',address:'Address',district:'District',taluka:'Taluka',state:'State',pin:'PIN Code',email:'School Email',mobile:'School Mobile',academicYear:'Academic Year',subscriptionStatus:'Subscription Status',softwareVersion:'Software Version'};
export default function PerfectEduPlatform(){
 const [schoolOpen,setSchoolOpen]=useState(false);
 const [token,setToken]=useState(''),[schools,setSchools]=useState([]),[audit,setAudit]=useState([]),[query,setQuery]=useState(''),[form,setForm]=useState(null),[selected,setSelected]=useState(null),[users,setUsers]=useState([]),[user,setUser]=useState({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function request(action,body={},access=token){const response=await fetch('/__school_demo/'+action,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+access},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error);return result;}
 async function refresh(access=token){const result=await request('platform-schools',{},access);setSchools(result.schools);setAudit(result.audit);}
 async function run(action){setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function admins(school){setSelected(school);setUser({name:'',email:'',username:'admin',active:true});setUsers((await request('platform-school-users',{schoolId:school.id})).users.filter(u=>u.uid!=='development-admin'));}
 async function image(event,key){const file=event.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setMessage('Use a PNG, JPEG or WebP image up to 2 MB.');return;}const reader=new FileReader();reader.onload=()=>setForm(f=>({...f,[key]:reader.result}));reader.readAsDataURL(file);}
 if(schoolOpen)return <App/>;
 return <main className="perfectedu-platform"><header><a href="/">PerfectEdu</a><span>Platform Administration</span><a href="/login">School Login</a></header><p>www.perfectedu.co.in · {developmentEnabled?'DEVELOPMENT / TEST MODE':'Production platform activation required'}</p><h1>Schools & Permissions</h1><p role="alert">{message}</p>
 {!developmentEnabled?<p>Production platform authentication is not configured. Existing Firebase authentication has not been changed.</p>:!token?<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);run(async()=>{const result=await request('platform-login',Object.fromEntries(data));setToken(result.token);await refresh(result.token);});}}><label>Platform User ID<input name="username" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>Platform Login</button></form>:<>
 <button onClick={()=>run(async()=>{await request('logout');setToken('');setSchools([]);setSelected(null);})}>Logout</button><button onClick={()=>{setForm(empty());setSelected(null);}}>Add New School</button><label>Search school name / UDISE<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p>Active: {schools.filter(s=>s.status==='ACTIVE').length} · Inactive / suspended: {schools.filter(s=>s.status!=='ACTIVE').length}</p>
 {form&&<form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await request('platform-save-school',{school:form});setForm(null);await refresh();await admins(result.school);setMessage('School saved. Create its Master Admin, enable modules, then activate it.');});}}><h2>{form.id?'Edit School':'Add New School'}</h2><div className="form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input value={form[key]||''} required={['udise','schoolNameEn','academicYear'].includes(key)} readOnly={key==='udise'&&!!form.id&&!!schools.find(s=>s.id===form.id)?.udise} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{['logo','institutionLogo'].map(key=><label key={key}>{key==='logo'?'School Logo':'Institution Logo'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>image(e,key)}/>{form[key]&&<img alt={key} src={form[key]} width="60"/>}</label>)}</div><fieldset><legend>Enabled modules</legend><label><input type="checkbox" checked={form.modules.includes('*')} onChange={e=>setForm({...form,modules:e.target.checked?['*']:[]})}/>All modules</label>{!form.modules.includes('*')&&navigationItems.map(([key,label])=><label key={key}><input type="checkbox" checked={form.modules.includes(key)} onChange={e=>setForm({...form,modules:e.target.checked?[...form.modules,key]:form.modules.filter(m=>m!==key)})}/>{typeof label==='string'?label:key}</label>)}</fieldset><button disabled={busy}>Save School</button><button type="button" onClick={()=>setForm(null)}>Cancel</button></form>}
 <div className="table-responsive"><table><thead><tr><th>UDISE / School</th><th>Status</th><th>Students / Staff</th><th>Storage</th><th>Subscription</th><th>Actions</th></tr></thead><tbody>{schools.filter(s=>[s.udise,s.schoolNameEn,s.schoolNameMr].join(' ').toLowerCase().includes(query.toLowerCase())).map(s=><tr key={s.id}><td>{s.udise||'UDISE awaiting verification'}<br/>{s.schoolNameEn||s.schoolNameMr}<small>{s.id}</small></td><td>{s.status}</td><td>{s.studentCount} / {s.staffCount}</td><td>{s.storageBytes} bytes</td><td>{s.subscriptionStatus}</td><td><button onClick={()=>run(async()=>{const result=await request('platform-enter-school',{schoolId:s.id});developmentAccept(result);history.replaceState(null,'','/school');setSchoolOpen(true);})}>Open School</button><button onClick={()=>setForm({...empty(),...s})}>Edit School</button><button onClick={()=>run(()=>admins(s))}>School Admins</button>{['ACTIVE','SUSPENDED','ARCHIVED'].map(status=><button key={status} disabled={busy||s.status===status} onClick={()=>run(async()=>{await request('platform-school-status',{schoolId:s.id,status});await refresh();})}>{status==='ACTIVE'?'Activate':status==='SUSPENDED'?'Suspend':'Archive'}</button>)}</td></tr>)}</tbody></table></div>
 {selected&&<section><h2>School Master Admin — {selected.schoolNameEn||selected.schoolNameMr}</h2><p>Tenant: {selected.id} · UDISE: {selected.udise}</p><form onSubmit={e=>{e.preventDefault();const element=e.currentTarget,password=new FormData(element).get('temporary');run(async()=>{await request('platform-save-admin',{schoolId:selected.id,user,password});element.reset();await admins(selected);setMessage('School Admin saved. Password was hashed by the backend.');});}}>{['name','email','username','mobile'].map(key=><label key={key}>{key}<input aria-label={'Admin '+key} value={user[key]||''} required={key!=='mobile'} onChange={e=>setUser({...user,[key]:e.target.value})}/></label>)}<label>Temporary Password<input name="temporary" type="password" minLength={12} required={!user.uid} autoComplete="new-password"/></label><p>Leave blank when editing to keep the current password. Set a new value to reset this school account.</p><button disabled={busy}>Save Master Admin</button></form>{users.map(u=><p key={u.uid}>{u.name} · {u.email} · {u.role}<button onClick={()=>setUser(u)}>Edit / Reset Access</button></p>)}</section>}
 <h2>Platform audit log</h2><ul>{audit.slice(-50).reverse().map((row,i)=><li key={row.id||i}>{row.at} · {row.action} · {row.schoolId}</li>)}</ul></>}
 </main>;
}
