import {useState} from 'react';
import {useLanguage} from '../design/language';
import Icon from '../components/Icon';
import './perfectedu-home.css';

const features=[
 ['users','Student management','विद्यार्थी व्यवस्थापन','Admission, profiles, classes and academic years.','प्रवेश, विद्यार्थी माहिती, वर्ग आणि शैक्षणिक वर्ष.'],
 ['calendar','Attendance','उपस्थिती व्यवस्थापन','Daily registers, leave and attendance history.','दैनंदिन उपस्थिती, रजा आणि उपस्थिती इतिहास.'],
 ['message','Parent communication','पालक संवाद','Prepared messages, calls and contact history.','तयार संदेश, फोन आणि संवाद इतिहास.'],
 ['badge','Teachers & staff','शिक्षक व कर्मचारी','Staff profiles, attendance and permissions.','कर्मचारी माहिती, उपस्थिती आणि परवानग्या.'],
 ['file','Fees & receipts','फी व्यवस्थापन','Collections, receipts and outstanding dues.','फी संकलन, पावत्या आणि थकबाकी.'],
 ['chart','Results & marksheets','निकाल व गुणपत्रिका','Marks, progress reports and report cards.','गुण, प्रगती अहवाल आणि गुणपत्रिका.'],
 ['award','Certificates','प्रमाणपत्रे','Bonafide, leaving and admission documents.','बोनाफाईड, शाळा सोडल्याचा दाखला आणि प्रवेश कागदपत्रे.'],
 ['book','Library','ग्रंथालय व्यवस्थापन','Book issue, returns and due records.','पुस्तक वाटप, परतावा आणि मुदत नोंदी.'],
 ['award','Sports','क्रीडा व्यवस्थापन','Participation, equipment and issue records.','सहभाग, क्रीडा साहित्य आणि वाटप नोंदी.'],
 ['bus','Educational trips','शैक्षणिक सहली','Student lists, permissions and parent contact.','विद्यार्थी यादी, परवानगी आणि पालक संपर्क.'],
 ['badge','Identity cards','ओळखपत्रे','School identity cards from student records.','विद्यार्थी माहितीवरून शाळेची ओळखपत्रे.'],
 ['upload','Excel import','एक्सेल आयात','Bulk records, validation and photo mapping.','एकत्रित माहिती, पडताळणी आणि फोटो जुळवणी.']
];
const documents=[['Admission form','प्रवेश अर्ज'],['Bonafide certificate','बोनाफाईड प्रमाणपत्र'],['Leaving certificate','शाळा सोडल्याचा दाखला'],['Progress card','प्रगती पत्रक'],['Marksheet','गुणपत्रिका'],['ID card','ओळखपत्र'],['Student register','विद्यार्थी नोंदवही'],['Attendance reports','उपस्थिती अहवाल'],['School forms','शाळेचे इतर अर्ज']];
export default function PerfectEduHome(){
 const {t,language,setLanguage}=useLanguage();
 const [menu,setMenu]=useState(false);
 const nav=[['home','Home','मुख्यपृष्ठ'],['about','About PerfectEdu','परिचय'],['features','Features','वैशिष्ट्ये'],['modules','Modules','विभाग'],['schools','For Schools','शाळांसाठी'],['mobile','Mobile App','मोबाईल ॲप'],['support','Support','मदत'],['contact','Contact','संपर्क']];
 const heading=(eyebrow,en,mr)=><><p className="pe-eyebrow">{eyebrow}</p><h2>{t(en,mr)}</h2></>;
 const login=<a className="pe-button" href="/login">{t('School Login','शाळा प्रवेश करा')}<Icon name="arrow"/></a>;
 const tags=items=><div className="pe-tags">{items.map(([en,mr])=><span key={en}>{t(en,mr)}</span>)}</div>;
 return <div className="pe-home" id="home">
  <a className="pe-skip" href="#pe-content">{t('Skip to content','मुख्य मजकुराकडे जा')}</a>
  <div className="pe-topline">{t('Designed for schools. Built around people.','शाळांसाठी विकसित. माणसांना जोडणारी व्यवस्था.')}<span>मराठी + English</span></div>
  <header className="pe-header"><a href="/" className="pe-brand" aria-label="PerfectEdu home"><span className="pe-mark"><Icon name="cap"/></span><span>Perfect<span className="pe-teal">Edu</span><small>SCHOOL MANAGEMENT PLATFORM</small></span></a><button className="pe-menu" aria-label={t('Toggle navigation','नेव्हिगेशन उघडा')} aria-expanded={menu} aria-controls="pe-nav" onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></button><nav id="pe-nav" className={menu?'pe-nav is-open':'pe-nav'} aria-label="Main navigation" onKeyDown={e=>{if(e.key==='Escape')setMenu(false);}}>{nav.map(([id,en,mr])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{t(en,mr)}</a>)}</nav><div className="pe-header-actions"><div className="pe-language" aria-label="Language"><button lang="mr" aria-pressed={language==='mr'} onClick={()=>setLanguage('mr')}>मराठी</button><span>|</span><button lang="en" aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>English</button></div><a className="pe-login" href="/login">{t('School Login','शाळा प्रवेश')}</a></div></header>
  <main id="pe-content">
   <section className="pe-hero pe-container"><div><p className="pe-eyebrow"><span/> PERFECTEDU · EDUCATION ERP</p><h1>{t('A new digital direction for school management.','शिक्षण व्यवस्थापनाची नवी डिजिटल दिशा.')}</h1><p className="pe-lead">{t('Students, teachers, attendance, fees, results, documents and parent communication — bring the school day together in one digital workspace.','विद्यार्थी, शिक्षक, उपस्थिती, शुल्क, निकाल, कागदपत्रे, पालक संवाद आणि शाळेचे दैनंदिन प्रशासन — सर्व काही एका डिजिटल प्लॅटफॉर्मवर.')}</p><div className="pe-actions">{login}<a className="pe-text-link" href="#about">{t('Discover PerfectEdu','PerfectEdu बद्दल जाणून घ्या')} ↗</a></div><p className="pe-hero-note"><Icon name="school"/>{t('Every school. Its own identity. One connected workspace.','प्रत्येक शाळा. स्वतंत्र ओळख. एकच स्मार्ट व्यवस्था.')}</p></div><div className="pe-visual" aria-label={t('Illustrative school workspace','शाळा कार्यस्थानाचे प्रातिनिधिक चित्र')}><div className="pe-window-bar"><span>● ● ●</span><small>{t('ILLUSTRATIVE WORKSPACE','प्रातिनिधिक कार्यस्थान')}</small></div><div className="pe-workspace"><div className="pe-workspace-title"><span className="pe-mark"><Icon name="school"/></span><div><strong>{t('Your school workspace','आपल्या शाळेचे कार्यस्थान')}</strong><small>{t('One place for every school day','शाळेच्या प्रत्येक दिवसासाठी एकच व्यवस्था')}</small></div></div><div className="pe-mini-grid">{[['users','Students','विद्यार्थी'],['calendar','Attendance','उपस्थिती'],['file','Documents','कागदपत्रे']].map(([icon,en,mr])=><div key={icon}><Icon name={icon}/><strong>{t(en,mr)}</strong><span className="pe-line"/><span className="pe-line short"/></div>)}</div><div className="pe-workspace-row"><div><p className="pe-eyebrow">{t('THE SCHOOL DAY','शाळेचा दिवस')}</p>{[['calendar','Record attendance','उपस्थिती नोंदवा'],['message','Stay in touch with parents','पालकांशी संपर्क ठेवा'],['file','Prepare school documents','शाळेची कागदपत्रे तयार करा']].map(([icon,en,mr])=><p key={icon}><Icon name={icon}/>{t(en,mr)}<span>↗</span></p>)}</div><div className="pe-book-art"><Icon name="book"/><span>LEARN<br/>CONNECT<br/>GROW</span></div></div></div><div className="pe-visual-caption"><Icon name="shield"/>{t('School identity · Roles · Academic years','शाळेची ओळख · भूमिका · शैक्षणिक वर्ष')}</div></div></section>
   <div className="pe-audience"><div className="pe-container">{[['Schools','शाळा'],['Higher secondary schools','उच्च माध्यमिक शाळा'],['Headmasters','मुख्याध्यापक'],['Teachers','शिक्षक'],['Educational institutions','शैक्षणिक संस्था']].map(([en,mr])=><span key={en}>{t(en,mr)}</span>)}</div></div>
   <section id="about" className="pe-container pe-section pe-intro"><div>{heading('01 / PERFECTEDU','What is PerfectEdu?','PerfectEdu म्हणजे काय?')}</div><div><p className="pe-large-copy">{t('A school management platform that brings administration, learning records and communication together.','PerfectEdu ही शाळांसाठी विकसित केलेली संपूर्ण डिजिटल School Management Platform आहे.')}</p><p>{t('From admission to leaving certificates, attendance to parent communication, and fees to results — organise the records that matter in one place. Each school’s workspace is identified by its UDISE code.','शाळेच्या प्रवेशापासून विद्यार्थ्यांच्या Leaving Certificate पर्यंत, उपस्थितीपासून पालक संवादापर्यंत आणि फीपासून निकालापर्यंत सर्व नोंदी एका ठिकाणी व्यवस्थापित करा. प्रत्येक शाळेचे स्वतंत्र कार्यस्थान तिच्या UDISE कोडने ओळखले जाते.')}</p></div></section>
   <section id="features" className="pe-light"><div className="pe-container pe-section"><div className="pe-section-top"><div>{heading('02 / CONNECTED SCHOOL','One school. Every essential workflow.','संपूर्ण शाळा. प्रत्येक महत्त्वाचे काम.')}</div><p>{t('Familiar school processes, thoughtfully organised.','शाळेच्या परिचित कामांची सुबक डिजिटल मांडणी.')}</p></div><div id="modules" className="pe-features">{features.map(([icon,en,mr,desc,descMr],i)=><article key={en}><div className="pe-feature-top"><Icon name={icon}/><span>{String(i+1).padStart(2,'0')}</span></div><h3>{t(en,mr)}</h3><p>{t(desc,descMr)}</p></article>)}</div></div></section>
   <section className="pe-container pe-section pe-split"><div>{heading('03 / SMART ATTENDANCE','More than attendance. A closer connection to parents.','उपस्थितीपेक्षा अधिक — पालकांपर्यंत त्वरित माहिती')}<p>{t('Move from the daily register to the right parent contact without opening another student profile.','दैनंदिन उपस्थिती नोंदवहीतूनच योग्य पालकाशी संपर्क साधा.')}</p><ul className="pe-checks">{[['Present, absent, late and permission leave','उपस्थित, अनुपस्थित, उशीर आणि परवानगी रजा'],['Father, mother and emergency contacts','वडील, आई आणि आपत्कालीन संपर्क'],['Call, WhatsApp and SMS shortcuts','कॉल, WhatsApp आणि SMS पर्याय'],['Dismissal notices and prolonged absence follow-up','शाळा सुटल्याची सूचना आणि दीर्घ अनुपस्थितीचा पाठपुरावा']].map(([en,mr])=><li key={en}>{t(en,mr)}</li>)}</ul></div><div className="pe-register"><div className="pe-register-head"><Icon name="calendar"/><strong>{t('Attendance & parent contact','उपस्थिती आणि पालक संपर्क')}</strong></div><small>{t('Illustration · no actual student records','प्रातिनिधिक मांडणी · वास्तविक विद्यार्थी नोंदी नाहीत')}</small>{[['P','Present','उपस्थित'],['A','Absent','अनुपस्थित'],['L','Late','उशीर'],['PL','Permission leave','परवानगी रजा']].map(([code,en,mr])=><div className="pe-register-row" key={code}><span className={'pe-status pe-status-'+code}>{code}</span><strong>{t(en,mr)}</strong><span className="pe-contact-icons"><Icon name="phone"/><Icon name="message"/></span></div>)}<p>{t('Choose the contact. Open the device dialer or message composer.','संपर्क निवडा. उपकरणावर कॉल किंवा संदेशाचा पर्याय उघडा.')}</p></div></section>
   <section className="pe-doc-section"><div className="pe-container pe-section pe-split"><div className="pe-document-art"><div className="pe-paper"><Icon name="cap"/><small>PERFECTEDU</small><h3>{t('School documents','शाळेची कागदपत्रे')}</h3><span className="pe-line"/><span className="pe-line"/><span className="pe-line short"/><div className="pe-seal"><Icon name="award"/></div><small>{t('Your school. Your letterhead.','आपली शाळा. आपले लेटरहेड.')}</small></div></div><div>{heading('04 / DIGITAL DOCUMENTS','School documents, now digital.','कागदपत्रे आता डिजिटल')}<p>{t('Use stored student information to fill your school’s approved templates. Preview, print and prepare documents for PDF.','जतन केलेल्या विद्यार्थी माहितीवरून शाळेचे मंजूर नमुने आपोआप भरा. पूर्वावलोकन, प्रिंट आणि PDF साठी कागदपत्रे तयार करा.')}</p>{tags(documents)}<p className="pe-emphasis">{t('Enter information once. Prepare the documents you need.','एकदा माहिती भरा — आवश्यक कागदपत्रे तयार करा')}</p></div></div></section>
   <section className="pe-container pe-section pe-split"><div>{heading('05 / PARENT COMMUNICATION','Keep school and home connected.','शाळा आणि पालकांमध्ये सतत संपर्क')}<p>{t('Editable Marathi and English templates for everyday updates. Native calling and message composers remain available; automatic delivery requires a configured provider.','दैनंदिन सूचनांसाठी संपादन करता येणारे मराठी आणि इंग्रजी नमुने. कॉल व संदेशाचे पर्याय उपलब्ध राहतात; स्वयंचलित संदेश वितरणासाठी सेवा प्रदात्याची जोडणी आवश्यक आहे.')}</p>{tags([['Present / Absent / Late','उपस्थित / अनुपस्थित / उशीर'],['School dismissal','शाळा सुटल्याची सूचना'],['Fee receipt & reminder','फी पावती व स्मरणपत्र'],['Results & parent meetings','निकाल व पालक सभा'],['Library & trips','ग्रंथालय व सहली'],['Emergency notices','आपत्कालीन सूचना']])}</div><div className="pe-message-art"><Icon name="message"/><p className="pe-eyebrow">{t('MESSAGE TEMPLATE · PREVIEW','संदेश नमुना · पूर्वावलोकन')}</p><blockquote>{t('Your child [Student Name] is marked absent on [Date]. Please contact the school if required.','आपला पाल्य [विद्यार्थ्याचे नाव] दिनांक [दिनांक] रोजी अनुपस्थित आहे. आवश्यक असल्यास शाळेशी संपर्क साधावा.')}</blockquote><div><span>मराठी</span><span>English</span></div></div></section>
   <section id="schools" className="pe-navy"><div className="pe-container pe-section">{heading('06 / MULTI-SCHOOL PLATFORM','One platform. Independent school workspaces.','एक प्लॅटफॉर्म — अनेक शाळा')}<p>{t('UDISE identifies the school; user roles determine access within its workspace. School data and permissions must remain isolated at the backend.','UDISE शाळेची ओळख ठरवतो; वापरकर्त्याच्या भूमिकेनुसार कार्यस्थानातील प्रवेश ठरतो. प्रत्येक शाळेची माहिती आणि परवानग्या बॅकएंड स्तरावर स्वतंत्र राहणे आवश्यक आहे.')}</p><ol className="pe-flow">{[['PerfectEdu','PerfectEdu'],['UDISE identification','UDISE ओळख'],['School workspace','शाळेचे कार्यस्थान'],['School admin','शाळा प्रशासक'],['Teachers','शिक्षक'],['Students / Parents','विद्यार्थी / पालक']].map(([en,mr],i)=><li key={en}><span>0{i+1}</span>{t(en,mr)}</li>)}</ol></div></section>
   <section id="mobile" className="pe-container pe-section pe-split"><div className="pe-phone"><div className="pe-phone-notch"/><span className="pe-mark"><Icon name="cap"/></span><h3>Perfect Education</h3><small>{t('MOBILE WORKSPACE · ILLUSTRATION','मोबाईल कार्यस्थान · प्रातिनिधिक चित्र')}</small>{[['calendar','Attendance','उपस्थिती'],['search','Student search','विद्यार्थी शोध'],['phone','Parent contact','पालक संपर्क'],['message','Notifications','सूचना']].map(([icon,en,mr])=><div key={icon}><Icon name={icon}/>{t(en,mr)}<span>›</span></div>)}</div><div>{heading('07 / PERFECTEDU MOBILE','Web and mobile. One school data source.','वेब आणि मोबाईल — एकच माहिती')}<p>{t('Designed for teachers to access attendance, students and parent contacts on Android, using the same school backend as the web workspace.','वेब कार्यस्थानाप्रमाणेच शाळेच्या एकाच बॅकएंडमधून Android वर उपस्थिती, विद्यार्थी माहिती आणि पालक संपर्क वापरण्याची रचना.')}</p><p>{t('The connected production Android release is being verified. Download will be enabled after release testing.','जोडणी असलेल्या उत्पादन Android आवृत्तीची पडताळणी सुरू आहे. चाचण्या पूर्ण झाल्यानंतर डाउनलोड उपलब्ध होईल.')}</p><button className="pe-button" disabled><Icon name="download"/>{t('Download Android App','Android ॲप डाउनलोड करा')}</button><small className="pe-release-note">{t('Verified release pending · no unverified APK offered','पडताळलेली आवृत्ती प्रतीक्षेत · अप्रमाणित APK दिलेली नाही')}</small></div></section>
   <section className="pe-light"><div className="pe-container pe-section">{heading('08 / RESPONSIBLE ACCESS','School information deserves careful protection.','शाळेची माहिती सुरक्षित')}<div className="pe-security">{[['UDISE identification','UDISE आधारित ओळख'],['Role-based access','भूमिकेनुसार प्रवेश'],['School data isolation','शाळानिहाय स्वतंत्र माहिती'],['Admin-controlled users','प्रशासकाच्या नियंत्रणातील वापरकर्ते'],['Secure authentication','सुरक्षित प्रमाणीकरण'],['Audit history','बदलांचा इतिहास'],['Backup & restore','बॅकअप आणि पुनर्संचयित'],['Academic year control','शैक्षणिक वर्ष नियंत्रण']].map(([en,mr])=><div key={en}><Icon name="shield"/>{t(en,mr)}</div>)}</div><p className="pe-release-note">{t('Production authentication and tenant security verification are ongoing. This overview is not a certification of production readiness.','उत्पादन प्रमाणीकरण आणि शाळानिहाय सुरक्षा पडताळणी सुरू आहे. हा परिचय उत्पादन सज्जतेचे प्रमाणपत्र नाही.')}</p></div></section>
   <section className="pe-container pe-section"><p className="pe-eyebrow">WHY PERFECTEDU</p><div className="pe-benefits">{[['Save time','वेळेची बचत'],['Digital documents','कागदपत्रांचे डिजिटलायझेशन'],['Faster parent contact','पालकांशी जलद संपर्क'],['One school workspace','एकाच ठिकाणी संपूर्ण शाळा व्यवस्थापन']].map(([en,mr],i)=><div key={en}><span>0{i+1}</span><h3>{t(en,mr)}</h3></div>)}</div></section>
   <section className="pe-container pe-cta"><div><p className="pe-eyebrow">LET’S MOVE EDUCATION FORWARD</p><h2>{t('Ready for a more connected school?','आपली शाळा डिजिटल व्यवस्थापनासाठी तयार आहे का?')}</h2><p>{t('Make everyday school management simpler, from students to administration.','PerfectEdu सोबत विद्यार्थ्यांपासून प्रशासनापर्यंत संपूर्ण शाळा व्यवस्थापन अधिक सोपे करा.')}</p></div><div className="pe-actions">{login}<a href="#contact" className="pe-text-link">{t('Contact PerfectEdu','PerfectEdu संपर्क')} ↗</a></div></section>
   <section className="pe-container pe-section pe-split"><div id="support">{heading('HELP & SUPPORT','Need help getting started?','सुरुवात करण्यासाठी मदत हवी?')}<p>{t('Use your school’s verified UDISE and the account provided by your school administrator. For account access or password assistance, contact your school administrator.','शाळेचा पडताळलेला UDISE आणि शाळा प्रशासकाने दिलेले खाते वापरा. खाते प्रवेश किंवा पासवर्ड मदतीसाठी शाळा प्रशासकाशी संपर्क साधा.')}</p><a className="pe-text-link" href="/login">{t('Go to school login','शाळा प्रवेशाकडे जा')} →</a></div><div id="contact"><h2>{t('Contact PerfectEdu','PerfectEdu संपर्क')}</h2><p>{t('Platform support contact details will be published here once confirmed. For existing school accounts, your school administrator is your first point of contact.','प्लॅटफॉर्म मदतीचे संपर्क तपशील निश्चित झाल्यावर येथे प्रकाशित केले जातील. विद्यमान शाळा खात्यांसाठी प्रथम आपल्या शाळा प्रशासकाशी संपर्क साधा.')}</p><a className="pe-text-link" href="https://www.perfectedu.co.in">www.perfectedu.co.in</a></div></section>
  </main><footer className="pe-footer"><div className="pe-container"><div className="pe-footer-top"><div><strong>PerfectEdu</strong><p>School Management Platform</p><small>www.perfectedu.co.in</small></div><nav aria-label="Footer navigation">{nav.slice(0,4).map(([id,en,mr])=><a key={id} href={'#'+id}>{t(en,mr)}</a>)}<a href="/login">{t('School Login','शाळा प्रवेश')}</a><a href="#support">{t('Support','मदत')}</a></nav><div className="pe-policies"><details><summary>{t('Privacy Policy','गोपनीयता धोरण')}</summary><p>{t('The approved public privacy policy is awaiting publication. Contact your school administrator for current school data-handling information.','मंजूर सार्वजनिक गोपनीयता धोरण प्रकाशित होणे बाकी आहे. शाळेच्या माहिती हाताळणीबाबत शाळा प्रशासकाशी संपर्क साधा.')}</p></details><details><summary>{t('Terms','अटी')}</summary><p>{t('Platform terms are awaiting publication. School access is restricted to authorised accounts.','प्लॅटफॉर्मच्या अटी प्रकाशित होणे बाकी आहे. शाळेत प्रवेश केवळ अधिकृत खात्यांसाठी आहे.')}</p></details></div></div><div className="pe-footer-bottom">© {new Date().getFullYear()} PerfectEdu. All rights reserved.<span>{t('Built for the school day.','शाळेच्या प्रत्येक दिवसासाठी.')}</span></div></div></footer>
 </div>;
}
