import {useEffect,useState,useRef} from 'react';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,sendPasswordResetEmail} from 'firebase/auth';
import {schoolFirebase} from '../backend/firebaseClient';
import {navigationItems} from '../design/navigation';
import './platform-administration.css';
const labels={schoolNameEn:'School Name',schoolNameMr:'School Name in Marathi',udise:'UDISE Code',schoolCode:'Unique School Code',tenantId:'Permanent Tenant ID',institutionName:'Management / Institution Name',schoolType:'School Type',board:'Board',medium:'Medium',address:'Address',city:'Village / City',taluka:'Taluka',district:'District',state:'State',pin:'PIN Code',principal:'Principal / Headmaster',mobile:'School Mobile',alternateMobile:'Alternative Mobile',email:'School Email',adminEmail:'Admin Email',academicYear:'Academic Year',plan:'Subscription / Plan'};
const empty=()=>Object.fromEntries([...Object.keys(labels).map(k=>[k,'']),['status','INACTIVE'],['logo','']]);
const menu=['Dashboard','Schools','Add New School','School Administrators','Users','Subscriptions / Plans','Platform Reports','Activity Logs','Platform Settings'];
const collections=['students','teachers','staff','attendance','fees','results','notifications','library','sports','trips','certificates','academic_years','parents','settings','documents','templates'];
export default function PlatformAdministration(){
 const [authorities,setAuthorities]=useState([]),[authorityForm,setAuthorityForm]=useState({email:'',role:'PLATFORM_SUPPORT',active:true});
 const [session,setSession]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('Dashboard'),[schools,setSchools]=useState([]),[userCount,setUserCount]=useState(0),[query,setQuery]=useState(''),[form,setForm]=useState(null),[selected,setSelected]=useState(null),[users,setUsers]=useState([]),[admin,setAdmin]=useState(null),[logs,setLogs]=useState([]),[settings,setSettings]=useState({platformName:'Perfect Education',supportEmail:''}),[records,setRecords]=useState([]),[collection,setCollection]=useState('students');
 const roleRef=useRef(null);roleRef.current=session?.role;
 async function request(action,body={}){const user=schoolFirebase().auth.currentUser;if(!user)throw Error('Sign in with your platform account.');const url=import.meta.env.VITE_TENANT_AUTH_URL;if(!url)throw Error('Production platform backend is not configured.');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await user.getIdToken()},body:JSON.stringify({action,...body})});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;}
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.code?'Unable to sign in. Check your account or use password recovery.':e.message);}finally{setBusy(false);}}
 async function refresh(){const result=await request('platform-list');setSchools(result.schools);setUserCount(result.totalPlatformUsers);}
 useEffect(()=>{document.title='Perfect Education | Platform Administration';let stop=()=>{},generation=0;const loginRoute=()=>history.replaceState(null,'','/platform-admin/login');try{stop=onAuthStateChanged(schoolFirebase().auth,async user=>{const current=++generation;setSession(null);if(!user){loginRoute();return;}setBusy(true);setError('');try{const verified=await request('platform-session');if(current!==generation)return;await refresh();if(current!==generation)return;setView('Dashboard');setSelected(null);setForm(null);setAdmin(null);setSession(verified);history.replaceState(null,'','/platform-admin');const saved=sessionStorage.getItem('perfectedu_platform_school');if(saved&&verified.role==='PLATFORM_SUPER_ADMIN')await open({id:saved});}catch(e){if(current===generation){setSession(null);loginRoute();setError(e.message);}}finally{if(current===generation)setBusy(false);}});}catch(e){setError(e.message);loginRoute();}return()=>{generation++;stop();};},[]);
 useEffect(()=>{if(!session?.email)return;let live=true,activity=Date.now();const started=activity;const logout=()=>{setSession(null);void signOut(schoolFirebase().auth);};const expire=()=>{if(Date.now()-activity>=15*60000||Date.now()-started>=8*60*60000)logout();};const touch=()=>{expire();activity=Date.now();};const events=['pointerdown','keydown','touchstart'];events.forEach(name=>window.addEventListener(name,touch));window.addEventListener('focus',expire);const timer=setInterval(expire,1000);const verify=setInterval(async()=>{try{const next=await request('platform-session');if(live&&roleRef.current){if(roleRef.current!==next.role){setView('Dashboard');setSelected(null);setForm(null);setAdmin(null);}setSession(next);}}catch{if(live)logout();}},60000);return()=>{live=false;clearInterval(timer);clearInterval(verify);events.forEach(name=>window.removeEventListener(name,touch));window.removeEventListener('focus',expire);};},[session?.email]);
 async function navigate(name){sessionStorage.removeItem('perfectedu_platform_school');setView(name);setSelected(null);setAdmin(null);setForm(name==='Add New School'?empty():null);if(name==='Users')setAuthorities((await request('platform-authorities')).users);if(name==='Activity Logs')setLogs((await request('platform-logs')).logs);if(name==='Platform Settings')setSettings((await request('platform-settings')).settings);}
 async function open(school,name=collection){const data=await request('platform-school',{schoolId:school.id,collection:name});setSelected(data.school);setRecords(data.records);setCollection(name);setView('School inspection');sessionStorage.setItem('perfectedu_platform_school',school.id);}
 async function manage(s){setSelected(s);setUsers((await request('platform-users',{schoolId:s.id})).users);setAdmin({name:'',email:'',mobile:'',active:true,modules:navigationItems.map(n=>n[0])});setView('School Administrators');}
 function download(){const csv=[['School','UDISE','Tenant','Students','Teachers','Staff','Status'],...schools.map(s=>[s.schoolNameEn||s.schoolNameMr,s.udise,s.id,s.studentCount,s.teacherCount,s.staffCount,s.status])].map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));a.download='Perfect-Education-Platform-Report.csv';a.click();URL.revokeObjectURL(a.href);}
 const totals={Schools:schools.length,'Active Schools':schools.filter(s=>s.status==='ACTIVE').length,'Inactive Schools':schools.filter(s=>s.status!=='ACTIVE').length,Students:schools.reduce((n,s)=>n+s.studentCount,0),Teachers:schools.reduce((n,s)=>n+s.teacherCount,0),Staff:schools.reduce((n,s)=>n+s.staffCount,0),'Platform Users':userCount};
 return <div className="platform-admin"><header><a href="/">Perfect Education</a><span>Platform Administration</span><a href="/login">School Login</a></header><div role="alert">{error}</div><p role="status">{message}</p>{!session?<main><h1>Super Admin Login</h1><p>Platform access is separately authorized. A school administrator account alone cannot enter this panel.</p><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);run(()=>signInWithEmailAndPassword(schoolFirebase().auth,String(data.get('email')).trim(),data.get('password')));}}><label>Email / User ID<input aria-label="Email" name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>Platform Login</button><button type="button" onClick={e=>{const email=new FormData(e.currentTarget.form).get('email');run(async()=>{await sendPasswordResetEmail(schoolFirebase().auth,String(email).trim());setMessage('If eligible, your account will receive a reset email.');});}}>Forgot Password</button></form></main>:<div className="platform-layout"><nav aria-label="Platform navigation">{menu.filter(name=>session.role==='PLATFORM_SUPER_ADMIN'||['Dashboard','Schools','Platform Reports'].includes(name)).map(name=><button key={name} aria-current={view===name?'page':undefined} onClick={()=>run(()=>navigate(name))}>{name}</button>)}<button onClick={()=>run(async()=>{sessionStorage.removeItem('perfectedu_platform_school');await signOut(schoolFirebase().auth);setSession(null);setSchools([]);setSelected(null);setRecords([]);})}>Logout</button></nav><main><h1>{view}</h1><p>Signed in: {session.email} · {session.role}</p>
 {view==='Dashboard'&&<><div className="platform-stats">{Object.entries(totals).map(([label,value])=><article key={label}><strong>{value}</strong><span>Total {label}</span></article>)}</div><h2>Recently added schools</h2>{[...schools].sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0)).slice(0,5).map(s=><p key={s.id}>{s.schoolNameEn||s.schoolNameMr} · {s.udise} · {s.status}</p>)}</>}
 {form&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await request('platform-save-school',{school:form});setForm(null);await refresh();setView('Schools');setMessage('School saved. Existing school records were preserved.');});}}><div className="platform-form">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input value={form[key]||''} required={['schoolNameEn','udise','schoolCode','tenantId','academicYear'].includes(key)} readOnly={key==='tenantId'&&!!form.id} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label>School Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files[0];if(!f)return;if(f.size>140000||!['image/png','image/jpeg','image/webp'].includes(f.type)){setError('Use PNG/JPEG/WebP up to 140 KB.');return;}const r=new FileReader();r.onload=()=>setForm(s=>({...s,logo:r.result}));r.readAsDataURL(f);}}/>{form.logo&&<img width="70" src={form.logo} alt="School logo"/>}</label></div><button disabled={busy}>Save School</button><button type="button" onClick={()=>setForm(null)}>Cancel</button></form>}
 {['Schools','School Administrators','Users','Subscriptions / Plans','Platform Reports'].includes(view)&&!selected&&<><label>Search school<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={download}>Export Platform Report</button><div className="platform-table"><table><thead><tr>{['School','UDISE','Tenant ID','District','Admin','Students / Staff','Status','Created','Actions'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{schools.filter(s=>[s.schoolNameEn,s.schoolNameMr,s.udise,s.id].join(' ').toLowerCase().includes(query.toLowerCase())).map(s=><tr key={s.id}><td>{s.schoolNameEn||s.schoolNameMr}</td><td>{s.udise}</td><td>{s.id}</td><td>{s.district}</td><td>{s.adminEmail||'View admins'}</td><td>{s.studentCount} / {s.teacherCount+s.staffCount}</td><td>{s.status}</td><td>{s.createdAt?._seconds?new Date(s.createdAt._seconds*1000).toLocaleDateString():'Existing school'}</td><td>{session.role==='PLATFORM_SUPER_ADMIN'&&<><button onClick={()=>run(()=>open(s))}>Open School</button><button onClick={()=>run(async()=>{const d=await request('platform-school',{schoolId:s.id});setForm({...empty(),...d.school,tenantId:s.id});})}>Edit School</button><button onClick={()=>run(()=>manage(s))}>Manage Admins</button><button onClick={()=>run(async()=>{if(!confirm(`${s.status==='ACTIVE'?'Deactivate':'Activate'} ${s.schoolNameEn||s.id}?`))return;await request('platform-status',{schoolId:s.id,status:s.status==='ACTIVE'?'INACTIVE':'ACTIVE'});await refresh();})}>{s.status==='ACTIVE'?'Deactivate':'Activate'}</button></>}<button onClick={()=>{setMessage(`${s.id}: ${s.studentCount} students, ${s.teacherCount} teachers, ${s.staffCount} staff, ${s.userCount} memberships.`);}}>View Statistics</button></td></tr>)}</tbody></table></div></>}
 {selected&&<section className="platform-context"><h2>{selected.schoolNameEn||selected.schoolNameMr||selected.schoolName}</h2><p>UDISE: {selected.udise} · Tenant: {selected.id} · Platform administrative context</p><button onClick={()=>run(()=>navigate('Schools'))}>Back to Platform Admin</button></section>}
 {view==='School inspection'&&selected&&<><p>Read-only administrative inspection. First 200 records per collection. School records are never copied between tenants.</p><label>School records<select value={collection} onChange={e=>run(()=>open(selected,e.target.value))}>{collections.map(c=><option key={c}>{c}</option>)}</select></label>{records.length?records.map(r=><details key={r.id}><summary>{r.data?.name||r.name||r.id}</summary><pre>{JSON.stringify(r.data||r,null,2)}</pre></details>):<p>No records in this school collection.</p>}</>}
 {admin&&selected&&<><form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await request('platform-save-admin',{schoolId:selected.id,user:admin});await manage(selected);setMessage(`SCHOOL_ADMIN membership saved for ${result.email}. Use Send password setup email for secure password creation; existing passwords were not changed.`);});}}><h2>School administrator</h2>{['name','email','mobile'].map(k=><label key={k}>{k}<input value={admin[k]||''} required={k!=='mobile'} type={k==='email'?'email':'text'} onChange={e=>setAdmin({...admin,[k]:e.target.value})}/></label>)}<label><input type="checkbox" checked={admin.active} onChange={e=>setAdmin({...admin,active:e.target.checked})}/>Active</label><p>Role: SCHOOL_ADMIN · School: {selected.id}</p><button disabled={busy}>Save School Admin</button><button type="button" onClick={()=>run(async()=>{await sendPasswordResetEmail(schoolFirebase().auth,admin.email);setMessage('Password setup/reset email requested.');})}>Send password setup email</button></form>{users.map(u=><p key={u.uid}>{u.name||u.email||u.uid} · {u.role} · {u.active?'Active':'Inactive'} {u.role==='SCHOOL_ADMIN'&&<button onClick={()=>setAdmin(u)}>Edit</button>}</p>)}</>}
 {view==='Users'&&session.role==='PLATFORM_SUPER_ADMIN'&&<section><h2>Platform users</h2><p>These roles govern the platform, not school membership. Support can view school directory and aggregate counts only.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await request('platform-save-authority',{user:authorityForm});setAuthorities((await request('platform-authorities')).users);setMessage('Platform role saved. Authentication password and school memberships were preserved.');});}}><label>Existing account email<input type="email" required value={authorityForm.email} onChange={e=>setAuthorityForm({...authorityForm,email:e.target.value})}/></label><label>Platform role<select aria-label="Platform role" value={authorityForm.role} onChange={e=>setAuthorityForm({...authorityForm,role:e.target.value})}><option>PLATFORM_SUPPORT</option><option>PLATFORM_SUPER_ADMIN</option></select></label><label><input type="checkbox" checked={authorityForm.active} onChange={e=>setAuthorityForm({...authorityForm,active:e.target.checked})}/>Platform access active</label><button disabled={busy}>Save platform access</button></form>{authorities.map(user=><article key={user.uid}><p>{user.email||user.uid} | {user.role} | {user.active?'Active':'Inactive'} | Last sign-in: {user.lastSignIn||'Not recorded'}</p><button onClick={()=>setAuthorityForm({email:user.email,role:user.role,active:user.active})}>Edit platform access</button></article>)}</section>}
 {view==='Activity Logs'&&logs.map(l=><p key={l.id}>{l.at} · {l.action} · {l.schoolId} · {l.actor}</p>)}
 {view==='Platform Settings'&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await request('platform-settings',{settings});setMessage('Platform settings saved.');});}}>{Object.keys(settings).map(k=><label key={k}>{k}<input value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}<button disabled={busy}>Save Settings</button></form>}
 </main></div>}</div>;
}
