import {useEffect,useState} from 'react';
import {readStored,localDate} from '../storage';
import {useLanguage} from '../design/language';
import {PageHeading} from '../design/SchoolUI';
import {canView} from '../design/portalNavigation';
import {attendanceSummary,isActiveStudent,calendarEvent} from '../services/schoolOverview';
import Icon from '../components/Icon';
import {SchoolMark} from '../design/SchoolUI';

const quickActions=[
 ['Add Student','विद्यार्थी जोडा','Students','plus',{mode:'add'}],['Upload Excel','Excel अपलोड','Students','upload',{mode:'import'}],['Take Attendance','उपस्थिती नोंदवा','Attendance','calendar'],['Add Homework','गृहपाठ द्या','Homework','book'],['Enter Marks','गुण नोंदवा','Results','chart'],['Generate Bonafide','बोनाफाईड तयार करा','Formats','award',{initialType:'Bonafide Certificate'}],['Generate LC','LC तयार करा','Formats','file',{initialType:'Leaving Certificate'}],['Create ID Card','ओळखपत्र तयार करा','IDCard','badge'],['Send Notice','सूचना द्या','PortalContent','bell'],['Send WhatsApp','WhatsApp पाठवा','Communications','message'],['Send SMS','SMS पाठवा','Communications','message'],['Call Parent','पालकांना कॉल','Communications','phone'],['Create Trip','सहल तयार करा','Trips','pin'],['Add Sports Result','क्रीडा निकाल','Sports','trophy'],['Issue Library Book','पुस्तक द्या','Library','book']
];
export default function PortalHome({onNavigate,role='Admin',settings={}}){
 const{t}=useLanguage();const today=localDate();const students=readStored('erp_pro_students',[]).filter(isActiveStudent),teachers=readStored('erp_pro_teachers',[]),homework=readStored('erp_pro_homework',[]),trips=readStored('erp_pro_trips',[]),calendar=readStored('erp_pro_calendar',[]).map(calendarEvent),notices=readStored('erp_pro_portal_notices',[]).filter(n=>n.published),slides=readStored('erp_pro_portal_slides',[]).filter(s=>s.published);
 const attendance=attendanceSummary(students,readStored('erp_pro_attendance',{})[today]||{}),events=calendar.filter(e=>e.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
 const[index,setIndex]=useState(0),[pause,setPause]=useState(false),[hover,setHover]=useState(false);useEffect(()=>{if(pause||hover||slides.length<2||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setInterval(()=>setIndex(i=>i+1),6500);return()=>clearInterval(id)},[pause,hover,slides.length]);const slide=slides[index%Math.max(1,slides.length)];
 const metrics=[['Total Students','एकूण विद्यार्थी',students.length,'Students','users'],['Present Today','आज उपस्थित',attendance.present,'Attendance','check'],['Absent Today','आज अनुपस्थित',attendance.absent,'Attendance','calendar',{initialStatus:'Absent'}],['Teachers','शिक्षक',teachers.length,'Teachers','cap'],['Classes','वर्ग',new Set(students.map(s=>s.className).filter(Boolean)).size,'Academics','grid'],["Today’s Homework",'आजचा गृहपाठ',homework.filter(h=>h.date===today).length,'Homework','book'],['Upcoming Exams','आगामी परीक्षा',events.filter(e=>/exam|परीक्षा/i.test(e.type+' '+e.title)).length,'Results','file'],['New Notices','नवीन सूचना',notices.length,'PortalContent','bell'],['Upcoming Trips','आगामी सहली',trips.filter(i=>i.startDate>=today).length,'Trips','pin'],['Sports Events','क्रीडा कार्यक्रम',events.filter(e=>/sport|क्रीडा/i.test(e.type+' '+e.title)).length,'Sports','trophy'],['Scholarships','शिष्यवृत्ती',readStored('erp_pro_scholarship_applications',[]).length,'Scholarships','award'],['Pending Certificates','प्रलंबित प्रमाणपत्रे',readStored('erp_pro_certificates',[]).filter(c=>c.status==='Pending').length,'Formats','file'],['Library Due Books','परतावा देय पुस्तके',readStored('erp_pro_library_loans',[]).filter(l=>!l.returned&&l.dueDate&&l.dueDate<=today).length,'Library','book']];
 return <div className="portal-home institutional-home">
 <div className="home-lead school-home-layout"><section className={`school-event-hero ${slide?'with-photo':''}`} aria-label="School event slider" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)}>{slide&&<img src={slide.src} alt={slide.title}/>}<div className="school-event-copy"><span>{t('OUR SCHOOL COMMUNITY','आपले शालेय विश्व')}</span><h2>{slide?slide.title:t('Knowledge. Character. Opportunity.','ज्ञान. संस्कार. संधी.')}</h2><p>{slide?.eventDate||t('Learning, achievement and the life of our school.','शिक्षण, यश आणि आपल्या शाळेतील घडामोडी.')}</p><button onClick={()=>onNavigate('PortalContent',{tab:'slides'})}>{slide?t('View school gallery','शालेय छायाचित्रे पहा'):t('Add school / event photographs','शाळा / कार्यक्रम छायाचित्रे जोडा')} ↗</button>{!slide&&<small>{t('Publish approved school photographs to display them in this slider.','येथे शाळेची मान्यताप्राप्त छायाचित्रे प्रकाशित करा.')}</small>}</div><div className="school-event-controls"><span>{String(index%Math.max(slides.length,1)+1).padStart(2,'0')} / {String(Math.max(slides.length,1)).padStart(2,'0')}</span><button aria-label="Previous slide" disabled={slides.length<2} onClick={()=>setIndex(i=>(i-1+slides.length)%slides.length)}>←</button><button aria-label="Next slide" disabled={slides.length<2} onClick={()=>setIndex(i=>i+1)}>→</button>{slides.length>1&&<button aria-label={pause?'Play slideshow':'Pause slideshow'} onClick={()=>setPause(!pause)}>{pause?'▶':'Ⅱ'}</button>}</div></section>
 <section className="institution-introduction"><span className="portal-eyebrow">{t('WELCOME TO OUR SCHOOL','आपल्या शाळेत स्वागत')}</span><h1>{t('A place to learn. A community to belong.','शिकण्याचे स्थान. आपुलकीचा परिवार.')}</h1><div className="institution-introduction-identity"><SchoolMark logo={settings.logo}/><div><h2>{settings.schoolName}</h2><p>{settings.address}</p></div></div><p>{t('Education brings together knowledge, character and opportunity. Our school portal connects learning, student records and everyday school life in one place.','ज्ञान, संस्कार आणि संधी यांचा संगम म्हणजे शिक्षण. शिक्षण, विद्यार्थी नोंदी आणि शालेय उपक्रमांसाठी एकत्रित शालेय पोर्टल.')}</p><div className="institution-introduction-links"><button onClick={()=>onNavigate('Academics')}>{t('Explore academics','शैक्षणिक उपक्रम')} →</button><button onClick={()=>onNavigate('Students')}>{t('Student Master','विद्यार्थी मास्टर')} →</button></div></section><aside className="home-notice-panel"><header><span>{t('LATEST UPDATES','ताज्या घडामोडी')}</span><h2>{t('Noticeboard','सूचना फलक')}</h2></header>{notices.length?notices.slice(0,3).map(n=><button key={n.id} onClick={()=>onNavigate('PortalContent',{tab:'notices'})}><small>{n.date||t('School notice','शालेय सूचना')}</small><strong>{t(n.title,n.titleMr||n.title)}</strong><span>↗</span></button>):<p>{t('Published school announcements will appear here.','प्रकाशित शालेय सूचना येथे दिसतील.')}</p>}<button className="home-panel-link" onClick={()=>onNavigate('PortalContent',{tab:'notices'})}>{t('All announcements','सर्व सूचना')} ↗</button></aside></div>
 <section className="home-priority-actions" aria-label="Quick actions">{quickActions.slice(0,5).filter(a=>canView(role,a[2])).map(([en,mr,page,icon,opts])=><button key={en} className={page==='Students'&&opts?.mode==='add'?'primary':''} onClick={()=>onNavigate(page,opts)}><Icon name={icon} size={17}/>{t(en,mr)}<span>↗</span></button>)}</section>
 <section className="home-record-summary"><div className="home-section-heading"><h2>{t('Today at a glance','आजचा आढावा')}</h2><small>{t('From saved school records','जतन केलेल्या शालेय नोंदींवर आधारित')}</small></div><div className="home-metric-row">{metrics.slice(0,6).filter(m=>canView(role,m[3])).map(([en,mr,value,page,icon,opts])=><button key={en} onClick={()=>onNavigate(page,opts)}><small>{t(en,mr)}</small><strong>{value}</strong><Icon name={icon} size={17}/></button>)}</div></section>
 <div className="home-office-grid"><section className="home-office-panel"><div className="home-section-heading"><h2>{t('School workspace','शालेय कार्यस्थान')}</h2><small>{t('Common tasks','नियमित कामे')}</small></div><div className="home-workspace-links">{quickActions.slice(0,5).filter(a=>canView(role,a[2])).map(([en,mr,page,icon,opts])=><button key={en} onClick={()=>onNavigate(page,opts)}><Icon name={icon} size={16}/>{t(en,mr)}<span>↗</span></button>)}</div></section><section className="home-office-panel"><div className="home-section-heading"><h2>{t('School calendar','शालेय दिनदर्शिका')}</h2><button onClick={()=>onNavigate('Calendar')}>{t('View all','सर्व पहा')} ↗</button></div>{events.length?events.slice(0,3).map(e=><button className="home-calendar-entry" key={e.id||e.title} onClick={()=>onNavigate('Calendar')}><time>{e.date}</time><strong>{e.title}</strong><span>{e.location||t('School campus','शाळा परिसर')}</span></button>):<p className="home-empty-text">{t('No upcoming events have been published.','आगामी कार्यक्रम प्रकाशित केलेले नाहीत.')}</p>}</section></div>
 <section className="home-institution-links">{[['About our school','आपल्या शाळेविषयी','PortalInfo',{title:'About School'}],['Academic programmes','शैक्षणिक उपक्रम','Academics'],['Student records & Excel import','विद्यार्थी नोंदी व Excel आयात','Students',{mode:'import'}]].filter(a=>canView(role,a[2])).map(([en,mr,page,opts])=><button key={en} onClick={()=>onNavigate(page,opts)}>{t(en,mr)} <span>↗</span></button>)}</section>
 </div>;
}
export function Academics({onNavigate}){const{t}=useLanguage();return <div className="core-page"><PageHeading eyebrow={t('LEARNING & PROGRESS','अध्ययन व प्रगती')} title={t('Academic centre','शैक्षणिक केंद्र')} description={t('Plan the lesson. Support the learner. Celebrate progress.','धड्याचे नियोजन. विद्यार्थ्यांना साथ. प्रगतीचा आनंद.')}/><section className="portal-academic-banner"><Icon name="book" size={50}/><div><h2>{t('Every learner has a next chapter.','प्रत्येक विद्यार्थ्याची पुढची पायरी.')}</h2><p>{t('Classes 8–12 • Lessons • Assessment • Progress','इयत्ता ८–१२ • अध्यापन • मूल्यमापन • प्रगती')}</p></div></section><div className="portal-class-grid">{[8,9,10,11,12].map(c=><button key={c} onClick={()=>onNavigate('Students',{initialClass:String(c)})}><span>{t('CLASS','इयत्ता')}</span><strong>{c}</strong><small>{t('View students','विद्यार्थी पहा')} →</small></button>)}</div><div className="portal-quick-grid">{[['Subjects','विषय','PortalInfo',{title:'Subjects',titleMr:'विषय'}],['Timetable','वेळापत्रक','Timetable'],['Homework','गृहपाठ','Homework'],['Assignments','स्वाध्याय','Classwork'],['Marks & Excel Import','गुण व Excel आयात','Results'],['Progress Cards','प्रगती पत्रके','Formats',{initialType:'Progress Card'}],['Annual Results','वार्षिक निकाल','Formats',{initialType:'Annual Result'}]].map(([en,mr,page,opts])=><button key={en} onClick={()=>onNavigate(page,opts)}><Icon name="book"/>{t(en,mr)}<Icon name="arrow" size={16}/></button>)}</div></div>}
