import { useLanguage } from "../design/language";
import { useState } from "react";
import { readStored, useStoredState, localDate } from "../storage";
import { PageHeading, EmptyState } from "../design/SchoolUI";
import { exportRows } from "../services/excel";
import { notify } from "../components/Feedback";

export default function Scholarships({ onNavigate }) {
  const { t } = useLanguage();
  const students = readStored("erp_pro_students", []).filter(s => !s.archivedAt);
  const [items, saveItems] = useStoredState("erp_pro_scholarship_applications", []), [form, setForm] = useState({ studentId: "", scholarship: "", eligibility: "", documents: "", status: "Pending", deadline: "" }), [query, setQuery] = useState("");
  const save = () => { const student = students.find(s => s.id === form.studentId); if (!student || !form.scholarship.trim() || !form.eligibility.trim() || !form.deadline) return notify("Student, scholarship, eligibility and deadline are required."); if (saveItems([...items, { ...form, id: crypto.randomUUID(), studentName: student.name, grNo: student.grNo, className: student.className, createdAt: localDate() }])) { setForm({ ...form, studentId: "" }); notify("Scholarship application saved."); } };
  const visible = items.filter(i => Object.values(i).join(" ").toLowerCase().includes(query.toLowerCase()));
  return <div className="core-page"><PageHeading eyebrow="OPPORTUNITY FOR EVERY LEARNER" title="Scholarships" description="Track eligibility, document checklists, applications and deadlines without losing sight of a student." /><section className="school-panel workflow-panel"><div className="form-grid"><label>{t("Student")}<select aria-label="Student" value={form.studentId} onChange={e => setForm({ ...form, studentId: e.target.value })}><option value="">Select student</option>{students.map(s => <option key={s.id} value={s.id}>{s.name} · {s.grNo}</option>)}</select></label>{["scholarship", "eligibility", "documents", "deadline"].map(k => <label key={k}>{t(k)}<input type={k === "deadline" ? "date" : "text"} value={form[k]} onChange={e => setForm({ ...form, [k]: e.target.value })} /></label>)}</div><button onClick={save}>{t("Save application")}</button><button onClick={() => onNavigate("Formats", { initialType: "Scholarship Form", studentId: form.studentId })}>Scholarship form</button></section><div className="domain-toolbar"><label>Search applications<input value={query} onChange={e => setQuery(e.target.value)} /></label><button onClick={() => exportRows(visible, "scholarship-students.xlsx")}>Export applications</button></div>{visible.length ? <div className="table-scroll"><table><thead><tr><th>Student / scheme</th><th>Eligibility / documents</th><th>Deadline reminder</th><th>Status</th></tr></thead><tbody>{visible.map(i => <tr key={i.id}><td>{i.studentName} · {i.grNo}<br/>{i.scholarship}</td><td>{i.eligibility}<br/>{i.documents || "Checklist pending"}</td><td>{i.deadline} · {i.deadline < localDate() ? "Deadline passed" : Math.ceil((Date.parse(i.deadline) - Date.parse(localDate())) / 86400000) <= 7 ? "Due within 7 days" : "Upcoming"}</td><td><select aria-label={`Scholarship status ${i.id}`} value={i.status} onChange={e => saveItems(items.map(row => row.id === i.id ? { ...row, status: e.target.value, updatedAt: new Date().toISOString() } : row))}>{["Pending", "Applied", "Approved", "Rejected"].map(s => <option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div> : <EmptyState icon="award" title="Help a student take the next step" description="Create an application to track requirements and deadlines. Reminders here are local; automatic messaging is not connected." />}<details><summary>Previous scholarship scheme notes ({readStored("erp_pro_scholarships", []).length})</summary>{readStored("erp_pro_scholarships", []).map(i => <pre key={i.id}>{JSON.stringify(i, null, 2)}</pre>)}</details></div>;
}
