import {useContext,useEffect,useState} from 'react';
import {sendPasswordResetEmail} from 'firebase/auth';
import {CommunicationSession} from '../backend/CommunicationSession';
import {tenantRequest,selectedUdise} from '../backend/tenantAuth';
import {schoolFirebase} from '../backend/firebaseClient';
const roles=['SCHOOL_ADMIN','HEADMASTER','TEACHER','CLERK','ACCOUNTANT','LIBRARIAN','SPORTS_TEACHER','STAFF','READ_ONLY'];
const roleAliases={"Admin":"SCHOOL_ADMIN","ADMIN":"SCHOOL_ADMIN","Headmaster":"HEADMASTER","Teacher":"TEACHER","Class Teacher":"TEACHER","Subject Teacher":"TEACHER","Clerk":"CLERK","Accounts Staff":"ACCOUNTANT","Library Staff":"LIBRARIAN","Sports Teacher":"SPORTS_TEACHER","Office Staff":"STAFF","Read Only":"READ_ONLY","VIEW_ONLY":"READ_ONLY"};
const blank=()=>({name:'',email:'',username:'',mobile:'',role:'TEACHER',active:true,modules:['Dashboard','Students','Attendance'],resources:['students','attendance','settings','academic_years'],classIds:[],studentIds:[]});
export default function SchoolUsers(){
 const session=useContext(CommunicationSession),[users,setUsers]=useState([]),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 const authorized=['Super Admin','Admin'].includes(session?.role);
 const request=(action,payload)=>tenantRequest(action,selectedUdise(),undefined,payload);
 async function refresh(){setUsers((await request('school-users')).users);}
 async function run(action){setBusy(true);setMessage('');try{await action();}catch(error){setMessage(error.code?'The account request could not be completed. Check the email and try again.':error.message);}finally{setBusy(false);}}
 useEffect(()=>{if(authorized)void run(refresh);},[authorized,session?.schoolId]);
 if(!authorized)return <p>School administrator permission is required to manage user accounts.</p>;
 async function save(){const result=await request('school-save-user',{user:{...form,classIds:form.classIds.map(value=>value.trim()).filter(Boolean)}});await refresh();setForm({...form,uid:result.uid});setMessage('School access saved. Use Send password setup email if needed. Existing passwords and other school memberships were preserved.');}
 return <div className="core-page"><h2>School users and permissions</h2><p>School: {session.schoolId}. These accounts cannot grant platform permissions. Deactivation applies only to this school.</p><form className="school-panel workflow-panel" onSubmit={e=>{e.preventDefault();void run(save);}}><div className="form-grid">{[['name','User name'],['email','User email'],['username','User ID'],['mobile','User mobile']].map(([key,label])=><label key={key}>{label}<input required={['name','email'].includes(key)} readOnly={key==='email'&&!!form.uid} type={key==='email'?'email':'text'} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>School role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.filter(role=>role!=='SCHOOL_ADMIN'||session.role==='Super Admin').map(role=><option key={role}>{role}</option>)}</select></label><label>Assigned classes (Class:Division, comma separated)<input value={form.classIds.join(',')} onChange={e=>setForm({...form,classIds:e.target.value.split(',')})}/></label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>School access active</label></div>{[['modules','Modules'],['resources','Data permissions']].map(([key,label])=><fieldset key={key}><legend>{label}</legend>{(session[key]||[]).map(value=><label key={value}><input type="checkbox" checked={form[key].includes(value)} onChange={e=>setForm({...form,[key]:e.target.checked?[...form[key],value]:form[key].filter(v=>v!==value)})}/>{value}</label>)}</fieldset>)}<button disabled={busy}>Save school user</button><button type="button" disabled={busy||!form.uid} onClick={()=>run(async()=>{await sendPasswordResetEmail(schoolFirebase().auth,form.email);setMessage('Password setup/reset email requested. The recipient completes it privately.');})}>Send password setup email</button><button type="button" onClick={()=>setForm(blank())}>New school user</button></form><p role="status">{message}</p><label>Search school users<input value={query} onChange={e=>setQuery(e.target.value)}/></label>{users.filter(user=>[user.name,user.email,user.username,user.role].join(' ').toLowerCase().includes(query.toLowerCase())).map(user=><article className="school-panel" key={user.uid}><strong>{user.name||user.email}</strong><p>{user.email} | {user.role} | {user.active?'Active':'Inactive'} | Last sign-in: {user.lastSignIn||'Not recorded'}</p>{user.uid!==session.uid&&!['SUPER_ADMIN','SCHOOL_SUPER_ADMIN','Super Admin'].includes(user.role)&&<button onClick={()=>setForm({...blank(),...user,role:roles.includes(user.role)?user.role:roleAliases[user.role]||'READ_ONLY'})}>Edit school user</button>}</article>)}</div>;
}
