import { useLanguage } from "../design/language";
import StudentLookup from "../components/StudentLookup";
import { useState } from "react";
import { readStored, useStoredState, localDate } from "../storage";
import { availableUnits, validateLoan } from "../services/lending";
import { exportRows } from "../services/excel";
import { PageHeading, EmptyState } from "../design/SchoolUI";
import { notify } from "../components/Feedback";

export default function Sports({ onNavigate }) {
  const { t } = useLanguage();
  const students = readStored("erp_pro_students", []).filter(s => !s.archivedAt);
  const [athletes, saveAthletes] = useStoredState("erp_pro_sports_athletes", []), [equipment, saveEquipment] = useStoredState("erp_pro_sports_equipment", []), [loans, saveLoans] = useStoredState("erp_pro_equipment_loans", []);
  const [form, setForm] = useState({ studentId: "", sport: "", ageGroup: "", weightCategory: "", competition: "", level: "", result: "", medal: "" });
  const [item, setItem] = useState({ name: "", sport: "", quantity: "1", condition: "Good" }), [loan, setLoan] = useState({ studentId: "", itemRef: "", quantity: "1", dueDate: "" }), [query, setQuery] = useState("");
  const addAthlete = () => { const student = students.find(s => s.id === form.studentId); if (!student || !form.sport.trim()) return notify("Select a student and sport."); if (saveAthletes([...athletes, { ...form, student: student.name, grNo: student.grNo, className: student.className, id: crypto.randomUUID() }])) { setForm({ ...form, competition: "", result: "", medal: "" }); notify("Athlete record saved."); } };
  const addEquipment = () => { if (!item.name.trim() || !Number.isInteger(Number(item.quantity)) || Number(item.quantity) <= 0) return notify("Equipment name and positive whole-number quantity required."); if (saveEquipment([...equipment, { ...item, id: crypto.randomUUID(), quantity: Number(item.quantity), available: Number(item.quantity) }])) setItem({ name: "", sport: "", quantity: "1", condition: "Good" }); };
  const available = item => availableUnits(item, loans, item.id) - loans.filter(l => l.itemRef === item.id && l.returned && ["Lost", "Damaged"].includes(l.returnCondition)).reduce((sum, l) => sum + l.quantity, 0);
  const issue = () => { const equipmentItem = equipment.find(i => i.id === loan.itemRef), student = students.find(s => s.id === loan.studentId); const error = validateLoan(loan, equipmentItem ? available(equipmentItem) : 0, localDate()); if (error || !student) return notify(error || "Choose an active student."); if (saveLoans([...loans, { ...loan, id: crypto.randomUUID(), studentName: student.name, grNo: student.grNo, equipmentName: equipmentItem.name, quantity: Number(loan.quantity), issueDate: localDate(), returned: false }])) notify("Equipment issued."); };
  const returned = (id, condition) => { if (!condition) return; if (saveLoans(loans.map(l => l.id === id && !l.returned ? { ...l, returned: true, returnDate: localDate(), returnCondition: condition } : l))) notify("Return recorded. Lost/damaged units remain unavailable."); };
  const visible = athletes.filter(a => Object.values(a).join(" ").toLowerCase().includes(query.toLowerCase()));
  return <div className="core-page"><PageHeading eyebrow="PLAY. PARTICIPATE. ACHIEVE." title="Sports & equipment" description="Student athletes, competitions, achievements and accountable equipment lending." /><StudentLookup students={students} onSelect={s => { setForm({ ...form, studentId: s.id }); setLoan({ ...loan, studentId: s.id }); }} /><section className="school-panel workflow-panel"><h3>Athlete / competition record</h3><div className="form-grid"><label>{t("Student")}<select aria-label="Student" value={form.studentId} onChange={e => setForm({ ...form, studentId: e.target.value })}><option value="">Select student</option>{students.map(s => <option key={s.id} value={s.id}>{s.name} · {s.grNo}</option>)}</select></label>{Object.keys(form).filter(k => k !== "studentId").map(key => <label key={key}>{t(key)}<input value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}</div><button onClick={addAthlete}>{t("Save athlete")}</button><button onClick={() => onNavigate("Formats", { initialType: "Sports Certificate", studentId: form.studentId })}>Sports certificate</button></section><div className="domain-toolbar"><label>Search athlete / sport<input value={query} onChange={e => setQuery(e.target.value)} /></label><button onClick={() => exportRows(visible, "sports-students.xlsx")}>Export sports students</button><button disabled={!visible.some(a => a.studentId)} onClick={() => onNavigate("Communications", { initialStudentIds: [...new Set(visible.map(a => a.studentId).filter(Boolean))], initialMessage: "School sports update: " + query })}>Contact sports group parents</button></div>{visible.length ? <div className="record-grid">{visible.map(a => <article className="school-panel workflow-panel" key={a.id}><h3>{a.student}</h3><p>{a.sport} · {a.ageGroup} · {a.weightCategory} · {a.level}</p><p>{a.competition} · {a.result || "Result pending"} · {a.medal}</p><button onClick={() => onNavigate("Formats", { initialType: "Achievement Certificate", studentId: a.studentId })}>Certificate</button></article>)}</div> : <EmptyState icon="trophy" title="Every achievement starts with participation" description="Add a student athlete and their sport to begin." />}
    <section className="school-panel workflow-panel"><h3>Equipment Master</h3><div className="form-grid">{Object.keys(item).map(key => <label key={key}>{t(key)}<input type={key === "quantity" ? "number" : "text"} value={item[key]} onChange={e => setItem({ ...item, [key]: e.target.value })} /></label>)}</div><button onClick={addEquipment}>{t("Save equipment")}</button>{equipment.map(i => <p key={i.id}>{i.name} · {i.sport} · {available(i)}/{i.quantity} available · {i.condition}</p>)}</section>
    <section className="school-panel workflow-panel"><h3>Equipment issue / return</h3><div className="form-grid"><label>Borrowing student<select aria-label="Borrowing student" value={loan.studentId} onChange={e => setLoan({ ...loan, studentId: e.target.value })}><option value="">Select student</option>{students.map(s => <option key={s.id} value={s.id}>{s.name} · {s.grNo}</option>)}</select></label><label>{t("Equipment")}<select aria-label="Equipment" value={loan.itemRef} onChange={e => setLoan({ ...loan, itemRef: e.target.value })}><option value="">Select equipment</option>{equipment.map(i => <option key={i.id} value={i.id}>{i.name} ({available(i)} available)</option>)}</select></label><label>Issue quantity<input type="number" value={loan.quantity} onChange={e => setLoan({ ...loan, quantity: e.target.value })} /></label><label>Return due<input type="date" value={loan.dueDate} onChange={e => setLoan({ ...loan, dueDate: e.target.value })} /></label></div><button onClick={issue}>{t("Issue equipment")}</button><button onClick={() => exportRows(loans, "equipment-history.xlsx")}>Export equipment history</button>{loans.length ? <div className="table-scroll"><table><thead><tr><th>Student / equipment</th><th>{t("Quantity")}</th><th>Due</th><th>Condition / return</th></tr></thead><tbody>{loans.map(l => <tr key={l.id}><td>{l.studentName} · {l.equipmentName}</td><td>{l.quantity}</td><td>{l.dueDate}</td><td>{l.returned ? `${l.returnCondition} · ${l.returnDate}` : <select aria-label={`Return ${l.id}`} value="" onChange={e => returned(l.id, e.target.value)}><option value="">Record return</option><option>Good</option><option>Damaged</option><option>Lost</option></select>}</td></tr>)}</tbody></table></div> : <p>No equipment has been issued yet.</p>}</section></div>;
}
