import { notify } from "../components/Feedback";
import { useState } from "react";
import { useStoredState } from "../storage";

export default function Sports() {
  const [athletes, setAthletes] = useStoredState("erp_pro_sports_athletes", []);
  const [equipment, setEquipment] = useStoredState("erp_pro_sports_equipment", []);
  const [form, setForm] = useState({ student: "", sport: "", ageGroup: "", level: "", competition: "", result: "", medal: "" });
  const [item, setItem] = useState({ name: "", sport: "", quantity: "", condition: "नवीन" });
  const addAthlete = () => { if (!form.student.trim() || !form.sport.trim()) { notify("विद्यार्थी आणि खेळाचे नाव भरा"); return; } if (!setAthletes([...athletes, { id: crypto.randomUUID(), ...form }])) return; setForm({ student: "", sport: "", ageGroup: "", level: "", competition: "", result: "", medal: "" }); notify("Athlete profile जतन झाली"); };
  const addEquipment = () => { if (!item.name.trim() || !item.quantity) { notify("Equipment आणि quantity भरा"); return; } if (!setEquipment([...equipment, { id: crypto.randomUUID(), ...item, available: item.quantity }])) return; setItem({ name: "", sport: "", quantity: "", condition: "नवीन" }); notify("Sports equipment जतन झाले"); };
  return <div className="page module-page"><div className="module-heading"><div><span className="eyebrow">STUDENT WELLBEING</span><h2>क्रीडा व्यवस्थापन</h2><p>Athlete profiles, competitions आणि equipment inventory.</p></div><div className="module-count">{athletes.length}<span>athletes</span></div></div><section className="workflow-panel"><div className="panel-title"><h3>Athlete Profile</h3><span>पालक notificationसाठी student contact वापरा</span></div><div className="form-grid">{[["विद्यार्थी","student"],["खेळाचे नाव","sport"],["Age Group","ageGroup"],["Level","level"],["Competition","competition"],["Result","result"],["Medal / Position","medal"]].map(([label,key]) => <label key={key}>{label}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><button onClick={addAthlete}>Athlete जतन करा</button></section><section className="workflow-panel"><div className="panel-title"><h3>Sports Equipment Issue / Return तयारी</h3><span>Available quantity track करा</span></div><div className="form-grid">{[["Equipment","name"],["Sport","sport"],["Quantity","quantity"],["Condition","condition"]].map(([label,key]) => <label key={key}>{label}<input value={item[key]} onChange={(event) => setItem({ ...item, [key]: event.target.value })} /></label>)}</div><button onClick={addEquipment}>Equipment जतन करा</button></section><div className="record-grid">{athletes.map((athlete) => <article className="record-card text-record" key={athlete.id}><div className="record-card-body"><span className="record-kicker">{athlete.sport} · {athlete.level || "Level नोंद नाही"}</span><h3>{athlete.student}</h3><p>{athlete.competition || "स्पर्धा नोंद नाही"} · {athlete.result || "निकाल प्रलंबित"} · {athlete.medal || "पदक नाही"}</p></div></article>)}</div>{athletes.length === 0 && <div className="empty-state"><strong>Athlete profiles उपलब्ध नाहीत</strong><span>वरील formमधून पहिली नोंद तयार करा.</span></div>}<div className="secondary-metrics"><span>Equipment <b>{equipment.length}</b></span><span>Available units <b>{equipment.reduce((total, entry) => total + Number(entry.available || 0), 0)}</b></span></div></div>;
}
