import {useState} from 'react';
import {readStored,localDate} from '../storage';
import {studentStatuses,lifecycleActive} from '../services/studentLifecycle';
import {previewMovements,commitMovements} from '../services/lifecycleStore';
import {exportRows} from '../services/excel';
import {notify} from '../components/Feedback';
import {PageHeading} from '../design/SchoolUI';

export default function StudentLifecycle({studentId,role,onNavigate,initialStatus}){
 const [revision,refresh]=useState(0),[query,setQuery]=useState(''),[status,setStatus]=useState(initialStatus||''),[year,setYear]=useState(''),[standard,setStandard]=useState(''),[ids,setIds]=useState(studentId?[studentId]:[]),[preview,setPreview]=useState(null),[reviewed,setReviewed]=useState(false),[overrides,setOverrides]=useState({});
 const [form,setForm]=useState({action:'Promote',academicYear:'',division:'',reason:'',className:'',rollNo:'',leavingDate:localDate(),transferDestination:'',lcNumber:'',lcIssueDate:'',remarks:'',status:'Active'});
 const students=readStored('erp_pro_students',[]),history=readStored('erp_pro_academic_history',[]),movements=readStored('erp_pro_student_movements',[]),results=readStored('erp_pro_results',[]);
 const visible=students.filter(s=>(!year||s.academicYear===year)&&(!standard||s.className===standard)&&(!status||(status==='Archived'?!!s.archivedAt:(s.status||'Active')===status))&&[s.name,s.student_name_mr,s.grNo,s.admissionNo].join(' ').toLowerCase().includes(query.toLowerCase()));
 const clear=()=>{setPreview(null);setReviewed(false)};
 const update=(key,value)=>{setForm({...form,[key]:value});clear()};
 const choose=(id,checked)=>{setIds(checked?[...new Set([...ids,id])]:ids.filter(i=>i!==id));clear()};
 const prepare=()=>{try{setPreview(previewMovements(ids,id=>({...form,...overrides[id],...(form.action==='Promote'||['Repeat','Detained','Result Pending'].includes(form.action)?{division:form.division||students.find(s=>s.id===id)?.division,rollNo:overrides[id]?.rollNo??students.find(s=>s.id===id)?.rollNo}: {})})));setReviewed(false)}catch(e){notify(e.message)}};
 const confirm=()=>{if(!reviewed||!preview)return;try{commitMovements(preview);clear();setIds([]);refresh(revision+1);notify('Lifecycle changes saved. Student IDs and linked history retained.')}catch(e){notify(e.message)}};
 const rows=visible.map(s=>({studentId:s.id,GR:s.grNo,Name:s.name,Status:s.archivedAt?'Archived':s.status||'Active',AcademicYear:s.academicYear,Standard:s.className,Division:s.division,Roll:s.rollNo}));
 const selected=students.filter(s=>ids.includes(s.id));
 const movementRows=movements.filter(h=>!ids.length||ids.includes(h.studentId));
 return <div className="core-page"><PageHeading eyebrow="ONE STUDENT · EVERY ACADEMIC YEAR" title="Student Lifecycle & Year-End" description="Promote, repeat, transfer or leave school without creating another student profile. Review results, preview changes, then confirm."/>
 <section className="school-panel workflow-panel"><div className="form-grid"><label>Search all student records<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Status filter<select aria-label="Status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses, including archived</option>{studentStatuses.map(v=><option key={v}>{v}</option>)}</select></label><label>Source academic year<select aria-label="Source academic year" value={year} onChange={e=>{setYear(e.target.value);setIds([]);clear()}}><option value="">All years</option>{[...new Set(students.map(s=>s.academicYear).filter(Boolean))].map(y=><option key={y}>{y}</option>)}</select></label><label>Source class<select aria-label="Source class" value={standard} onChange={e=>{setStandard(e.target.value);setIds([]);clear()}}><option value="">All classes</option>{[...new Set(students.map(s=>s.className))].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="import-actions"><button onClick={()=>{setIds(visible.filter(lifecycleActive).map(s=>s.id));clear()}}>Select visible enrolled students</button><button onClick={()=>{setIds([]);clear()}}>Clear selection</button><button onClick={()=>exportRows(rows,'student-lifecycle.xlsx')}>Export Excel</button><button onClick={()=>exportRows(rows,'student-lifecycle.csv')}>Export CSV</button><button onClick={()=>window.print()}>Print / PDF</button><button onClick={()=>onNavigate('LongAbsence')}>Long Absent Students</button></div>
 <div className="table-scroll"><table><thead><tr><th>Select</th><th>Student / GR</th><th>Year / Class / Roll</th><th>Status</th><th>Review results</th><th>Year-end decision / roll override</th></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><input aria-label={`Select ${s.name}`} type="checkbox" checked={ids.includes(s.id)} onChange={e=>choose(s.id,e.target.checked)}/></td><td><button onClick={()=>onNavigate('Students',{studentId:s.id})}>{s.name}</button><br/>{s.grNo}</td><td>{s.academicYear||'Set academic year in Student Master'} · {s.className}/{s.division} · {s.rollNo}</td><td>{s.archivedAt?'Archived':s.status||'Active'}</td><td><details><summary>Result records ({results.filter(r=>r.studentId===s.id&&r.academicYear===s.academicYear).length})</summary>{results.filter(r=>r.studentId===s.id&&r.academicYear===s.academicYear).map(r=><p key={r.id}>{r.exam}: {r.subject} {r.obtainedMarks}/{r.maxMarks}</p>)}<small>Missing or untagged results are not inferred as a pass.</small></details></td><td><select aria-label={`Decision ${s.name}`} value={overrides[s.id]?.action||''} onChange={e=>{setOverrides({...overrides,[s.id]:{...overrides[s.id],action:e.target.value||form.action}});clear()}}><option value="">Use common action</option>{['Promote','Repeat','Detained','Result Pending','School Left','Transferred','Passed Out'].map(a=><option key={a}>{a}</option>)}</select><input aria-label={`New roll ${s.name}`} placeholder="Keep current roll" value={overrides[s.id]?.rollNo??''} onChange={e=>{setOverrides({...overrides,[s.id]:{...overrides[s.id],rollNo:e.target.value}});clear()}}/></td></tr>)}</tbody></table></div></section>
 <section className="school-panel workflow-panel"><h2>Review and process {ids.length} selected student(s)</h2><div className="form-grid"><label>Lifecycle action<select aria-label="Lifecycle action" value={form.action} onChange={e=>{update('action',e.target.value);setOverrides({})}}>{['Promote','Repeat','Detained','Result Pending','Class Transfer','Set Initial Academic Year','School Left','Transferred','Passed Out','School Completed','TC/LC Issued','Archive','Delete Student','Restore','Set Status'].map(a=><option key={a}>{a}</option>)}</select></label><label>Next academic year<input placeholder="2027-28" value={form.academicYear} onChange={e=>update('academicYear',e.target.value)}/></label><label>Destination division<input value={form.division} onChange={e=>update('division',e.target.value)}/></label><label>Destination standard (class transfer)<input value={form.className} onChange={e=>update('className',e.target.value)}/></label><label>Roll number (class transfer)<input value={form.rollNo} onChange={e=>update('rollNo',e.target.value)}/></label><label>Reason (required)<input value={form.reason} onChange={e=>update('reason',e.target.value)}/></label><label>New status<select aria-label="New status" value={form.status} onChange={e=>update('status',e.target.value)}>{['Active','Long Absent','Suspended','Inactive'].map(v=><option key={v}>{v}</option>)}</select></label>{['leavingDate','transferDestination','lcNumber','lcIssueDate','remarks'].map(k=><label key={k}>{({leavingDate:'Date of leaving',transferDestination:'Transfer destination',lcNumber:'LC / TC number',lcIssueDate:'LC issue date',remarks:'Leaving remarks'})[k]}<input type={k.endsWith('Date')?'date':'text'} value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div><p>Delete Student is a soft archive. Restore restores the previous status; a previously withdrawn student remains withdrawn until explicitly reactivated. Academic attendance snapshots use June–May unless an enrollment start was recorded. Original dated records remain intact.</p><button onClick={prepare}>Preview lifecycle changes</button>
 {preview&&<><div className="table-scroll"><table><thead><tr><th>Student</th><th>Action</th><th>Before</th><th>After</th></tr></thead><tbody>{preview.plans.map(p=><tr key={p.student.id}><td>{p.student.name} · {p.student.grNo}</td><td>{p.movement.action}</td><td>{JSON.stringify(p.movement.oldValue)}</td><td>{JSON.stringify(p.movement.newValue)}</td></tr>)}</tbody></table></div><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed results, selected students and every proposed change.</label><button disabled={!reviewed} onClick={confirm}>Confirm lifecycle changes</button></>}
 </section><section className="school-panel workflow-panel"><h2>Academic and movement history</h2><button onClick={()=>exportRows(movementRows,"student-movements.xlsx")}>Export movement Excel</button><button onClick={()=>exportRows(movementRows,"student-movements.csv")}>Export movement CSV</button><p>{ids.length?'Selected students':'All students'} · snapshots supplement original attendance, marks, fees, certificates and communication records.</p><button onClick={()=>exportRows(history.filter(h=>!ids.length||ids.includes(h.studentId)),'year-wise-student-history.xlsx')}>Export year history Excel</button><button onClick={()=>exportRows(history.filter(h=>!ids.length||ids.includes(h.studentId)),'year-wise-student-history.csv')}>Export year history CSV</button>{history.filter(h=>!ids.length||ids.includes(h.studentId)).map(h=><details key={h.id}><summary>{students.find(s=>s.id===h.studentId)?.name} · {h.academicYear} · {h.className}/{h.division} · {h.promotionStatus}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(h,null,2)}</pre></details>)}<div className="table-scroll"><table><thead><tr><th>Date / user</th><th>Student</th><th>Action / reason</th><th>Old → new</th></tr></thead><tbody>{movements.filter(h=>!ids.length||ids.includes(h.studentId)).slice().reverse().map(h=><tr key={h.id}><td>{h.createdAt||h.date}<br/>{h.actor||'Legacy record — actor unavailable'}</td><td>{h.studentName||students.find(s=>s.id===h.studentId)?.name}</td><td>{h.action||h.type} · {h.reason}</td><td>{JSON.stringify(h.oldValue)} → {JSON.stringify(h.newValue)}</td></tr>)}</tbody></table></div></section>
 {role==='Super Admin'&&<section className="school-panel workflow-panel"><h2>Permanent deletion — locked</h2><p>Warning: permanent deletion can destroy linked academic and financial history. Verified server Super Admin authorization, a server audit log and final confirmation are required. Role preview cannot authorize deletion.</p>{selected.map(s=><p key={s.id}>{s.name}: {results.filter(r=>r.studentId===s.id).length} result records; {readStored('erp_pro_certificates',[]).filter(r=>r.studentId===s.id).length} certificates; {readStored('erp_pro_fee_ledger',[]).filter(r=>r.studentId===s.id).length} fee records; {Object.values(readStored('erp_pro_attendance',{})).filter(d=>d[s.id]).length} attendance days; {readStored('erp_pro_absence_communications',[]).filter(r=>r.studentId===s.id).length} communication records. Other linked modules require server-wide review.</p>)}<button disabled>Permanent Delete — server authorization required</button></section>}
 </div>;
}
