import { useState } from 'react';
import { downloadStudentTemplate, exportStudents } from '../services/excel';
import { StudentActions } from '../components/StudentActions';
import { notify } from '../components/Feedback';
import { Avatar, EmptyState, PageHeading } from '../design/SchoolUI';
import { useLanguage } from '../design/language';

export default function StudentDirectory({ students, visibleStudents, query, setQuery, classFilter, setClassFilter, divisionFilter, setDivisionFilter, showArchived, setShowArchived, onCreate, onImport, onSelect, onDelete, onEdit, onAction, onNavigate }) {
 const {t}=useLanguage();
 const [scanOpen,setScanOpen]=useState(false),[reference,setReference]=useState(''),[page,setPage]=useState(0),[size,setSize]=useState(25),[sort,setSort]=useState('name'),[year,setYear]=useState('');
 const classes=[...new Set(students.map(s=>s.className).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
 const divisions=[...new Set(students.filter(s=>!classFilter||s.className===classFilter).map(s=>s.division).filter(Boolean))].sort();
 const years=[...new Set(students.map(s=>s.academicYear).filter(Boolean))].sort().reverse();
 const filtered=visibleStudents.filter(s=>!year||s.academicYear===year).slice().sort((a,b)=>String(a[sort]||'').localeCompare(String(b[sort]||''),undefined,{numeric:true})||String(a.id).localeCompare(String(b.id)));
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages-1),shown=filtered.slice(current*size,(current+1)*size);
 const lookup=event=>{event.preventDefault();let id='';try{if(reference.trim().startsWith('schoolerp:student:v1:'))id=decodeURIComponent(reference.trim().slice('schoolerp:student:v1:'.length));}catch{/* malformed references do not match */}const matches=students.filter(s=>id?String(s.id)===id:s.grNo===reference.trim());if(matches.length!==1)return notify('No unique student matches that reference. Check the GR or QR value.');onSelect(matches[0].id);};
 return <div className="core-page student-directory">
 <PageHeading eyebrow={t('STUDENTS / RECORDS','विद्यार्थी / नोंदी')} title={t('Student Master','विद्यार्थी मास्टर')} description={t('Manage enrollment, family contacts and student history.','प्रवेश, पालक संपर्क आणि विद्यार्थ्यांचा इतिहास व्यवस्थापित करा.')}><div className="student-master-primary-actions"><button className="school-button" aria-label={t('Add student','विद्यार्थी जोडा')} onClick={onCreate}>+ {t('Add Student','विद्यार्थी जोडा')}</button><button className="school-button secondary" onClick={onImport}>{t('Import Excel','Excel आयात')}</button><button className="school-button secondary" onClick={() => downloadStudentTemplate()}>{t('Download Excel Template','Excel नमुना डाउनलोड')}</button><button className="school-button secondary" onClick={() => exportStudents(students,'all-students.xlsx')}>{t('Export Excel','Excel निर्यात')}</button></div></PageHeading>
 <section className="student-master-tools"><span><strong>{students.length}</strong> {showArchived?'inactive / archived':'enrolled'} students · {classes.length} classes</span><div><button onClick={()=>onNavigate('Lifecycle')}>Bulk Promotion / History</button><button onClick={()=>onNavigate('PhotoImport')}>Excel + Photo Folder</button><button onClick={()=>setScanOpen(!scanOpen)} aria-expanded={scanOpen}>Find by QR / GR</button></div></section>
 {scanOpen&&<form className="qr-lookup" onSubmit={lookup}><label>Student QR reference or GR number<input value={reference} onChange={e=>setReference(e.target.value)} required/></label><button className="school-button" type="submit">Find student</button><p>Paste a scanned reference or enter the exact GR number.</p></form>}
 <section className="school-panel directory-panel"><div className="directory-toolbar"><input aria-label="Search students" placeholder="Search name, GR, admission or roll…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/>
 <select aria-label="Class filter" value={classFilter} onChange={e=>{setClassFilter(e.target.value);setDivisionFilter('');setPage(0)}}><option value="">All classes</option>{classes.map(v=><option key={v} value={v}>Class {v}</option>)}</select><select aria-label="Division filter" value={divisionFilter} onChange={e=>{setDivisionFilter(e.target.value);setPage(0)}}><option value="">All divisions</option>{divisions.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Student academic year filter" value={year} onChange={e=>{setYear(e.target.value);setPage(0)}}><option value="">All years</option>{years.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Sort students" value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}>{[['name','Name A–Z'],['grNo','GR number'],['rollNo','Roll number'],['className','Standard']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></div>
 <div className="student-table-options"><label><input type="checkbox" checked={showArchived} onChange={e=>{setShowArchived(e.target.checked);setPage(0)}}/>Show inactive / archived students</label><div><button onClick={()=>exportStudents(filtered,'students-filtered.xlsx')}>Export filtered Excel</button><button onClick={()=>exportStudents(filtered,'students-filtered.csv')}>Export filtered CSV</button></div></div>
 {shown.length?<div className="table-scroll directory-table-wrap" tabIndex={0} aria-label="Student Master table"><table className="directory-table"><thead><tr>{['Photo','Name','Marathi Name','Class','Division','Roll No','GR No','Academic Year','Father Mobile','Mother Mobile','Status','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{shown.map(s=><tr key={s.id} data-student-id={s.id}><td><Avatar name={s.name} photo={s.photo} size="small"/></td><td><button className="directory-student" onClick={()=>onSelect(s.id)}><strong>{s.student_name_en||s.name}</strong></button></td><td lang="mr">{s.student_name_mr||s.name_mr||'—'}</td><td>{s.className}</td><td>{s.division||'—'}</td><td>{s.rollNo||'—'}</td><td>{s.grNo}</td><td>{s.academicYear||'Not recorded'}</td><td>{s.fatherMobile||'—'}</td><td>{s.motherMobile||'—'}</td><td><span className={`school-status ${s.archivedAt?'neutral':'success'}`}>{s.archivedAt?'Archived':s.status||'Active'}</span></td><td><StudentActions student={s} onView={onSelect} onEdit={onEdit} onArchive={onDelete} onAction={onAction}/></td></tr>)}</tbody></table></div>:<EmptyState icon="users" title={students.length?'No students match your search':'No students added yet'} description="Add a student or import a reviewed Excel list." action={<button className="school-button secondary" onClick={students.length?()=>{setQuery('');setClassFilter('');setDivisionFilter('');setYear('')}:onCreate}>{students.length?'Clear filters':'Add a student'}</button>}/>}
 <div className="directory-footer"><span>{filtered.length?current*size+1:0}–{Math.min((current+1)*size,filtered.length)} of {filtered.length} students</span><div className="student-pagination"><label>Rows<select aria-label="Rows per page" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(0)}}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} / {pages}</span><button disabled={current+1>=pages} onClick={()=>setPage(current+1)}>Next</button></div></div></section></div>;
}
