import { useState } from "react";
import { downloadStudentTemplate } from "../services/excel";
import Icon from "../components/Icon";
import { notify } from "../components/Feedback";
import { Avatar, EmptyState, PageHeading } from "../design/SchoolUI";
import { studentDisplayName, useLanguage } from "../design/language";

export default function StudentDirectory({ students, visibleStudents, query, setQuery, classFilter, setClassFilter, divisionFilter, setDivisionFilter, onCreate, onImport, onExport, onSelect, onDelete }) {
  const { language, t } = useLanguage();
  const [scanOpen, setScanOpen] = useState(false);
  const [reference, setReference] = useState("");
  const classes = [...new Set(students.map(s => s.className).filter(Boolean))];
  const divisions = [...new Set(students.filter(s => !classFilter || s.className === classFilter).map(s => s.division).filter(Boolean))];
  const lookup = event => {
    event.preventDefault();
    let id = "";
    try { if (reference.trim().startsWith("schoolerp:student:v1:")) id = decodeURIComponent(reference.trim().slice("schoolerp:student:v1:".length)); } catch { /* Treat malformed reference as unmatched. */ }
    const matches = students.filter(s => id ? String(s.id) === id : s.grNo === reference.trim());
    if (matches.length !== 1) { notify(t("No unique student matches that reference. Check the GR or QR value.", "या संदर्भाशी एकमेव विद्यार्थी जुळत नाही. GR किंवा QR तपासा.")); return; }
    onSelect(matches[0].id);
  };
  return <div className="core-page student-directory">
    <section className="portal-student-import-strip"><div><strong>{t("Student Excel workspace", "विद्यार्थी Excel कार्यस्थान")}</strong><p>{t("Upload → Preview → Column Mapping → Validate → Duplicate Check → Import · Error Report", "अपलोड → पूर्वदृश्य → स्तंभ जुळवा → तपासा → दुबार नोंदी → आयात · त्रुटी अहवाल")}</p></div><button onClick={() => downloadStudentTemplate()}>{t("Download Excel Template", "Excel नमुना डाउनलोड")}</button><button onClick={onImport}>{t("Upload Excel", "Excel अपलोड")}</button><button onClick={onExport}>{t("Export Excel", "Excel निर्यात")}</button></section>
    <PageHeading eyebrow={t("STUDENT DIRECTORY", "विद्यार्थी सूची")} title={t("Know every learner.", "प्रत्येक विद्यार्थ्याला जाणून घ्या.")} description={t("Student information, thoughtfully organized in one place.", "विद्यार्थ्यांची माहिती एकाच ठिकाणी, सुव्यवस्थित.")}><button className="school-button secondary" onClick={onImport}><Icon name="upload" size={17} />{t("Import Excel", "Excel आयात")}</button><button className="school-button" onClick={onCreate}><Icon name="plus" size={18} />{t("Add student", "विद्यार्थी जोडा")}</button></PageHeading>
    <div className="directory-overview"><div><span className="metric-icon tone-blue"><Icon name="users" size={23} /></span><strong>{students.length}</strong><span>{t("Enrolled students", "नोंदणीकृत विद्यार्थी")}</span></div><div><strong>{classes.length}</strong><span>{t("Classes", "इयत्ता")}</span></div><div><strong>{students.filter(s => s.photo).length}</strong><span>{t("Student photos", "विद्यार्थी फोटो")}</span></div><button className="school-link" onClick={() => setScanOpen(!scanOpen)} aria-expanded={scanOpen}><Icon name="scan" size={19} />{t("Find by QR / GR", "QR / GR ने शोधा")}</button></div>
    {scanOpen && <form className="qr-lookup" onSubmit={lookup}><label>{t("Student QR reference or GR number", "विद्यार्थी QR संदर्भ किंवा GR क्रमांक")}<input autoFocus value={reference} onChange={e => setReference(e.target.value)} placeholder="schoolerp:student:v1:…" required /></label><button className="school-button" type="submit">{t("Find student", "विद्यार्थी शोधा")}<Icon name="arrow" size={16} /></button><p>{t("Paste a scanned reference or enter the GR. Camera scanning will be connected in the QR phase.", "स्कॅन केलेला संदर्भ किंवा GR भरा. कॅमेरा स्कॅनिंग QR टप्प्यात जोडले जाईल.")}</p></form>}
    <section className="school-panel directory-panel"><div className="directory-toolbar"><label className="input-with-icon"><Icon name="search" size={18} /><input aria-label={t("Search students", "विद्यार्थी शोधा")} placeholder={t("Search name, GR or roll number…", "नाव, GR किंवा हजेरी क्रमांक शोधा…")} value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label={t("Class filter", "इयत्ता filter")} value={classFilter} onChange={e => { setClassFilter(e.target.value); setDivisionFilter(""); }}><option value="">{t("All classes", "सर्व इयत्ता")}</option>{classes.map(name => <option key={name} value={name}>{t("Class", "इयत्ता")} {name}</option>)}</select><select aria-label={t("Division filter", "तुकडी filter")} value={divisionFilter} onChange={e => setDivisionFilter(e.target.value)}><option value="">{t("All divisions", "सर्व तुकड्या")}</option>{divisions.map(name => <option key={name}>{name}</option>)}</select><button className="school-button secondary" onClick={onExport} disabled={!students.length}><Icon name="download" size={16} />{t("Export", "निर्यात")}</button></div>
      {visibleStudents.length ? <div className="table-scroll directory-table-wrap"><table className="directory-table"><thead><tr><th>{t("Student", "विद्यार्थी")}</th><th>{t("GR number", "GR क्रमांक")}</th><th>{t("Class", "इयत्ता")}</th><th>{t("Roll no.", "हजेरी क्र.")}</th><th>{t("Parent", "पालक")}</th><th>{t("Status", "स्थिती")}</th><th><span className="sr-only">{t("Actions", "कृती")}</span></th></tr></thead><tbody>{visibleStudents.map((s, i) => <tr key={s.id} data-student-id={s.id}><td><button className="directory-student" onClick={() => onSelect(s.id)}><Avatar name={s.name} photo={s.photo} tone={i % 3 === 0 ? "blue" : i % 3 === 1 ? "green" : "amber"} /><span><strong>{studentDisplayName(s, language)}</strong><small>{language === "en" ? s.student_name_mr || s.name_mr || `GR ${s.grNo}` : s.student_name_en || `GR ${s.grNo}`}</small></span></button></td><td>{s.grNo}</td><td><span className="class-pill">{s.className} / {s.division || "—"}</span></td><td>{s.rollNo || "—"}</td><td><span>{s.guardianName || s.fatherName || s.motherName || t("Parent / guardian", "पालक / संरक्षक")}</span><small className="cell-secondary">{s.mobile ? `••••••${String(s.mobile).slice(-4)}` : t("No contact", "संपर्क नाही")}</small></td><td><span className="school-status success">{s.archivedAt ? "Archived" : s.status || t("Enrolled", "नोंदणीकृत")}</span></td><td><div className="directory-row-actions"><button className="icon-button" aria-label={`${t("View profile", "प्रोफाइल पहा")} ${s.grNo}`} onClick={() => onSelect(s.id)}><Icon name="arrow" size={18} /></button><button className="directory-delete" onClick={() => onDelete(s.id)} aria-label={s.archivedAt ? "Restore student" : "Archive student"} title={s.archivedAt ? "Restore student" : "Archive student"}><Icon name="close" size={15} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState icon="users" title={students.length ? t("No students match your search", "शोधाशी जुळणारे विद्यार्थी नाहीत") : t("Every journey begins with a name", "प्रत्येक प्रवासाची सुरुवात एका नावाने")} description={students.length ? t("Try another name, GR number or class.", "दुसरे नाव, GR किंवा वर्ग वापरून पहा.") : t("Add your first student or bring your class list from Excel.", "पहिला विद्यार्थी जोडा किंवा Excel मधून वर्ग यादी आयात करा.")} action={<button className="school-button secondary" onClick={students.length ? () => { setQuery(""); setClassFilter(""); setDivisionFilter(""); } : onCreate}>{students.length ? t("Clear filters", "फिल्टर काढा") : t("Add a student", "विद्यार्थी जोडा")}<Icon name="plus" size={15} /></button>} />}
      <div className="directory-footer"><span>{t(`Showing ${visibleStudents.length} of ${students.length} students`, `${students.length} पैकी ${visibleStudents.length} विद्यार्थी`)}</span><span><Icon name="shield" size={14} />{t("Student Master", "विद्यार्थी मास्टर")}</span></div>
    </section>
  </div>;
}
