import {studentReference} from '../services/studentReference';
import FamilyContactCard from '../components/FamilyContactCard';
import { useState } from "react";
import Icon from "../components/Icon";
import { localDate, readStored } from "../storage";
import { qrImage } from "../qr";
import { parentContacts } from "../services/absenceCommunication";
import { academicYear, studentDisplayName, useLanguage } from "../design/language";
import { Avatar, EmptyState, PageHeading, Panel } from "../design/SchoolUI";

export default function StudentProfile({ student, settings, onBack, onNavigate }) {
  const { language, t } = useLanguage();
  const [tab, setTab] = useState("overview");
  const history = readStored("erp_pro_attendance", {});
  const records = Object.entries(history).filter(([, students]) => students[student.id]).sort(([a], [b]) => b.localeCompare(a));
  const contacts = parentContacts(student);
  const results = readStored("erp_pro_results", []).filter(result => result.studentId ? String(result.studentId) === String(student.id) : result.grNo && result.grNo === student.grNo);
  const certificates = readStored("erp_pro_certificates", []).filter(item => item.studentId ? String(item.studentId) === String(student.id) : item.grNo && item.grNo === student.grNo);
  const qr = qrImage(studentReference(student.id,settings.tenantId));
  const present = records.filter(([, day]) => ["Present", "Late", "Half Day"].includes(day[student.id])).length;
  const percent = records.length ? Math.round(present / records.length * 100) : null;
  const fields = [["Full name · original", "पूर्ण नाव · मूळ", student.student_name_en || student.name], ["Marathi name", "मराठी नाव", student.student_name_mr || student.name_mr], ["Date of birth", "जन्म दिनांक", student.dob], ["Gender", "लिंग", student.gender], ["Blood group", "रक्तगट", student.bloodGroup], ["Academic year", "शैक्षणिक वर्ष", student.academicYear || academicYear(settings)], ["Address", "पत्ता", language === "mr" ? student.address_mr || student.address : student.address_en || student.address]];
  return <div className="core-page student-profile">
    <button onClick={()=>onNavigate("Lifecycle",{studentId:student.id})}>Academic history / lifecycle actions</button><button className="school-link profile-back" onClick={onBack}><Icon name="back" size={16} />{t("Back to student directory", "विद्यार्थी सूचीकडे परत")}</button>
    <PageHeading eyebrow={t("STUDENT MASTER", "विद्यार्थी मास्टर")} title={t("Student Profile", "विद्यार्थ्याची संपूर्ण माहिती.")} description={t("One student record, connected across the school.", "एक विद्यार्थी नोंद, संपूर्ण शाळेसाठी.")}><button className="school-button secondary" onClick={() => onNavigate("Attendance", { initialClass: student.className, initialDivision: student.division })}><Icon name="calendar" size={17} />{t("Open attendance", "उपस्थिती उघडा")}</button></PageHeading>
    <section className="student-profile-hero"><div className="profile-cover"><span>{t("STUDENT RECORD", "प्रत्येक विद्यार्थ्याची एक कहाणी")}</span><Icon name="cap" size={84} /></div><div className="profile-identity"><Avatar name={student.name} photo={student.photo} size="portrait" /><div><span className="school-status success">{student.archivedAt?"Archived":student.status||t("Enrolled student", "नोंदणीकृत विद्यार्थी")}</span><h2>{studentDisplayName(student, language)}</h2><p>{language === "mr" ? student.student_name_en || student.name : student.student_name_mr || student.name_mr || t("Marathi name not entered", "मराठी नाव नोंदलेले नाही")}</p></div><div className="profile-class"><strong>{student.className}<span>{student.division || "—"}</span></strong><small>{t("CLASS / DIVISION", "इयत्ता / तुकडी")}</small></div></div><div className="profile-identifiers"><span>{t("GR number", "GR क्रमांक")}<strong>{student.grNo}</strong></span><span>{t("Roll number", "हजेरी क्रमांक")}<strong>{student.rollNo || "—"}</strong></span><span>{t("Academic year", "शैक्षणिक वर्ष")}<strong>{student.academicYear || academicYear(settings)}</strong></span><span>{t("Attendance", "उपस्थिती")}<strong>{percent === null ? "—" : `${percent}%`}<small>{t("of recorded days", "नोंदवलेल्या दिवसांची")}</small></strong></span></div></section>
    <FamilyContactCard student={student} onNavigate={onNavigate}/><div className="school-tabs" role="tablist" aria-label="Student profile sections">{[["overview", "Overview", "आढावा"], ["attendance", "Attendance", "उपस्थिती"], ["academics", "Academic records", "शैक्षणिक नोंदी"], ["documents", "Documents", "कागदपत्रे"]].map(([key, en, mr]) => <button role="tab" id={`student-tab-${key}`} aria-controls={`student-panel-${key}`} aria-selected={tab === key} key={key} onClick={() => setTab(key)}>{t(en, mr)}{key === "documents" && <span>{certificates.length}</span>}</button>)}</div>
    <div role="tabpanel" id={`student-panel-${tab}`} aria-labelledby={`student-tab-${tab}`}>
      {tab === "overview" && <div className="profile-columns"><div><Panel title={t("Student information", "विद्यार्थ्याची माहिती")} subtitle={t("Details from the central student record", "विद्यार्थी मास्टरमधील माहिती")}><dl className="student-information">{fields.map(([en, mr, value]) => <div key={en} className={en === "Address" ? "full-width" : ""}><dt>{t(en, mr)}</dt><dd>{value || <span className="missing-value">{t("Not entered", "नोंदलेले नाही")}</span>}</dd></div>)}</dl></Panel><Panel title={t("Parent & guardian contacts", "पालक व संरक्षक संपर्क")} subtitle={t("Contact details are shown only inside this workspace.", "संपर्क तपशील या कार्यस्थानात दाखवले जातात.")}><div className="profile-contacts">{contacts.length ? contacts.map(contact => <div key={contact.id}><Avatar name={contact.name} size="small" /><span><strong>{contact.name}</strong><small>{contact.label}</small></span><span className="parent-contact-value">{contact.mobile || t("Invalid number", "चुकीचा क्रमांक")}</span></div>) : <EmptyState compact icon="phone" title={t("No parent contacts added", "पालक संपर्क नोंदलेला नाही")} />}</div>{student.emergencyContact && <p className="profile-emergency"><Icon name="phone" size={16} />{t("Emergency contact", "आपत्कालीन संपर्क")}: {student.emergencyContact}</p>}</Panel></div><aside><Panel title={t("Student QR", "विद्यार्थी QR")}><div className="student-qr">{qr && <img src={qr} width="152" height="152" alt="Student QR" />}<strong>GR {student.grNo}</strong><p>{t("Scan or enter this reference inside the school workspace to find this student.", "विद्यार्थी शोधण्यासाठी शालेय कार्यस्थानात हा संदर्भ स्कॅन करा किंवा भरा.")}</p><span><Icon name="scan" size={15} />{t("Student reference only · no contact data", "फक्त विद्यार्थी संदर्भ · संपर्क डेटा नाही")}</span></div></Panel><div className="profile-note"><Icon name="book" size={24} /><h3>{t("One source. Less typing.", "एक नोंद. कमी टंकलेखन.")}</h3><p>{t("Class, GR number and parent contacts are taken from Student Master. Original names are kept unchanged.", "इयत्ता, GR आणि पालक संपर्क विद्यार्थी मास्टरमधून घेतले जातात. मूळ नावे बदलली जात नाहीत.")}</p></div></aside></div>}
      {tab === "attendance" && <Panel title={t("Attendance history", "उपस्थिती इतिहास")} subtitle={t(`${records.length} recorded days · through ${localDate()}`, `${records.length} नोंदवलेले दिवस · ${localDate()} पर्यंत`)}>{records.length ? <div className="table-scroll"><table><thead><tr><th>{t("Date", "दिनांक")}</th><th>{t("Status", "स्थिती")}</th></tr></thead><tbody>{records.map(([date, day]) => <tr key={date}><td>{date}</td><td><span className={`school-status ${day[student.id] === "Absent" ? "warning" : "success"}`}>{day[student.id]}</span></td></tr>)}</tbody></table></div> : <EmptyState compact icon="calendar" title={t("No attendance recorded yet", "अद्याप उपस्थिती नोंद नाही")} />}</Panel>}
      {tab === "academics" && <Panel title={t("Academic records", "शैक्षणिक नोंदी")}>{results.length ? <div className="table-scroll"><table><thead><tr><th>{t("Exam", "परीक्षा")}</th><th>{t("Subject", "विषय")}</th><th>{t("Marks", "गुण")}</th><th>{t("Grade", "श्रेणी")}</th></tr></thead><tbody>{results.map(result => <tr key={result.id}><td>{result.exam}</td><td>{result.subject}</td><td>{result.obtainedMarks}/{result.maxMarks}</td><td>{result.grade}</td></tr>)}</tbody></table></div> : <EmptyState compact icon="chart" title={t("No results published yet", "अद्याप निकाल नोंदलेला नाही")} description={t("Records matched to this student's ID or GR will appear here.", "या विद्यार्थ्याच्या ID किंवा GR शी जुळणाऱ्या नोंदी येथे दिसतील.")} />}</Panel>}
      {tab === "documents" && <Panel title={t("School documents", "शालेय कागदपत्रे")}>{certificates.length ? <div className="document-list">{certificates.map(item => <div key={item.id}><Icon name="award" size={24} /><span><strong>{item.reason}</strong><small>{item.certificateNo} · {item.issueDate}</small></span></div>)}</div> : <EmptyState compact icon="file" title={t("No documents issued yet", "अद्याप कागदपत्रे दिलेली नाहीत")} description={t("Issued certificate records will appear here.", "दिलेल्या प्रमाणपत्रांच्या नोंदी येथे दिसतील.")} />}</Panel>}
    </div>
  </div>;
}
