import { useState } from "react";
import { localDate, readStored } from "../storage";
import Icon from "../components/Icon";
import { Avatar, EmptyState, PageHeading, Panel } from "../design/SchoolUI";
import { studentDisplayName, useLanguage } from "../design/language";
import { attendanceSummary, calendarEvent, isActiveStudent, matchesClass, teacherClasses } from "../services/schoolOverview";

export default function TeacherDashboard({ onNavigate }) {
  const { language, t } = useLanguage();
  const teachers = readStored("erp_pro_teachers", []);
  const [teacherId, setTeacherId] = useState(() => String(teachers[0]?.id || ""));
  const teacher = teachers.find(item => String(item.id) === teacherId);
  const assignments = teacherClasses(teacher, readStored("erp_pro_classTeachers", []), teachers);
  const students = readStored("erp_pro_students", []).filter(s => isActiveStudent(s) && assignments.some(group => matchesClass(s, group)));
  const today = localDate();
  const day = readStored("erp_pro_attendance", {})[today] || {};
  const summary = attendanceSummary(students, day);
  const homework = readStored("erp_pro_homework", []).filter(item => assignments.some(group => matchesClass(item, group)));
  const events = readStored("erp_pro_calendar", []).map(calendarEvent).filter(item => item.date >= today).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 3);
  const followups = readStored("erp_pro_absence_followups", {});
  const absent = students.filter(s => day[s.id] === "Absent");
  return <div className="core-page teacher-workspace">
    <PageHeading eyebrow={t("TEACHING WORKSPACE", "शिक्षक कार्यस्थान")} title={t("A thoughtful start to your day.", "आपल्या दिवसाची उत्तम सुरुवात.")} description={t("Your classes. Your students. Your next step.", "आपले वर्ग. आपले विद्यार्थी. आपले पुढील पाऊल.")}><label className="teacher-view-select">{t("View teacher's workspace", "शिक्षकांचे कार्यस्थान पहा")}<select aria-label="Teacher workspace" value={teacherId} onChange={e => setTeacherId(e.target.value)}><option value="">{t("Choose a teacher", "शिक्षक निवडा")}</option>{teachers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></PageHeading>
    <p className="workspace-preview-note"><Icon name="eye" size={15} />{t("Administrator view of a teacher's assigned work. Individual staff sign-in will be connected after design approval.", "शिक्षकांच्या नेमून दिलेल्या कामाचा प्रशासकीय आढावा. वैयक्तिक शिक्षक प्रवेश डिझाइन मंजुरीनंतर जोडला जाईल.")}</p>
    {!teacher ? <Panel title={t("Your teaching team", "आपले शिक्षक वृंद")}><EmptyState icon="cap" title={t("Choose a teacher to begin", "सुरुवात करण्यासाठी शिक्षक निवडा")} description={t("Add teachers and assign their classes to create a personalized workspace.", "वैयक्तिक कार्यस्थानासाठी शिक्षकांची नोंद करा आणि वर्ग नेमून द्या.")} action={<button className="school-button" onClick={() => onNavigate("Teachers")}>{t("Open teacher directory", "शिक्षक सूची उघडा")}<Icon name="arrow" size={16} /></button>} /></Panel> : <>
      <section className="teacher-welcome"><Avatar name={teacher.name} photo={teacher.photo} size="large" /><div><span className="academic-eyebrow">{t("WELCOME TO YOUR CLASSROOM", "आपल्या वर्गात स्वागत आहे")}</span><h2>{t("Hello", "नमस्कार")}, {teacher.name}</h2><p>{teacher.subject || t("Teaching staff", "शिक्षक")} · {assignments.length} {t("assigned classes", "नेमून दिलेले वर्ग")}</p></div><button className="school-button" onClick={() => onNavigate("Attendance", { initialClass: assignments[0]?.className, initialDivision: assignments[0]?.division })}>{t("Take attendance", "उपस्थिती नोंदवा")}<Icon name="arrow" size={17} /></button></section>
      <section className="teacher-metrics">{[[students.length, "Assigned students", "नेमून दिलेले विद्यार्थी", "users"], [summary.pending, "Attendance pending", "उपस्थिती बाकी", "calendar"], [homework.length, "Homework records", "गृहपाठ नोंदी", "book"], [absent.length, "Absent students", "अनुपस्थित विद्यार्थी", "message"]].map(([count, en, mr, icon]) => <div key={en}><Icon name={icon} size={21} /><strong>{count}</strong><span>{t(en, mr)}</span></div>)}</section>
      <div className="dashboard-columns"><div className="dashboard-main-column"><Panel title={t("Your classes", "आपले वर्ग")} subtitle={t("Attendance and learning, in one place.", "उपस्थिती आणि अभ्यास, एकाच ठिकाणी.")}>
        {assignments.length ? <div className="teacher-class-list">{assignments.map(group => { const members = students.filter(s => matchesClass(s, group)); const stats = attendanceSummary(members, day); return <article key={`${group.className}/${group.division}`}><span className="class-number">{group.className}<small>{group.division || "—"}</small></span><div><h3>{t("Class", "इयत्ता")} {group.className} {group.division}</h3><p>{members.length} {t("students", "विद्यार्थी")} · {teacher.subject}</p><span className={`school-status ${stats.pending ? "warning" : "success"}`}>{stats.pending ? t(`${stats.pending} attendance entries pending`, `${stats.pending} उपस्थिती नोंदी बाकी`) : t("Register complete", "नोंदवही पूर्ण")}</span></div><button className="school-button secondary" onClick={() => onNavigate("Attendance", { initialClass: group.className, initialDivision: group.division })}>{t("Open class", "वर्ग उघडा")}<Icon name="arrow" size={15} /></button></article>; })}</div> : <EmptyState compact icon="users" title={t("No class assignments yet", "अद्याप वर्ग नेमलेले नाहीत")} description={t("Use class teacher settings in Attendance to assign this teacher.", "वर्ग नेमण्यासाठी उपस्थितीतील वर्गशिक्षक सेटिंग वापरा.")} action={<button className="school-link" onClick={() => onNavigate("Attendance")}>{t("Manage assignments", "वर्ग नेमणूक करा")}<Icon name="arrow" size={15} /></button>} />}
      </Panel><Panel title={t("Parent follow-up", "पालक संपर्क")} subtitle={t("A small conversation can make a difference.", "एक छोटा संवाद महत्त्वाचा ठरू शकतो.")}>
        {absent.length ? <div className="teacher-followups">{absent.slice(0, 5).map(s => <button key={s.id} onClick={() => onNavigate("Attendance", { initialClass: s.className, initialDivision: s.division })}><Avatar name={s.name} photo={s.photo} /><span><strong>{studentDisplayName(s, language)}</strong><small>{t("Class", "इयत्ता")} {s.className}/{s.division}</small></span><span className="school-status warning">{followups[JSON.stringify([today, String(s.id)])]?.status || t("Pending", "बाकी")}</span><Icon name="arrow" size={16} /></button>)}</div> : <EmptyState compact icon="message" title={t("No absence follow-ups today", "आज अनुपस्थिती संपर्क बाकी नाही")} description={t("Absent students from your assigned classes will appear here.", "आपल्या वर्गातील अनुपस्थित विद्यार्थी येथे दिसतील.")} />}
      </Panel></div><aside className="dashboard-side-column"><Panel title={t("Plan your next lesson", "पुढील अभ्यासाचे नियोजन")}><div className="teacher-quick-links">{[["Homework", "book", "Assign homework", "गृहपाठ द्या"], ["Classwork", "file", "Record classwork", "वर्गपाठ नोंदवा"], ["Results", "chart", "Review results", "निकाल पहा"], ["Timetable", "clock", "Open timetable", "वेळापत्रक उघडा"]].map(([key, icon, en, mr]) => <button key={key} onClick={() => onNavigate(key)}><Icon name={icon} /><span>{t(en, mr)}</span><Icon name="arrow" size={16} /></button>)}</div></Panel><Panel title={t("Coming up at school", "शाळेतील आगामी कार्यक्रम")}>
        {events.length ? <div className="school-upcoming">{events.map(event => <button key={event.id} onClick={() => onNavigate("Calendar")}><span><b>{event.date.slice(-2)}</b>{new Date(`${event.date}T12:00:00`).toLocaleDateString(language === "mr" ? "mr-IN" : "en-IN", { month: "short" })}</span><div><strong>{event.title}</strong><small>{event.time || event.type}</small></div></button>)}</div> : <EmptyState compact icon="calendar" title={t("Nothing scheduled yet", "अद्याप कार्यक्रम नियोजित नाहीत")} action={<button className="school-link" onClick={() => onNavigate("Calendar")}>{t("View calendar", "दिनदर्शिका पहा")}<Icon name="arrow" size={15} /></button>} />}
      </Panel></aside></div>
    </>}
  </div>;
}
